// Code generated by ent, DO NOT EDIT.

package copytransfer

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the copytransfer type in the database.
	Label = "copy_transfer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldCopyID holds the string denoting the copy_id field in the database.
	FieldCopyID = "copy_id"
	// FieldFromBranchID holds the string denoting the from_branch_id field in the database.
	FieldFromBranchID = "from_branch_id"
	// FieldToBranchID holds the string denoting the to_branch_id field in the database.
	FieldToBranchID = "to_branch_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldInitiatedBy holds the string denoting the initiated_by field in the database.
	FieldInitiatedBy = "initiated_by"
	// FieldReceivedBy holds the string denoting the received_by field in the database.
	FieldReceivedBy = "received_by"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldReceivedAt holds the string denoting the received_at field in the database.
	FieldReceivedAt = "received_at"
	// Table holds the table name of the copytransfer in the database.
	Table = "copy_transfers"
)

// Columns holds all SQL columns for copytransfer fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldCopyID,
	FieldFromBranchID,
	FieldToBranchID,
	FieldStatus,
	FieldInitiatedBy,
	FieldReceivedBy,
	FieldNotes,
	FieldReceivedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusIN_TRANSIT is the default value of the Status enum.
const DefaultStatus = StatusIN_TRANSIT

// Status values.
const (
	StatusIN_TRANSIT Status = "IN_TRANSIT"
	StatusRECEIVED   Status = "RECEIVED"
	StatusCANCELLED  Status = "CANCELLED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusIN_TRANSIT, StatusRECEIVED, StatusCANCELLED:
		return nil
	default:
		return fmt.Errorf("copytransfer: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the CopyTransfer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByCopyID orders the results by the copy_id field.
func ByCopyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCopyID, opts...).ToFunc()
}

// ByFromBranchID orders the results by the from_branch_id field.
func ByFromBranchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromBranchID, opts...).ToFunc()
}

// ByToBranchID orders the results by the to_branch_id field.
func ByToBranchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToBranchID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByInitiatedBy orders the results by the initiated_by field.
func ByInitiatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInitiatedBy, opts...).ToFunc()
}

// ByReceivedBy orders the results by the received_by field.
func ByReceivedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedBy, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByReceivedAt orders the results by the received_at field.
func ByReceivedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReceivedAt, opts...).ToFunc()
}
