// Code generated by ent, DO NOT EDIT.

package ebookpurchase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/library-service/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldTenantID, v))
}

// EbookID applies equality check predicate on the "ebook_id" field. It's identical to EbookIDEQ.
func EbookID(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldEbookID, v))
}

// MemberID applies equality check predicate on the "member_id" field. It's identical to MemberIDEQ.
func MemberID(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldMemberID, v))
}

// TreasuryIntentID applies equality check predicate on the "treasury_intent_id" field. It's identical to TreasuryIntentIDEQ.
func TreasuryIntentID(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldTreasuryIntentID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldAmount, v))
}

// DownloadToken applies equality check predicate on the "download_token" field. It's identical to DownloadTokenEQ.
func DownloadToken(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldDownloadToken, v))
}

// DownloadCount applies equality check predicate on the "download_count" field. It's identical to DownloadCountEQ.
func DownloadCount(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldDownloadCount, v))
}

// PurchasedAt applies equality check predicate on the "purchased_at" field. It's identical to PurchasedAtEQ.
func PurchasedAt(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldPurchasedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldTenantID, v))
}

// EbookIDEQ applies the EQ predicate on the "ebook_id" field.
func EbookIDEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldEbookID, v))
}

// EbookIDNEQ applies the NEQ predicate on the "ebook_id" field.
func EbookIDNEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldEbookID, v))
}

// EbookIDIn applies the In predicate on the "ebook_id" field.
func EbookIDIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldEbookID, vs...))
}

// EbookIDNotIn applies the NotIn predicate on the "ebook_id" field.
func EbookIDNotIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldEbookID, vs...))
}

// EbookIDGT applies the GT predicate on the "ebook_id" field.
func EbookIDGT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldEbookID, v))
}

// EbookIDGTE applies the GTE predicate on the "ebook_id" field.
func EbookIDGTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldEbookID, v))
}

// EbookIDLT applies the LT predicate on the "ebook_id" field.
func EbookIDLT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldEbookID, v))
}

// EbookIDLTE applies the LTE predicate on the "ebook_id" field.
func EbookIDLTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldEbookID, v))
}

// MemberIDEQ applies the EQ predicate on the "member_id" field.
func MemberIDEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldMemberID, v))
}

// MemberIDNEQ applies the NEQ predicate on the "member_id" field.
func MemberIDNEQ(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldMemberID, v))
}

// MemberIDIn applies the In predicate on the "member_id" field.
func MemberIDIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldMemberID, vs...))
}

// MemberIDNotIn applies the NotIn predicate on the "member_id" field.
func MemberIDNotIn(vs ...uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldMemberID, vs...))
}

// MemberIDGT applies the GT predicate on the "member_id" field.
func MemberIDGT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldMemberID, v))
}

// MemberIDGTE applies the GTE predicate on the "member_id" field.
func MemberIDGTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldMemberID, v))
}

// MemberIDLT applies the LT predicate on the "member_id" field.
func MemberIDLT(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldMemberID, v))
}

// MemberIDLTE applies the LTE predicate on the "member_id" field.
func MemberIDLTE(v uuid.UUID) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldMemberID, v))
}

// TreasuryIntentIDEQ applies the EQ predicate on the "treasury_intent_id" field.
func TreasuryIntentIDEQ(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDNEQ applies the NEQ predicate on the "treasury_intent_id" field.
func TreasuryIntentIDNEQ(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDIn applies the In predicate on the "treasury_intent_id" field.
func TreasuryIntentIDIn(vs ...string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldTreasuryIntentID, vs...))
}

// TreasuryIntentIDNotIn applies the NotIn predicate on the "treasury_intent_id" field.
func TreasuryIntentIDNotIn(vs ...string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldTreasuryIntentID, vs...))
}

// TreasuryIntentIDGT applies the GT predicate on the "treasury_intent_id" field.
func TreasuryIntentIDGT(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDGTE applies the GTE predicate on the "treasury_intent_id" field.
func TreasuryIntentIDGTE(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDLT applies the LT predicate on the "treasury_intent_id" field.
func TreasuryIntentIDLT(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDLTE applies the LTE predicate on the "treasury_intent_id" field.
func TreasuryIntentIDLTE(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDContains applies the Contains predicate on the "treasury_intent_id" field.
func TreasuryIntentIDContains(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldContains(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDHasPrefix applies the HasPrefix predicate on the "treasury_intent_id" field.
func TreasuryIntentIDHasPrefix(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldHasPrefix(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDHasSuffix applies the HasSuffix predicate on the "treasury_intent_id" field.
func TreasuryIntentIDHasSuffix(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldHasSuffix(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDIsNil applies the IsNil predicate on the "treasury_intent_id" field.
func TreasuryIntentIDIsNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIsNull(FieldTreasuryIntentID))
}

// TreasuryIntentIDNotNil applies the NotNil predicate on the "treasury_intent_id" field.
func TreasuryIntentIDNotNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotNull(FieldTreasuryIntentID))
}

// TreasuryIntentIDEqualFold applies the EqualFold predicate on the "treasury_intent_id" field.
func TreasuryIntentIDEqualFold(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEqualFold(FieldTreasuryIntentID, v))
}

// TreasuryIntentIDContainsFold applies the ContainsFold predicate on the "treasury_intent_id" field.
func TreasuryIntentIDContainsFold(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldContainsFold(FieldTreasuryIntentID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v decimal.Decimal) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldStatus, vs...))
}

// DownloadTokenEQ applies the EQ predicate on the "download_token" field.
func DownloadTokenEQ(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldDownloadToken, v))
}

// DownloadTokenNEQ applies the NEQ predicate on the "download_token" field.
func DownloadTokenNEQ(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldDownloadToken, v))
}

// DownloadTokenIn applies the In predicate on the "download_token" field.
func DownloadTokenIn(vs ...string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldDownloadToken, vs...))
}

// DownloadTokenNotIn applies the NotIn predicate on the "download_token" field.
func DownloadTokenNotIn(vs ...string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldDownloadToken, vs...))
}

// DownloadTokenGT applies the GT predicate on the "download_token" field.
func DownloadTokenGT(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldDownloadToken, v))
}

// DownloadTokenGTE applies the GTE predicate on the "download_token" field.
func DownloadTokenGTE(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldDownloadToken, v))
}

// DownloadTokenLT applies the LT predicate on the "download_token" field.
func DownloadTokenLT(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldDownloadToken, v))
}

// DownloadTokenLTE applies the LTE predicate on the "download_token" field.
func DownloadTokenLTE(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldDownloadToken, v))
}

// DownloadTokenContains applies the Contains predicate on the "download_token" field.
func DownloadTokenContains(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldContains(FieldDownloadToken, v))
}

// DownloadTokenHasPrefix applies the HasPrefix predicate on the "download_token" field.
func DownloadTokenHasPrefix(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldHasPrefix(FieldDownloadToken, v))
}

// DownloadTokenHasSuffix applies the HasSuffix predicate on the "download_token" field.
func DownloadTokenHasSuffix(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldHasSuffix(FieldDownloadToken, v))
}

// DownloadTokenIsNil applies the IsNil predicate on the "download_token" field.
func DownloadTokenIsNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIsNull(FieldDownloadToken))
}

// DownloadTokenNotNil applies the NotNil predicate on the "download_token" field.
func DownloadTokenNotNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotNull(FieldDownloadToken))
}

// DownloadTokenEqualFold applies the EqualFold predicate on the "download_token" field.
func DownloadTokenEqualFold(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEqualFold(FieldDownloadToken, v))
}

// DownloadTokenContainsFold applies the ContainsFold predicate on the "download_token" field.
func DownloadTokenContainsFold(v string) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldContainsFold(FieldDownloadToken, v))
}

// DownloadCountEQ applies the EQ predicate on the "download_count" field.
func DownloadCountEQ(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldDownloadCount, v))
}

// DownloadCountNEQ applies the NEQ predicate on the "download_count" field.
func DownloadCountNEQ(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldDownloadCount, v))
}

// DownloadCountIn applies the In predicate on the "download_count" field.
func DownloadCountIn(vs ...int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldDownloadCount, vs...))
}

// DownloadCountNotIn applies the NotIn predicate on the "download_count" field.
func DownloadCountNotIn(vs ...int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldDownloadCount, vs...))
}

// DownloadCountGT applies the GT predicate on the "download_count" field.
func DownloadCountGT(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldDownloadCount, v))
}

// DownloadCountGTE applies the GTE predicate on the "download_count" field.
func DownloadCountGTE(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldDownloadCount, v))
}

// DownloadCountLT applies the LT predicate on the "download_count" field.
func DownloadCountLT(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldDownloadCount, v))
}

// DownloadCountLTE applies the LTE predicate on the "download_count" field.
func DownloadCountLTE(v int) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldDownloadCount, v))
}

// PurchasedAtEQ applies the EQ predicate on the "purchased_at" field.
func PurchasedAtEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldEQ(FieldPurchasedAt, v))
}

// PurchasedAtNEQ applies the NEQ predicate on the "purchased_at" field.
func PurchasedAtNEQ(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNEQ(FieldPurchasedAt, v))
}

// PurchasedAtIn applies the In predicate on the "purchased_at" field.
func PurchasedAtIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIn(FieldPurchasedAt, vs...))
}

// PurchasedAtNotIn applies the NotIn predicate on the "purchased_at" field.
func PurchasedAtNotIn(vs ...time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotIn(FieldPurchasedAt, vs...))
}

// PurchasedAtGT applies the GT predicate on the "purchased_at" field.
func PurchasedAtGT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGT(FieldPurchasedAt, v))
}

// PurchasedAtGTE applies the GTE predicate on the "purchased_at" field.
func PurchasedAtGTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldGTE(FieldPurchasedAt, v))
}

// PurchasedAtLT applies the LT predicate on the "purchased_at" field.
func PurchasedAtLT(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLT(FieldPurchasedAt, v))
}

// PurchasedAtLTE applies the LTE predicate on the "purchased_at" field.
func PurchasedAtLTE(v time.Time) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldLTE(FieldPurchasedAt, v))
}

// PurchasedAtIsNil applies the IsNil predicate on the "purchased_at" field.
func PurchasedAtIsNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldIsNull(FieldPurchasedAt))
}

// PurchasedAtNotNil applies the NotNil predicate on the "purchased_at" field.
func PurchasedAtNotNil() predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.FieldNotNull(FieldPurchasedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EbookPurchase) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EbookPurchase) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EbookPurchase) predicate.EbookPurchase {
	return predicate.EbookPurchase(sql.NotPredicates(p))
}
