// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/acquisitionfund"
	"github.com/bengobox/library-service/internal/ent/predicate"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// AcquisitionFundUpdate is the builder for updating AcquisitionFund entities.
type AcquisitionFundUpdate struct {
	config
	hooks    []Hook
	mutation *AcquisitionFundMutation
}

// Where appends a list predicates to the AcquisitionFundUpdate builder.
func (_u *AcquisitionFundUpdate) Where(ps ...predicate.AcquisitionFund) *AcquisitionFundUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AcquisitionFundUpdate) SetUpdatedAt(v time.Time) *AcquisitionFundUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AcquisitionFundUpdate) SetTenantID(v uuid.UUID) *AcquisitionFundUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableTenantID(v *uuid.UUID) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBudgetID sets the "budget_id" field.
func (_u *AcquisitionFundUpdate) SetBudgetID(v uuid.UUID) *AcquisitionFundUpdate {
	_u.mutation.SetBudgetID(v)
	return _u
}

// SetNillableBudgetID sets the "budget_id" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableBudgetID(v *uuid.UUID) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetBudgetID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AcquisitionFundUpdate) SetName(v string) *AcquisitionFundUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableName(v *string) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AcquisitionFundUpdate) SetCode(v string) *AcquisitionFundUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableCode(v *string) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *AcquisitionFundUpdate) ClearCode() *AcquisitionFundUpdate {
	_u.mutation.ClearCode()
	return _u
}

// SetAllocatedAmount sets the "allocated_amount" field.
func (_u *AcquisitionFundUpdate) SetAllocatedAmount(v decimal.Decimal) *AcquisitionFundUpdate {
	_u.mutation.SetAllocatedAmount(v)
	return _u
}

// SetNillableAllocatedAmount sets the "allocated_amount" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableAllocatedAmount(v *decimal.Decimal) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetAllocatedAmount(*v)
	}
	return _u
}

// SetSpent sets the "spent" field.
func (_u *AcquisitionFundUpdate) SetSpent(v decimal.Decimal) *AcquisitionFundUpdate {
	_u.mutation.SetSpent(v)
	return _u
}

// SetNillableSpent sets the "spent" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableSpent(v *decimal.Decimal) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetSpent(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AcquisitionFundUpdate) SetDescription(v string) *AcquisitionFundUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AcquisitionFundUpdate) SetNillableDescription(v *string) *AcquisitionFundUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AcquisitionFundUpdate) ClearDescription() *AcquisitionFundUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AcquisitionFundMutation object of the builder.
func (_u *AcquisitionFundUpdate) Mutation() *AcquisitionFundMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AcquisitionFundUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AcquisitionFundUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AcquisitionFundUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AcquisitionFundUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AcquisitionFundUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := acquisitionfund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AcquisitionFundUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := acquisitionfund.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AcquisitionFund.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AcquisitionFundUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(acquisitionfund.Table, acquisitionfund.Columns, sqlgraph.NewFieldSpec(acquisitionfund.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(acquisitionfund.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(acquisitionfund.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BudgetID(); ok {
		_spec.SetField(acquisitionfund.FieldBudgetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(acquisitionfund.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(acquisitionfund.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(acquisitionfund.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.AllocatedAmount(); ok {
		_spec.SetField(acquisitionfund.FieldAllocatedAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Spent(); ok {
		_spec.SetField(acquisitionfund.FieldSpent, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(acquisitionfund.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(acquisitionfund.FieldDescription, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{acquisitionfund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AcquisitionFundUpdateOne is the builder for updating a single AcquisitionFund entity.
type AcquisitionFundUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AcquisitionFundMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AcquisitionFundUpdateOne) SetUpdatedAt(v time.Time) *AcquisitionFundUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AcquisitionFundUpdateOne) SetTenantID(v uuid.UUID) *AcquisitionFundUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableTenantID(v *uuid.UUID) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetBudgetID sets the "budget_id" field.
func (_u *AcquisitionFundUpdateOne) SetBudgetID(v uuid.UUID) *AcquisitionFundUpdateOne {
	_u.mutation.SetBudgetID(v)
	return _u
}

// SetNillableBudgetID sets the "budget_id" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableBudgetID(v *uuid.UUID) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetBudgetID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AcquisitionFundUpdateOne) SetName(v string) *AcquisitionFundUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableName(v *string) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *AcquisitionFundUpdateOne) SetCode(v string) *AcquisitionFundUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableCode(v *string) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// ClearCode clears the value of the "code" field.
func (_u *AcquisitionFundUpdateOne) ClearCode() *AcquisitionFundUpdateOne {
	_u.mutation.ClearCode()
	return _u
}

// SetAllocatedAmount sets the "allocated_amount" field.
func (_u *AcquisitionFundUpdateOne) SetAllocatedAmount(v decimal.Decimal) *AcquisitionFundUpdateOne {
	_u.mutation.SetAllocatedAmount(v)
	return _u
}

// SetNillableAllocatedAmount sets the "allocated_amount" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableAllocatedAmount(v *decimal.Decimal) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetAllocatedAmount(*v)
	}
	return _u
}

// SetSpent sets the "spent" field.
func (_u *AcquisitionFundUpdateOne) SetSpent(v decimal.Decimal) *AcquisitionFundUpdateOne {
	_u.mutation.SetSpent(v)
	return _u
}

// SetNillableSpent sets the "spent" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableSpent(v *decimal.Decimal) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetSpent(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AcquisitionFundUpdateOne) SetDescription(v string) *AcquisitionFundUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AcquisitionFundUpdateOne) SetNillableDescription(v *string) *AcquisitionFundUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *AcquisitionFundUpdateOne) ClearDescription() *AcquisitionFundUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// Mutation returns the AcquisitionFundMutation object of the builder.
func (_u *AcquisitionFundUpdateOne) Mutation() *AcquisitionFundMutation {
	return _u.mutation
}

// Where appends a list predicates to the AcquisitionFundUpdate builder.
func (_u *AcquisitionFundUpdateOne) Where(ps ...predicate.AcquisitionFund) *AcquisitionFundUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AcquisitionFundUpdateOne) Select(field string, fields ...string) *AcquisitionFundUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AcquisitionFund entity.
func (_u *AcquisitionFundUpdateOne) Save(ctx context.Context) (*AcquisitionFund, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AcquisitionFundUpdateOne) SaveX(ctx context.Context) *AcquisitionFund {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AcquisitionFundUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AcquisitionFundUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AcquisitionFundUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := acquisitionfund.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AcquisitionFundUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := acquisitionfund.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AcquisitionFund.name": %w`, err)}
		}
	}
	return nil
}

func (_u *AcquisitionFundUpdateOne) sqlSave(ctx context.Context) (_node *AcquisitionFund, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(acquisitionfund.Table, acquisitionfund.Columns, sqlgraph.NewFieldSpec(acquisitionfund.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AcquisitionFund.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, acquisitionfund.FieldID)
		for _, f := range fields {
			if !acquisitionfund.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != acquisitionfund.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(acquisitionfund.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(acquisitionfund.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.BudgetID(); ok {
		_spec.SetField(acquisitionfund.FieldBudgetID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(acquisitionfund.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(acquisitionfund.FieldCode, field.TypeString, value)
	}
	if _u.mutation.CodeCleared() {
		_spec.ClearField(acquisitionfund.FieldCode, field.TypeString)
	}
	if value, ok := _u.mutation.AllocatedAmount(); ok {
		_spec.SetField(acquisitionfund.FieldAllocatedAmount, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Spent(); ok {
		_spec.SetField(acquisitionfund.FieldSpent, field.TypeOther, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(acquisitionfund.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(acquisitionfund.FieldDescription, field.TypeString)
	}
	_node = &AcquisitionFund{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{acquisitionfund.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
