// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/auditlog"
	"github.com/bengobox/library-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditLogUpdate) SetUpdatedAt(v time.Time) *AuditLogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdate) SetTenantID(v uuid.UUID) *AuditLogUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTenantID(v *uuid.UUID) *AuditLogUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdate) SetUserID(v string) *AuditLogUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableUserID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdate) ClearUserID() *AuditLogUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *AuditLogUpdate) SetAggregateType(v string) *AuditLogUpdate {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAggregateType(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *AuditLogUpdate) SetAggregateID(v string) *AuditLogUpdate {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAggregateID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (_u *AuditLogUpdate) ClearAggregateID() *AuditLogUpdate {
	_u.mutation.ClearAggregateID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdate) SetAction(v string) *AuditLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableAction(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdate) SetChanges(v map[string]interface{}) *AuditLogUpdate {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdate) ClearChanges() *AuditLogUpdate {
	_u.mutation.ClearChanges()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdate) SetIPAddress(v string) *AuditLogUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableIPAddress(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdate) ClearIPAddress() *AuditLogUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditLogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := auditlog.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(auditlog.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(auditlog.FieldAggregateID, field.TypeString, value)
	}
	if _u.mutation.AggregateIDCleared() {
		_spec.ClearField(auditlog.FieldAggregateID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuditLogUpdateOne) SetUpdatedAt(v time.Time) *AuditLogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdateOne) SetTenantID(v uuid.UUID) *AuditLogUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTenantID(v *uuid.UUID) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuditLogUpdateOne) SetUserID(v string) *AuditLogUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableUserID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *AuditLogUpdateOne) ClearUserID() *AuditLogUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetAggregateType sets the "aggregate_type" field.
func (_u *AuditLogUpdateOne) SetAggregateType(v string) *AuditLogUpdateOne {
	_u.mutation.SetAggregateType(v)
	return _u
}

// SetNillableAggregateType sets the "aggregate_type" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAggregateType(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAggregateType(*v)
	}
	return _u
}

// SetAggregateID sets the "aggregate_id" field.
func (_u *AuditLogUpdateOne) SetAggregateID(v string) *AuditLogUpdateOne {
	_u.mutation.SetAggregateID(v)
	return _u
}

// SetNillableAggregateID sets the "aggregate_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAggregateID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAggregateID(*v)
	}
	return _u
}

// ClearAggregateID clears the value of the "aggregate_id" field.
func (_u *AuditLogUpdateOne) ClearAggregateID() *AuditLogUpdateOne {
	_u.mutation.ClearAggregateID()
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditLogUpdateOne) SetAction(v string) *AuditLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableAction(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetChanges sets the "changes" field.
func (_u *AuditLogUpdateOne) SetChanges(v map[string]interface{}) *AuditLogUpdateOne {
	_u.mutation.SetChanges(v)
	return _u
}

// ClearChanges clears the value of the "changes" field.
func (_u *AuditLogUpdateOne) ClearChanges() *AuditLogUpdateOne {
	_u.mutation.ClearChanges()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *AuditLogUpdateOne) SetIPAddress(v string) *AuditLogUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableIPAddress(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *AuditLogUpdateOne) ClearIPAddress() *AuditLogUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuditLogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := auditlog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.AggregateType(); ok {
		if err := auditlog.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "AuditLog.aggregate_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := auditlog.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditLog.action": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(auditlog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(auditlog.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(auditlog.FieldUserID, field.TypeString)
	}
	if value, ok := _u.mutation.AggregateType(); ok {
		_spec.SetField(auditlog.FieldAggregateType, field.TypeString, value)
	}
	if value, ok := _u.mutation.AggregateID(); ok {
		_spec.SetField(auditlog.FieldAggregateID, field.TypeString, value)
	}
	if _u.mutation.AggregateIDCleared() {
		_spec.ClearField(auditlog.FieldAggregateID, field.TypeString)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Changes(); ok {
		_spec.SetField(auditlog.FieldChanges, field.TypeJSON, value)
	}
	if _u.mutation.ChangesCleared() {
		_spec.ClearField(auditlog.FieldChanges, field.TypeJSON)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(auditlog.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(auditlog.FieldIPAddress, field.TypeString)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
