// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/authorizedvalue"
	"github.com/bengobox/library-service/internal/ent/predicate"
)

// AuthorizedValueDelete is the builder for deleting a AuthorizedValue entity.
type AuthorizedValueDelete struct {
	config
	hooks    []Hook
	mutation *AuthorizedValueMutation
}

// Where appends a list predicates to the AuthorizedValueDelete builder.
func (_d *AuthorizedValueDelete) Where(ps ...predicate.AuthorizedValue) *AuthorizedValueDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AuthorizedValueDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthorizedValueDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AuthorizedValueDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(authorizedvalue.Table, sqlgraph.NewFieldSpec(authorizedvalue.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AuthorizedValueDeleteOne is the builder for deleting a single AuthorizedValue entity.
type AuthorizedValueDeleteOne struct {
	_d *AuthorizedValueDelete
}

// Where appends a list predicates to the AuthorizedValueDelete builder.
func (_d *AuthorizedValueDeleteOne) Where(ps ...predicate.AuthorizedValue) *AuthorizedValueDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AuthorizedValueDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{authorizedvalue.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AuthorizedValueDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
