// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/bibrecord"
	"github.com/bengobox/library-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// BibRecordUpdate is the builder for updating BibRecord entities.
type BibRecordUpdate struct {
	config
	hooks    []Hook
	mutation *BibRecordMutation
}

// Where appends a list predicates to the BibRecordUpdate builder.
func (_u *BibRecordUpdate) Where(ps ...predicate.BibRecord) *BibRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BibRecordUpdate) SetUpdatedAt(v time.Time) *BibRecordUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *BibRecordUpdate) SetTenantID(v uuid.UUID) *BibRecordUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableTenantID(v *uuid.UUID) *BibRecordUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BibRecordUpdate) SetTitle(v string) *BibRecordUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableTitle(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *BibRecordUpdate) SetSubtitle(v string) *BibRecordUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableSubtitle(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *BibRecordUpdate) ClearSubtitle() *BibRecordUpdate {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetIsbn10 sets the "isbn10" field.
func (_u *BibRecordUpdate) SetIsbn10(v string) *BibRecordUpdate {
	_u.mutation.SetIsbn10(v)
	return _u
}

// SetNillableIsbn10 sets the "isbn10" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableIsbn10(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetIsbn10(*v)
	}
	return _u
}

// ClearIsbn10 clears the value of the "isbn10" field.
func (_u *BibRecordUpdate) ClearIsbn10() *BibRecordUpdate {
	_u.mutation.ClearIsbn10()
	return _u
}

// SetIsbn13 sets the "isbn13" field.
func (_u *BibRecordUpdate) SetIsbn13(v string) *BibRecordUpdate {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn13" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableIsbn13(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn13" field.
func (_u *BibRecordUpdate) ClearIsbn13() *BibRecordUpdate {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetIssn sets the "issn" field.
func (_u *BibRecordUpdate) SetIssn(v string) *BibRecordUpdate {
	_u.mutation.SetIssn(v)
	return _u
}

// SetNillableIssn sets the "issn" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableIssn(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetIssn(*v)
	}
	return _u
}

// ClearIssn clears the value of the "issn" field.
func (_u *BibRecordUpdate) ClearIssn() *BibRecordUpdate {
	_u.mutation.ClearIssn()
	return _u
}

// SetLccn sets the "lccn" field.
func (_u *BibRecordUpdate) SetLccn(v string) *BibRecordUpdate {
	_u.mutation.SetLccn(v)
	return _u
}

// SetNillableLccn sets the "lccn" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableLccn(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetLccn(*v)
	}
	return _u
}

// ClearLccn clears the value of the "lccn" field.
func (_u *BibRecordUpdate) ClearLccn() *BibRecordUpdate {
	_u.mutation.ClearLccn()
	return _u
}

// SetEdition sets the "edition" field.
func (_u *BibRecordUpdate) SetEdition(v string) *BibRecordUpdate {
	_u.mutation.SetEdition(v)
	return _u
}

// SetNillableEdition sets the "edition" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableEdition(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetEdition(*v)
	}
	return _u
}

// ClearEdition clears the value of the "edition" field.
func (_u *BibRecordUpdate) ClearEdition() *BibRecordUpdate {
	_u.mutation.ClearEdition()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BibRecordUpdate) SetLanguage(v string) *BibRecordUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableLanguage(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDdcClassification sets the "ddc_classification" field.
func (_u *BibRecordUpdate) SetDdcClassification(v string) *BibRecordUpdate {
	_u.mutation.SetDdcClassification(v)
	return _u
}

// SetNillableDdcClassification sets the "ddc_classification" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableDdcClassification(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetDdcClassification(*v)
	}
	return _u
}

// ClearDdcClassification clears the value of the "ddc_classification" field.
func (_u *BibRecordUpdate) ClearDdcClassification() *BibRecordUpdate {
	_u.mutation.ClearDdcClassification()
	return _u
}

// SetLcCallNumber sets the "lc_call_number" field.
func (_u *BibRecordUpdate) SetLcCallNumber(v string) *BibRecordUpdate {
	_u.mutation.SetLcCallNumber(v)
	return _u
}

// SetNillableLcCallNumber sets the "lc_call_number" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableLcCallNumber(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetLcCallNumber(*v)
	}
	return _u
}

// ClearLcCallNumber clears the value of the "lc_call_number" field.
func (_u *BibRecordUpdate) ClearLcCallNumber() *BibRecordUpdate {
	_u.mutation.ClearLcCallNumber()
	return _u
}

// SetPublicationYear sets the "publication_year" field.
func (_u *BibRecordUpdate) SetPublicationYear(v int) *BibRecordUpdate {
	_u.mutation.ResetPublicationYear()
	_u.mutation.SetPublicationYear(v)
	return _u
}

// SetNillablePublicationYear sets the "publication_year" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePublicationYear(v *int) *BibRecordUpdate {
	if v != nil {
		_u.SetPublicationYear(*v)
	}
	return _u
}

// AddPublicationYear adds value to the "publication_year" field.
func (_u *BibRecordUpdate) AddPublicationYear(v int) *BibRecordUpdate {
	_u.mutation.AddPublicationYear(v)
	return _u
}

// ClearPublicationYear clears the value of the "publication_year" field.
func (_u *BibRecordUpdate) ClearPublicationYear() *BibRecordUpdate {
	_u.mutation.ClearPublicationYear()
	return _u
}

// SetPublicationPlace sets the "publication_place" field.
func (_u *BibRecordUpdate) SetPublicationPlace(v string) *BibRecordUpdate {
	_u.mutation.SetPublicationPlace(v)
	return _u
}

// SetNillablePublicationPlace sets the "publication_place" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePublicationPlace(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetPublicationPlace(*v)
	}
	return _u
}

// ClearPublicationPlace clears the value of the "publication_place" field.
func (_u *BibRecordUpdate) ClearPublicationPlace() *BibRecordUpdate {
	_u.mutation.ClearPublicationPlace()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *BibRecordUpdate) SetPageCount(v int) *BibRecordUpdate {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePageCount(v *int) *BibRecordUpdate {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *BibRecordUpdate) AddPageCount(v int) *BibRecordUpdate {
	_u.mutation.AddPageCount(v)
	return _u
}

// ClearPageCount clears the value of the "page_count" field.
func (_u *BibRecordUpdate) ClearPageCount() *BibRecordUpdate {
	_u.mutation.ClearPageCount()
	return _u
}

// SetPublisherName sets the "publisher_name" field.
func (_u *BibRecordUpdate) SetPublisherName(v string) *BibRecordUpdate {
	_u.mutation.SetPublisherName(v)
	return _u
}

// SetNillablePublisherName sets the "publisher_name" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePublisherName(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetPublisherName(*v)
	}
	return _u
}

// ClearPublisherName clears the value of the "publisher_name" field.
func (_u *BibRecordUpdate) ClearPublisherName() *BibRecordUpdate {
	_u.mutation.ClearPublisherName()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *BibRecordUpdate) SetPublisherID(v uuid.UUID) *BibRecordUpdate {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePublisherID(v *uuid.UUID) *BibRecordUpdate {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// ClearPublisherID clears the value of the "publisher_id" field.
func (_u *BibRecordUpdate) ClearPublisherID() *BibRecordUpdate {
	_u.mutation.ClearPublisherID()
	return _u
}

// SetPrimarySubjectID sets the "primary_subject_id" field.
func (_u *BibRecordUpdate) SetPrimarySubjectID(v uuid.UUID) *BibRecordUpdate {
	_u.mutation.SetPrimarySubjectID(v)
	return _u
}

// SetNillablePrimarySubjectID sets the "primary_subject_id" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillablePrimarySubjectID(v *uuid.UUID) *BibRecordUpdate {
	if v != nil {
		_u.SetPrimarySubjectID(*v)
	}
	return _u
}

// ClearPrimarySubjectID clears the value of the "primary_subject_id" field.
func (_u *BibRecordUpdate) ClearPrimarySubjectID() *BibRecordUpdate {
	_u.mutation.ClearPrimarySubjectID()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *BibRecordUpdate) SetCollectionID(v uuid.UUID) *BibRecordUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableCollectionID(v *uuid.UUID) *BibRecordUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *BibRecordUpdate) ClearCollectionID() *BibRecordUpdate {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetFormat sets the "format" field.
func (_u *BibRecordUpdate) SetFormat(v bibrecord.Format) *BibRecordUpdate {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableFormat(v *bibrecord.Format) *BibRecordUpdate {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetRecordStatus sets the "record_status" field.
func (_u *BibRecordUpdate) SetRecordStatus(v bibrecord.RecordStatus) *BibRecordUpdate {
	_u.mutation.SetRecordStatus(v)
	return _u
}

// SetNillableRecordStatus sets the "record_status" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableRecordStatus(v *bibrecord.RecordStatus) *BibRecordUpdate {
	if v != nil {
		_u.SetRecordStatus(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *BibRecordUpdate) SetSummary(v string) *BibRecordUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableSummary(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *BibRecordUpdate) ClearSummary() *BibRecordUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *BibRecordUpdate) SetCoverImageURL(v string) *BibRecordUpdate {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableCoverImageURL(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *BibRecordUpdate) ClearCoverImageURL() *BibRecordUpdate {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetCoverBackImageURL sets the "cover_back_image_url" field.
func (_u *BibRecordUpdate) SetCoverBackImageURL(v string) *BibRecordUpdate {
	_u.mutation.SetCoverBackImageURL(v)
	return _u
}

// SetNillableCoverBackImageURL sets the "cover_back_image_url" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableCoverBackImageURL(v *string) *BibRecordUpdate {
	if v != nil {
		_u.SetCoverBackImageURL(*v)
	}
	return _u
}

// ClearCoverBackImageURL clears the value of the "cover_back_image_url" field.
func (_u *BibRecordUpdate) ClearCoverBackImageURL() *BibRecordUpdate {
	_u.mutation.ClearCoverBackImageURL()
	return _u
}

// SetAuthors sets the "authors" field.
func (_u *BibRecordUpdate) SetAuthors(v []string) *BibRecordUpdate {
	_u.mutation.SetAuthors(v)
	return _u
}

// AppendAuthors appends value to the "authors" field.
func (_u *BibRecordUpdate) AppendAuthors(v []string) *BibRecordUpdate {
	_u.mutation.AppendAuthors(v)
	return _u
}

// ClearAuthors clears the value of the "authors" field.
func (_u *BibRecordUpdate) ClearAuthors() *BibRecordUpdate {
	_u.mutation.ClearAuthors()
	return _u
}

// SetSubjects sets the "subjects" field.
func (_u *BibRecordUpdate) SetSubjects(v []string) *BibRecordUpdate {
	_u.mutation.SetSubjects(v)
	return _u
}

// AppendSubjects appends value to the "subjects" field.
func (_u *BibRecordUpdate) AppendSubjects(v []string) *BibRecordUpdate {
	_u.mutation.AppendSubjects(v)
	return _u
}

// ClearSubjects clears the value of the "subjects" field.
func (_u *BibRecordUpdate) ClearSubjects() *BibRecordUpdate {
	_u.mutation.ClearSubjects()
	return _u
}

// SetOtherIsbns sets the "other_isbns" field.
func (_u *BibRecordUpdate) SetOtherIsbns(v []string) *BibRecordUpdate {
	_u.mutation.SetOtherIsbns(v)
	return _u
}

// AppendOtherIsbns appends value to the "other_isbns" field.
func (_u *BibRecordUpdate) AppendOtherIsbns(v []string) *BibRecordUpdate {
	_u.mutation.AppendOtherIsbns(v)
	return _u
}

// ClearOtherIsbns clears the value of the "other_isbns" field.
func (_u *BibRecordUpdate) ClearOtherIsbns() *BibRecordUpdate {
	_u.mutation.ClearOtherIsbns()
	return _u
}

// SetDublinCore sets the "dublin_core" field.
func (_u *BibRecordUpdate) SetDublinCore(v map[string]interface{}) *BibRecordUpdate {
	_u.mutation.SetDublinCore(v)
	return _u
}

// ClearDublinCore clears the value of the "dublin_core" field.
func (_u *BibRecordUpdate) ClearDublinCore() *BibRecordUpdate {
	_u.mutation.ClearDublinCore()
	return _u
}

// SetMarc sets the "marc" field.
func (_u *BibRecordUpdate) SetMarc(v map[string]interface{}) *BibRecordUpdate {
	_u.mutation.SetMarc(v)
	return _u
}

// ClearMarc clears the value of the "marc" field.
func (_u *BibRecordUpdate) ClearMarc() *BibRecordUpdate {
	_u.mutation.ClearMarc()
	return _u
}

// SetDefaultLoanPolicyID sets the "default_loan_policy_id" field.
func (_u *BibRecordUpdate) SetDefaultLoanPolicyID(v uuid.UUID) *BibRecordUpdate {
	_u.mutation.SetDefaultLoanPolicyID(v)
	return _u
}

// SetNillableDefaultLoanPolicyID sets the "default_loan_policy_id" field if the given value is not nil.
func (_u *BibRecordUpdate) SetNillableDefaultLoanPolicyID(v *uuid.UUID) *BibRecordUpdate {
	if v != nil {
		_u.SetDefaultLoanPolicyID(*v)
	}
	return _u
}

// ClearDefaultLoanPolicyID clears the value of the "default_loan_policy_id" field.
func (_u *BibRecordUpdate) ClearDefaultLoanPolicyID() *BibRecordUpdate {
	_u.mutation.ClearDefaultLoanPolicyID()
	return _u
}

// Mutation returns the BibRecordMutation object of the builder.
func (_u *BibRecordUpdate) Mutation() *BibRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BibRecordUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BibRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BibRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BibRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BibRecordUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bibrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BibRecordUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := bibrecord.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BibRecord.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := bibrecord.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "BibRecord.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecordStatus(); ok {
		if err := bibrecord.RecordStatusValidator(v); err != nil {
			return &ValidationError{Name: "record_status", err: fmt.Errorf(`ent: validator failed for field "BibRecord.record_status": %w`, err)}
		}
	}
	return nil
}

func (_u *BibRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bibrecord.Table, bibrecord.Columns, sqlgraph.NewFieldSpec(bibrecord.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bibrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(bibrecord.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bibrecord.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(bibrecord.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(bibrecord.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn10(); ok {
		_spec.SetField(bibrecord.FieldIsbn10, field.TypeString, value)
	}
	if _u.mutation.Isbn10Cleared() {
		_spec.ClearField(bibrecord.FieldIsbn10, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(bibrecord.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(bibrecord.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Issn(); ok {
		_spec.SetField(bibrecord.FieldIssn, field.TypeString, value)
	}
	if _u.mutation.IssnCleared() {
		_spec.ClearField(bibrecord.FieldIssn, field.TypeString)
	}
	if value, ok := _u.mutation.Lccn(); ok {
		_spec.SetField(bibrecord.FieldLccn, field.TypeString, value)
	}
	if _u.mutation.LccnCleared() {
		_spec.ClearField(bibrecord.FieldLccn, field.TypeString)
	}
	if value, ok := _u.mutation.Edition(); ok {
		_spec.SetField(bibrecord.FieldEdition, field.TypeString, value)
	}
	if _u.mutation.EditionCleared() {
		_spec.ClearField(bibrecord.FieldEdition, field.TypeString)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(bibrecord.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DdcClassification(); ok {
		_spec.SetField(bibrecord.FieldDdcClassification, field.TypeString, value)
	}
	if _u.mutation.DdcClassificationCleared() {
		_spec.ClearField(bibrecord.FieldDdcClassification, field.TypeString)
	}
	if value, ok := _u.mutation.LcCallNumber(); ok {
		_spec.SetField(bibrecord.FieldLcCallNumber, field.TypeString, value)
	}
	if _u.mutation.LcCallNumberCleared() {
		_spec.ClearField(bibrecord.FieldLcCallNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PublicationYear(); ok {
		_spec.SetField(bibrecord.FieldPublicationYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicationYear(); ok {
		_spec.AddField(bibrecord.FieldPublicationYear, field.TypeInt, value)
	}
	if _u.mutation.PublicationYearCleared() {
		_spec.ClearField(bibrecord.FieldPublicationYear, field.TypeInt)
	}
	if value, ok := _u.mutation.PublicationPlace(); ok {
		_spec.SetField(bibrecord.FieldPublicationPlace, field.TypeString, value)
	}
	if _u.mutation.PublicationPlaceCleared() {
		_spec.ClearField(bibrecord.FieldPublicationPlace, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(bibrecord.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(bibrecord.FieldPageCount, field.TypeInt, value)
	}
	if _u.mutation.PageCountCleared() {
		_spec.ClearField(bibrecord.FieldPageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.PublisherName(); ok {
		_spec.SetField(bibrecord.FieldPublisherName, field.TypeString, value)
	}
	if _u.mutation.PublisherNameCleared() {
		_spec.ClearField(bibrecord.FieldPublisherName, field.TypeString)
	}
	if value, ok := _u.mutation.PublisherID(); ok {
		_spec.SetField(bibrecord.FieldPublisherID, field.TypeUUID, value)
	}
	if _u.mutation.PublisherIDCleared() {
		_spec.ClearField(bibrecord.FieldPublisherID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PrimarySubjectID(); ok {
		_spec.SetField(bibrecord.FieldPrimarySubjectID, field.TypeUUID, value)
	}
	if _u.mutation.PrimarySubjectIDCleared() {
		_spec.ClearField(bibrecord.FieldPrimarySubjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CollectionID(); ok {
		_spec.SetField(bibrecord.FieldCollectionID, field.TypeUUID, value)
	}
	if _u.mutation.CollectionIDCleared() {
		_spec.ClearField(bibrecord.FieldCollectionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(bibrecord.FieldFormat, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecordStatus(); ok {
		_spec.SetField(bibrecord.FieldRecordStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(bibrecord.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(bibrecord.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(bibrecord.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(bibrecord.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverBackImageURL(); ok {
		_spec.SetField(bibrecord.FieldCoverBackImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverBackImageURLCleared() {
		_spec.ClearField(bibrecord.FieldCoverBackImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Authors(); ok {
		_spec.SetField(bibrecord.FieldAuthors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldAuthors, value)
		})
	}
	if _u.mutation.AuthorsCleared() {
		_spec.ClearField(bibrecord.FieldAuthors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Subjects(); ok {
		_spec.SetField(bibrecord.FieldSubjects, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSubjects(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldSubjects, value)
		})
	}
	if _u.mutation.SubjectsCleared() {
		_spec.ClearField(bibrecord.FieldSubjects, field.TypeJSON)
	}
	if value, ok := _u.mutation.OtherIsbns(); ok {
		_spec.SetField(bibrecord.FieldOtherIsbns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOtherIsbns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldOtherIsbns, value)
		})
	}
	if _u.mutation.OtherIsbnsCleared() {
		_spec.ClearField(bibrecord.FieldOtherIsbns, field.TypeJSON)
	}
	if value, ok := _u.mutation.DublinCore(); ok {
		_spec.SetField(bibrecord.FieldDublinCore, field.TypeJSON, value)
	}
	if _u.mutation.DublinCoreCleared() {
		_spec.ClearField(bibrecord.FieldDublinCore, field.TypeJSON)
	}
	if value, ok := _u.mutation.Marc(); ok {
		_spec.SetField(bibrecord.FieldMarc, field.TypeJSON, value)
	}
	if _u.mutation.MarcCleared() {
		_spec.ClearField(bibrecord.FieldMarc, field.TypeJSON)
	}
	if value, ok := _u.mutation.DefaultLoanPolicyID(); ok {
		_spec.SetField(bibrecord.FieldDefaultLoanPolicyID, field.TypeUUID, value)
	}
	if _u.mutation.DefaultLoanPolicyIDCleared() {
		_spec.ClearField(bibrecord.FieldDefaultLoanPolicyID, field.TypeUUID)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bibrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BibRecordUpdateOne is the builder for updating a single BibRecord entity.
type BibRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BibRecordMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BibRecordUpdateOne) SetUpdatedAt(v time.Time) *BibRecordUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *BibRecordUpdateOne) SetTenantID(v uuid.UUID) *BibRecordUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableTenantID(v *uuid.UUID) *BibRecordUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *BibRecordUpdateOne) SetTitle(v string) *BibRecordUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableTitle(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *BibRecordUpdateOne) SetSubtitle(v string) *BibRecordUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableSubtitle(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// ClearSubtitle clears the value of the "subtitle" field.
func (_u *BibRecordUpdateOne) ClearSubtitle() *BibRecordUpdateOne {
	_u.mutation.ClearSubtitle()
	return _u
}

// SetIsbn10 sets the "isbn10" field.
func (_u *BibRecordUpdateOne) SetIsbn10(v string) *BibRecordUpdateOne {
	_u.mutation.SetIsbn10(v)
	return _u
}

// SetNillableIsbn10 sets the "isbn10" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableIsbn10(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetIsbn10(*v)
	}
	return _u
}

// ClearIsbn10 clears the value of the "isbn10" field.
func (_u *BibRecordUpdateOne) ClearIsbn10() *BibRecordUpdateOne {
	_u.mutation.ClearIsbn10()
	return _u
}

// SetIsbn13 sets the "isbn13" field.
func (_u *BibRecordUpdateOne) SetIsbn13(v string) *BibRecordUpdateOne {
	_u.mutation.SetIsbn13(v)
	return _u
}

// SetNillableIsbn13 sets the "isbn13" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableIsbn13(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetIsbn13(*v)
	}
	return _u
}

// ClearIsbn13 clears the value of the "isbn13" field.
func (_u *BibRecordUpdateOne) ClearIsbn13() *BibRecordUpdateOne {
	_u.mutation.ClearIsbn13()
	return _u
}

// SetIssn sets the "issn" field.
func (_u *BibRecordUpdateOne) SetIssn(v string) *BibRecordUpdateOne {
	_u.mutation.SetIssn(v)
	return _u
}

// SetNillableIssn sets the "issn" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableIssn(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetIssn(*v)
	}
	return _u
}

// ClearIssn clears the value of the "issn" field.
func (_u *BibRecordUpdateOne) ClearIssn() *BibRecordUpdateOne {
	_u.mutation.ClearIssn()
	return _u
}

// SetLccn sets the "lccn" field.
func (_u *BibRecordUpdateOne) SetLccn(v string) *BibRecordUpdateOne {
	_u.mutation.SetLccn(v)
	return _u
}

// SetNillableLccn sets the "lccn" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableLccn(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetLccn(*v)
	}
	return _u
}

// ClearLccn clears the value of the "lccn" field.
func (_u *BibRecordUpdateOne) ClearLccn() *BibRecordUpdateOne {
	_u.mutation.ClearLccn()
	return _u
}

// SetEdition sets the "edition" field.
func (_u *BibRecordUpdateOne) SetEdition(v string) *BibRecordUpdateOne {
	_u.mutation.SetEdition(v)
	return _u
}

// SetNillableEdition sets the "edition" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableEdition(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetEdition(*v)
	}
	return _u
}

// ClearEdition clears the value of the "edition" field.
func (_u *BibRecordUpdateOne) ClearEdition() *BibRecordUpdateOne {
	_u.mutation.ClearEdition()
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BibRecordUpdateOne) SetLanguage(v string) *BibRecordUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableLanguage(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDdcClassification sets the "ddc_classification" field.
func (_u *BibRecordUpdateOne) SetDdcClassification(v string) *BibRecordUpdateOne {
	_u.mutation.SetDdcClassification(v)
	return _u
}

// SetNillableDdcClassification sets the "ddc_classification" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableDdcClassification(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetDdcClassification(*v)
	}
	return _u
}

// ClearDdcClassification clears the value of the "ddc_classification" field.
func (_u *BibRecordUpdateOne) ClearDdcClassification() *BibRecordUpdateOne {
	_u.mutation.ClearDdcClassification()
	return _u
}

// SetLcCallNumber sets the "lc_call_number" field.
func (_u *BibRecordUpdateOne) SetLcCallNumber(v string) *BibRecordUpdateOne {
	_u.mutation.SetLcCallNumber(v)
	return _u
}

// SetNillableLcCallNumber sets the "lc_call_number" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableLcCallNumber(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetLcCallNumber(*v)
	}
	return _u
}

// ClearLcCallNumber clears the value of the "lc_call_number" field.
func (_u *BibRecordUpdateOne) ClearLcCallNumber() *BibRecordUpdateOne {
	_u.mutation.ClearLcCallNumber()
	return _u
}

// SetPublicationYear sets the "publication_year" field.
func (_u *BibRecordUpdateOne) SetPublicationYear(v int) *BibRecordUpdateOne {
	_u.mutation.ResetPublicationYear()
	_u.mutation.SetPublicationYear(v)
	return _u
}

// SetNillablePublicationYear sets the "publication_year" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePublicationYear(v *int) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPublicationYear(*v)
	}
	return _u
}

// AddPublicationYear adds value to the "publication_year" field.
func (_u *BibRecordUpdateOne) AddPublicationYear(v int) *BibRecordUpdateOne {
	_u.mutation.AddPublicationYear(v)
	return _u
}

// ClearPublicationYear clears the value of the "publication_year" field.
func (_u *BibRecordUpdateOne) ClearPublicationYear() *BibRecordUpdateOne {
	_u.mutation.ClearPublicationYear()
	return _u
}

// SetPublicationPlace sets the "publication_place" field.
func (_u *BibRecordUpdateOne) SetPublicationPlace(v string) *BibRecordUpdateOne {
	_u.mutation.SetPublicationPlace(v)
	return _u
}

// SetNillablePublicationPlace sets the "publication_place" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePublicationPlace(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPublicationPlace(*v)
	}
	return _u
}

// ClearPublicationPlace clears the value of the "publication_place" field.
func (_u *BibRecordUpdateOne) ClearPublicationPlace() *BibRecordUpdateOne {
	_u.mutation.ClearPublicationPlace()
	return _u
}

// SetPageCount sets the "page_count" field.
func (_u *BibRecordUpdateOne) SetPageCount(v int) *BibRecordUpdateOne {
	_u.mutation.ResetPageCount()
	_u.mutation.SetPageCount(v)
	return _u
}

// SetNillablePageCount sets the "page_count" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePageCount(v *int) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPageCount(*v)
	}
	return _u
}

// AddPageCount adds value to the "page_count" field.
func (_u *BibRecordUpdateOne) AddPageCount(v int) *BibRecordUpdateOne {
	_u.mutation.AddPageCount(v)
	return _u
}

// ClearPageCount clears the value of the "page_count" field.
func (_u *BibRecordUpdateOne) ClearPageCount() *BibRecordUpdateOne {
	_u.mutation.ClearPageCount()
	return _u
}

// SetPublisherName sets the "publisher_name" field.
func (_u *BibRecordUpdateOne) SetPublisherName(v string) *BibRecordUpdateOne {
	_u.mutation.SetPublisherName(v)
	return _u
}

// SetNillablePublisherName sets the "publisher_name" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePublisherName(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPublisherName(*v)
	}
	return _u
}

// ClearPublisherName clears the value of the "publisher_name" field.
func (_u *BibRecordUpdateOne) ClearPublisherName() *BibRecordUpdateOne {
	_u.mutation.ClearPublisherName()
	return _u
}

// SetPublisherID sets the "publisher_id" field.
func (_u *BibRecordUpdateOne) SetPublisherID(v uuid.UUID) *BibRecordUpdateOne {
	_u.mutation.SetPublisherID(v)
	return _u
}

// SetNillablePublisherID sets the "publisher_id" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePublisherID(v *uuid.UUID) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPublisherID(*v)
	}
	return _u
}

// ClearPublisherID clears the value of the "publisher_id" field.
func (_u *BibRecordUpdateOne) ClearPublisherID() *BibRecordUpdateOne {
	_u.mutation.ClearPublisherID()
	return _u
}

// SetPrimarySubjectID sets the "primary_subject_id" field.
func (_u *BibRecordUpdateOne) SetPrimarySubjectID(v uuid.UUID) *BibRecordUpdateOne {
	_u.mutation.SetPrimarySubjectID(v)
	return _u
}

// SetNillablePrimarySubjectID sets the "primary_subject_id" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillablePrimarySubjectID(v *uuid.UUID) *BibRecordUpdateOne {
	if v != nil {
		_u.SetPrimarySubjectID(*v)
	}
	return _u
}

// ClearPrimarySubjectID clears the value of the "primary_subject_id" field.
func (_u *BibRecordUpdateOne) ClearPrimarySubjectID() *BibRecordUpdateOne {
	_u.mutation.ClearPrimarySubjectID()
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *BibRecordUpdateOne) SetCollectionID(v uuid.UUID) *BibRecordUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableCollectionID(v *uuid.UUID) *BibRecordUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *BibRecordUpdateOne) ClearCollectionID() *BibRecordUpdateOne {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetFormat sets the "format" field.
func (_u *BibRecordUpdateOne) SetFormat(v bibrecord.Format) *BibRecordUpdateOne {
	_u.mutation.SetFormat(v)
	return _u
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableFormat(v *bibrecord.Format) *BibRecordUpdateOne {
	if v != nil {
		_u.SetFormat(*v)
	}
	return _u
}

// SetRecordStatus sets the "record_status" field.
func (_u *BibRecordUpdateOne) SetRecordStatus(v bibrecord.RecordStatus) *BibRecordUpdateOne {
	_u.mutation.SetRecordStatus(v)
	return _u
}

// SetNillableRecordStatus sets the "record_status" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableRecordStatus(v *bibrecord.RecordStatus) *BibRecordUpdateOne {
	if v != nil {
		_u.SetRecordStatus(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *BibRecordUpdateOne) SetSummary(v string) *BibRecordUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableSummary(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *BibRecordUpdateOne) ClearSummary() *BibRecordUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetCoverImageURL sets the "cover_image_url" field.
func (_u *BibRecordUpdateOne) SetCoverImageURL(v string) *BibRecordUpdateOne {
	_u.mutation.SetCoverImageURL(v)
	return _u
}

// SetNillableCoverImageURL sets the "cover_image_url" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableCoverImageURL(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetCoverImageURL(*v)
	}
	return _u
}

// ClearCoverImageURL clears the value of the "cover_image_url" field.
func (_u *BibRecordUpdateOne) ClearCoverImageURL() *BibRecordUpdateOne {
	_u.mutation.ClearCoverImageURL()
	return _u
}

// SetCoverBackImageURL sets the "cover_back_image_url" field.
func (_u *BibRecordUpdateOne) SetCoverBackImageURL(v string) *BibRecordUpdateOne {
	_u.mutation.SetCoverBackImageURL(v)
	return _u
}

// SetNillableCoverBackImageURL sets the "cover_back_image_url" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableCoverBackImageURL(v *string) *BibRecordUpdateOne {
	if v != nil {
		_u.SetCoverBackImageURL(*v)
	}
	return _u
}

// ClearCoverBackImageURL clears the value of the "cover_back_image_url" field.
func (_u *BibRecordUpdateOne) ClearCoverBackImageURL() *BibRecordUpdateOne {
	_u.mutation.ClearCoverBackImageURL()
	return _u
}

// SetAuthors sets the "authors" field.
func (_u *BibRecordUpdateOne) SetAuthors(v []string) *BibRecordUpdateOne {
	_u.mutation.SetAuthors(v)
	return _u
}

// AppendAuthors appends value to the "authors" field.
func (_u *BibRecordUpdateOne) AppendAuthors(v []string) *BibRecordUpdateOne {
	_u.mutation.AppendAuthors(v)
	return _u
}

// ClearAuthors clears the value of the "authors" field.
func (_u *BibRecordUpdateOne) ClearAuthors() *BibRecordUpdateOne {
	_u.mutation.ClearAuthors()
	return _u
}

// SetSubjects sets the "subjects" field.
func (_u *BibRecordUpdateOne) SetSubjects(v []string) *BibRecordUpdateOne {
	_u.mutation.SetSubjects(v)
	return _u
}

// AppendSubjects appends value to the "subjects" field.
func (_u *BibRecordUpdateOne) AppendSubjects(v []string) *BibRecordUpdateOne {
	_u.mutation.AppendSubjects(v)
	return _u
}

// ClearSubjects clears the value of the "subjects" field.
func (_u *BibRecordUpdateOne) ClearSubjects() *BibRecordUpdateOne {
	_u.mutation.ClearSubjects()
	return _u
}

// SetOtherIsbns sets the "other_isbns" field.
func (_u *BibRecordUpdateOne) SetOtherIsbns(v []string) *BibRecordUpdateOne {
	_u.mutation.SetOtherIsbns(v)
	return _u
}

// AppendOtherIsbns appends value to the "other_isbns" field.
func (_u *BibRecordUpdateOne) AppendOtherIsbns(v []string) *BibRecordUpdateOne {
	_u.mutation.AppendOtherIsbns(v)
	return _u
}

// ClearOtherIsbns clears the value of the "other_isbns" field.
func (_u *BibRecordUpdateOne) ClearOtherIsbns() *BibRecordUpdateOne {
	_u.mutation.ClearOtherIsbns()
	return _u
}

// SetDublinCore sets the "dublin_core" field.
func (_u *BibRecordUpdateOne) SetDublinCore(v map[string]interface{}) *BibRecordUpdateOne {
	_u.mutation.SetDublinCore(v)
	return _u
}

// ClearDublinCore clears the value of the "dublin_core" field.
func (_u *BibRecordUpdateOne) ClearDublinCore() *BibRecordUpdateOne {
	_u.mutation.ClearDublinCore()
	return _u
}

// SetMarc sets the "marc" field.
func (_u *BibRecordUpdateOne) SetMarc(v map[string]interface{}) *BibRecordUpdateOne {
	_u.mutation.SetMarc(v)
	return _u
}

// ClearMarc clears the value of the "marc" field.
func (_u *BibRecordUpdateOne) ClearMarc() *BibRecordUpdateOne {
	_u.mutation.ClearMarc()
	return _u
}

// SetDefaultLoanPolicyID sets the "default_loan_policy_id" field.
func (_u *BibRecordUpdateOne) SetDefaultLoanPolicyID(v uuid.UUID) *BibRecordUpdateOne {
	_u.mutation.SetDefaultLoanPolicyID(v)
	return _u
}

// SetNillableDefaultLoanPolicyID sets the "default_loan_policy_id" field if the given value is not nil.
func (_u *BibRecordUpdateOne) SetNillableDefaultLoanPolicyID(v *uuid.UUID) *BibRecordUpdateOne {
	if v != nil {
		_u.SetDefaultLoanPolicyID(*v)
	}
	return _u
}

// ClearDefaultLoanPolicyID clears the value of the "default_loan_policy_id" field.
func (_u *BibRecordUpdateOne) ClearDefaultLoanPolicyID() *BibRecordUpdateOne {
	_u.mutation.ClearDefaultLoanPolicyID()
	return _u
}

// Mutation returns the BibRecordMutation object of the builder.
func (_u *BibRecordUpdateOne) Mutation() *BibRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the BibRecordUpdate builder.
func (_u *BibRecordUpdateOne) Where(ps ...predicate.BibRecord) *BibRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BibRecordUpdateOne) Select(field string, fields ...string) *BibRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BibRecord entity.
func (_u *BibRecordUpdateOne) Save(ctx context.Context) (*BibRecord, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BibRecordUpdateOne) SaveX(ctx context.Context) *BibRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BibRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BibRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BibRecordUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := bibrecord.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BibRecordUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := bibrecord.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "BibRecord.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Format(); ok {
		if err := bibrecord.FormatValidator(v); err != nil {
			return &ValidationError{Name: "format", err: fmt.Errorf(`ent: validator failed for field "BibRecord.format": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RecordStatus(); ok {
		if err := bibrecord.RecordStatusValidator(v); err != nil {
			return &ValidationError{Name: "record_status", err: fmt.Errorf(`ent: validator failed for field "BibRecord.record_status": %w`, err)}
		}
	}
	return nil
}

func (_u *BibRecordUpdateOne) sqlSave(ctx context.Context) (_node *BibRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(bibrecord.Table, bibrecord.Columns, sqlgraph.NewFieldSpec(bibrecord.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BibRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, bibrecord.FieldID)
		for _, f := range fields {
			if !bibrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != bibrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(bibrecord.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(bibrecord.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(bibrecord.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(bibrecord.FieldSubtitle, field.TypeString, value)
	}
	if _u.mutation.SubtitleCleared() {
		_spec.ClearField(bibrecord.FieldSubtitle, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn10(); ok {
		_spec.SetField(bibrecord.FieldIsbn10, field.TypeString, value)
	}
	if _u.mutation.Isbn10Cleared() {
		_spec.ClearField(bibrecord.FieldIsbn10, field.TypeString)
	}
	if value, ok := _u.mutation.Isbn13(); ok {
		_spec.SetField(bibrecord.FieldIsbn13, field.TypeString, value)
	}
	if _u.mutation.Isbn13Cleared() {
		_spec.ClearField(bibrecord.FieldIsbn13, field.TypeString)
	}
	if value, ok := _u.mutation.Issn(); ok {
		_spec.SetField(bibrecord.FieldIssn, field.TypeString, value)
	}
	if _u.mutation.IssnCleared() {
		_spec.ClearField(bibrecord.FieldIssn, field.TypeString)
	}
	if value, ok := _u.mutation.Lccn(); ok {
		_spec.SetField(bibrecord.FieldLccn, field.TypeString, value)
	}
	if _u.mutation.LccnCleared() {
		_spec.ClearField(bibrecord.FieldLccn, field.TypeString)
	}
	if value, ok := _u.mutation.Edition(); ok {
		_spec.SetField(bibrecord.FieldEdition, field.TypeString, value)
	}
	if _u.mutation.EditionCleared() {
		_spec.ClearField(bibrecord.FieldEdition, field.TypeString)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(bibrecord.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.DdcClassification(); ok {
		_spec.SetField(bibrecord.FieldDdcClassification, field.TypeString, value)
	}
	if _u.mutation.DdcClassificationCleared() {
		_spec.ClearField(bibrecord.FieldDdcClassification, field.TypeString)
	}
	if value, ok := _u.mutation.LcCallNumber(); ok {
		_spec.SetField(bibrecord.FieldLcCallNumber, field.TypeString, value)
	}
	if _u.mutation.LcCallNumberCleared() {
		_spec.ClearField(bibrecord.FieldLcCallNumber, field.TypeString)
	}
	if value, ok := _u.mutation.PublicationYear(); ok {
		_spec.SetField(bibrecord.FieldPublicationYear, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublicationYear(); ok {
		_spec.AddField(bibrecord.FieldPublicationYear, field.TypeInt, value)
	}
	if _u.mutation.PublicationYearCleared() {
		_spec.ClearField(bibrecord.FieldPublicationYear, field.TypeInt)
	}
	if value, ok := _u.mutation.PublicationPlace(); ok {
		_spec.SetField(bibrecord.FieldPublicationPlace, field.TypeString, value)
	}
	if _u.mutation.PublicationPlaceCleared() {
		_spec.ClearField(bibrecord.FieldPublicationPlace, field.TypeString)
	}
	if value, ok := _u.mutation.PageCount(); ok {
		_spec.SetField(bibrecord.FieldPageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPageCount(); ok {
		_spec.AddField(bibrecord.FieldPageCount, field.TypeInt, value)
	}
	if _u.mutation.PageCountCleared() {
		_spec.ClearField(bibrecord.FieldPageCount, field.TypeInt)
	}
	if value, ok := _u.mutation.PublisherName(); ok {
		_spec.SetField(bibrecord.FieldPublisherName, field.TypeString, value)
	}
	if _u.mutation.PublisherNameCleared() {
		_spec.ClearField(bibrecord.FieldPublisherName, field.TypeString)
	}
	if value, ok := _u.mutation.PublisherID(); ok {
		_spec.SetField(bibrecord.FieldPublisherID, field.TypeUUID, value)
	}
	if _u.mutation.PublisherIDCleared() {
		_spec.ClearField(bibrecord.FieldPublisherID, field.TypeUUID)
	}
	if value, ok := _u.mutation.PrimarySubjectID(); ok {
		_spec.SetField(bibrecord.FieldPrimarySubjectID, field.TypeUUID, value)
	}
	if _u.mutation.PrimarySubjectIDCleared() {
		_spec.ClearField(bibrecord.FieldPrimarySubjectID, field.TypeUUID)
	}
	if value, ok := _u.mutation.CollectionID(); ok {
		_spec.SetField(bibrecord.FieldCollectionID, field.TypeUUID, value)
	}
	if _u.mutation.CollectionIDCleared() {
		_spec.ClearField(bibrecord.FieldCollectionID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Format(); ok {
		_spec.SetField(bibrecord.FieldFormat, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RecordStatus(); ok {
		_spec.SetField(bibrecord.FieldRecordStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(bibrecord.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(bibrecord.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.CoverImageURL(); ok {
		_spec.SetField(bibrecord.FieldCoverImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverImageURLCleared() {
		_spec.ClearField(bibrecord.FieldCoverImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CoverBackImageURL(); ok {
		_spec.SetField(bibrecord.FieldCoverBackImageURL, field.TypeString, value)
	}
	if _u.mutation.CoverBackImageURLCleared() {
		_spec.ClearField(bibrecord.FieldCoverBackImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.Authors(); ok {
		_spec.SetField(bibrecord.FieldAuthors, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedAuthors(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldAuthors, value)
		})
	}
	if _u.mutation.AuthorsCleared() {
		_spec.ClearField(bibrecord.FieldAuthors, field.TypeJSON)
	}
	if value, ok := _u.mutation.Subjects(); ok {
		_spec.SetField(bibrecord.FieldSubjects, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSubjects(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldSubjects, value)
		})
	}
	if _u.mutation.SubjectsCleared() {
		_spec.ClearField(bibrecord.FieldSubjects, field.TypeJSON)
	}
	if value, ok := _u.mutation.OtherIsbns(); ok {
		_spec.SetField(bibrecord.FieldOtherIsbns, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedOtherIsbns(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, bibrecord.FieldOtherIsbns, value)
		})
	}
	if _u.mutation.OtherIsbnsCleared() {
		_spec.ClearField(bibrecord.FieldOtherIsbns, field.TypeJSON)
	}
	if value, ok := _u.mutation.DublinCore(); ok {
		_spec.SetField(bibrecord.FieldDublinCore, field.TypeJSON, value)
	}
	if _u.mutation.DublinCoreCleared() {
		_spec.ClearField(bibrecord.FieldDublinCore, field.TypeJSON)
	}
	if value, ok := _u.mutation.Marc(); ok {
		_spec.SetField(bibrecord.FieldMarc, field.TypeJSON, value)
	}
	if _u.mutation.MarcCleared() {
		_spec.ClearField(bibrecord.FieldMarc, field.TypeJSON)
	}
	if value, ok := _u.mutation.DefaultLoanPolicyID(); ok {
		_spec.SetField(bibrecord.FieldDefaultLoanPolicyID, field.TypeUUID, value)
	}
	if _u.mutation.DefaultLoanPolicyIDCleared() {
		_spec.ClearField(bibrecord.FieldDefaultLoanPolicyID, field.TypeUUID)
	}
	_node = &BibRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{bibrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
