// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/library-service/internal/ent/bookcopy"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// BookCopy is the model entity for the BookCopy schema.
type BookCopy struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// BibRecordID holds the value of the "bib_record_id" field.
	BibRecordID uuid.UUID `json:"bib_record_id,omitempty"`
	// BranchID holds the value of the "branch_id" field.
	BranchID uuid.UUID `json:"branch_id,omitempty"`
	// Unique per tenant; scanned at circulation
	Barcode string `json:"barcode,omitempty"`
	// AccessionNo holds the value of the "accession_no" field.
	AccessionNo string `json:"accession_no,omitempty"`
	// CallNumber holds the value of the "call_number" field.
	CallNumber string `json:"call_number,omitempty"`
	// ShelfLocation holds the value of the "shelf_location" field.
	ShelfLocation string `json:"shelf_location,omitempty"`
	// Status holds the value of the "status" field.
	Status bookcopy.Status `json:"status,omitempty"`
	// Condition holds the value of the "condition" field.
	Condition string `json:"condition,omitempty"`
	// Reference/in-house reading only — never leaves the building
	IsReferenceOnly bool `json:"is_reference_only,omitempty"`
	// AcquisitionCost holds the value of the "acquisition_cost" field.
	AcquisitionCost *decimal.Decimal `json:"acquisition_cost,omitempty"`
	// AcquisitionDate holds the value of the "acquisition_date" field.
	AcquisitionDate *time.Time `json:"acquisition_date,omitempty"`
	// Free-text notes about this physical copy
	Notes string `json:"notes,omitempty"`
	// Per-copy policy override
	LoanPolicyID *uuid.UUID `json:"loan_policy_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BookCopy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case bookcopy.FieldAcquisitionCost:
			values[i] = &sql.NullScanner{S: new(decimal.Decimal)}
		case bookcopy.FieldLoanPolicyID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case bookcopy.FieldIsReferenceOnly:
			values[i] = new(sql.NullBool)
		case bookcopy.FieldBarcode, bookcopy.FieldAccessionNo, bookcopy.FieldCallNumber, bookcopy.FieldShelfLocation, bookcopy.FieldStatus, bookcopy.FieldCondition, bookcopy.FieldNotes:
			values[i] = new(sql.NullString)
		case bookcopy.FieldCreatedAt, bookcopy.FieldUpdatedAt, bookcopy.FieldAcquisitionDate:
			values[i] = new(sql.NullTime)
		case bookcopy.FieldID, bookcopy.FieldTenantID, bookcopy.FieldBibRecordID, bookcopy.FieldBranchID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BookCopy fields.
func (_m *BookCopy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case bookcopy.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case bookcopy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case bookcopy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case bookcopy.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case bookcopy.FieldBibRecordID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field bib_record_id", values[i])
			} else if value != nil {
				_m.BibRecordID = *value
			}
		case bookcopy.FieldBranchID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field branch_id", values[i])
			} else if value != nil {
				_m.BranchID = *value
			}
		case bookcopy.FieldBarcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field barcode", values[i])
			} else if value.Valid {
				_m.Barcode = value.String
			}
		case bookcopy.FieldAccessionNo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field accession_no", values[i])
			} else if value.Valid {
				_m.AccessionNo = value.String
			}
		case bookcopy.FieldCallNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field call_number", values[i])
			} else if value.Valid {
				_m.CallNumber = value.String
			}
		case bookcopy.FieldShelfLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shelf_location", values[i])
			} else if value.Valid {
				_m.ShelfLocation = value.String
			}
		case bookcopy.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = bookcopy.Status(value.String)
			}
		case bookcopy.FieldCondition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field condition", values[i])
			} else if value.Valid {
				_m.Condition = value.String
			}
		case bookcopy.FieldIsReferenceOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_reference_only", values[i])
			} else if value.Valid {
				_m.IsReferenceOnly = value.Bool
			}
		case bookcopy.FieldAcquisitionCost:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field acquisition_cost", values[i])
			} else if value.Valid {
				_m.AcquisitionCost = new(decimal.Decimal)
				*_m.AcquisitionCost = *value.S.(*decimal.Decimal)
			}
		case bookcopy.FieldAcquisitionDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field acquisition_date", values[i])
			} else if value.Valid {
				_m.AcquisitionDate = new(time.Time)
				*_m.AcquisitionDate = value.Time
			}
		case bookcopy.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case bookcopy.FieldLoanPolicyID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field loan_policy_id", values[i])
			} else if value.Valid {
				_m.LoanPolicyID = new(uuid.UUID)
				*_m.LoanPolicyID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BookCopy.
// This includes values selected through modifiers, order, etc.
func (_m *BookCopy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BookCopy.
// Note that you need to call BookCopy.Unwrap() before calling this method if this BookCopy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BookCopy) Update() *BookCopyUpdateOne {
	return NewBookCopyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BookCopy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BookCopy) Unwrap() *BookCopy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BookCopy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BookCopy) String() string {
	var builder strings.Builder
	builder.WriteString("BookCopy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("bib_record_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BibRecordID))
	builder.WriteString(", ")
	builder.WriteString("branch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BranchID))
	builder.WriteString(", ")
	builder.WriteString("barcode=")
	builder.WriteString(_m.Barcode)
	builder.WriteString(", ")
	builder.WriteString("accession_no=")
	builder.WriteString(_m.AccessionNo)
	builder.WriteString(", ")
	builder.WriteString("call_number=")
	builder.WriteString(_m.CallNumber)
	builder.WriteString(", ")
	builder.WriteString("shelf_location=")
	builder.WriteString(_m.ShelfLocation)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("condition=")
	builder.WriteString(_m.Condition)
	builder.WriteString(", ")
	builder.WriteString("is_reference_only=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsReferenceOnly))
	builder.WriteString(", ")
	if v := _m.AcquisitionCost; v != nil {
		builder.WriteString("acquisition_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AcquisitionDate; v != nil {
		builder.WriteString("acquisition_date=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	if v := _m.LoanPolicyID; v != nil {
		builder.WriteString("loan_policy_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BookCopies is a parsable slice of BookCopy.
type BookCopies []*BookCopy
