// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/copytransfer"
	"github.com/google/uuid"
)

// CopyTransferCreate is the builder for creating a CopyTransfer entity.
type CopyTransferCreate struct {
	config
	mutation *CopyTransferMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CopyTransferCreate) SetCreatedAt(v time.Time) *CopyTransferCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableCreatedAt(v *time.Time) *CopyTransferCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CopyTransferCreate) SetUpdatedAt(v time.Time) *CopyTransferCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableUpdatedAt(v *time.Time) *CopyTransferCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *CopyTransferCreate) SetTenantID(v uuid.UUID) *CopyTransferCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCopyID sets the "copy_id" field.
func (_c *CopyTransferCreate) SetCopyID(v uuid.UUID) *CopyTransferCreate {
	_c.mutation.SetCopyID(v)
	return _c
}

// SetFromBranchID sets the "from_branch_id" field.
func (_c *CopyTransferCreate) SetFromBranchID(v uuid.UUID) *CopyTransferCreate {
	_c.mutation.SetFromBranchID(v)
	return _c
}

// SetToBranchID sets the "to_branch_id" field.
func (_c *CopyTransferCreate) SetToBranchID(v uuid.UUID) *CopyTransferCreate {
	_c.mutation.SetToBranchID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CopyTransferCreate) SetStatus(v copytransfer.Status) *CopyTransferCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableStatus(v *copytransfer.Status) *CopyTransferCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetInitiatedBy sets the "initiated_by" field.
func (_c *CopyTransferCreate) SetInitiatedBy(v string) *CopyTransferCreate {
	_c.mutation.SetInitiatedBy(v)
	return _c
}

// SetNillableInitiatedBy sets the "initiated_by" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableInitiatedBy(v *string) *CopyTransferCreate {
	if v != nil {
		_c.SetInitiatedBy(*v)
	}
	return _c
}

// SetReceivedBy sets the "received_by" field.
func (_c *CopyTransferCreate) SetReceivedBy(v string) *CopyTransferCreate {
	_c.mutation.SetReceivedBy(v)
	return _c
}

// SetNillableReceivedBy sets the "received_by" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableReceivedBy(v *string) *CopyTransferCreate {
	if v != nil {
		_c.SetReceivedBy(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *CopyTransferCreate) SetNotes(v string) *CopyTransferCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableNotes(v *string) *CopyTransferCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetReceivedAt sets the "received_at" field.
func (_c *CopyTransferCreate) SetReceivedAt(v time.Time) *CopyTransferCreate {
	_c.mutation.SetReceivedAt(v)
	return _c
}

// SetNillableReceivedAt sets the "received_at" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableReceivedAt(v *time.Time) *CopyTransferCreate {
	if v != nil {
		_c.SetReceivedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CopyTransferCreate) SetID(v uuid.UUID) *CopyTransferCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *CopyTransferCreate) SetNillableID(v *uuid.UUID) *CopyTransferCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the CopyTransferMutation object of the builder.
func (_c *CopyTransferCreate) Mutation() *CopyTransferMutation {
	return _c.mutation
}

// Save creates the CopyTransfer in the database.
func (_c *CopyTransferCreate) Save(ctx context.Context) (*CopyTransfer, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CopyTransferCreate) SaveX(ctx context.Context) *CopyTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopyTransferCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopyTransferCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CopyTransferCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := copytransfer.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := copytransfer.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := copytransfer.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := copytransfer.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CopyTransferCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CopyTransfer.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CopyTransfer.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "CopyTransfer.tenant_id"`)}
	}
	if _, ok := _c.mutation.CopyID(); !ok {
		return &ValidationError{Name: "copy_id", err: errors.New(`ent: missing required field "CopyTransfer.copy_id"`)}
	}
	if _, ok := _c.mutation.FromBranchID(); !ok {
		return &ValidationError{Name: "from_branch_id", err: errors.New(`ent: missing required field "CopyTransfer.from_branch_id"`)}
	}
	if _, ok := _c.mutation.ToBranchID(); !ok {
		return &ValidationError{Name: "to_branch_id", err: errors.New(`ent: missing required field "CopyTransfer.to_branch_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CopyTransfer.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := copytransfer.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CopyTransfer.status": %w`, err)}
		}
	}
	return nil
}

func (_c *CopyTransferCreate) sqlSave(ctx context.Context) (*CopyTransfer, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CopyTransferCreate) createSpec() (*CopyTransfer, *sqlgraph.CreateSpec) {
	var (
		_node = &CopyTransfer{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(copytransfer.Table, sqlgraph.NewFieldSpec(copytransfer.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(copytransfer.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(copytransfer.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(copytransfer.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.CopyID(); ok {
		_spec.SetField(copytransfer.FieldCopyID, field.TypeUUID, value)
		_node.CopyID = value
	}
	if value, ok := _c.mutation.FromBranchID(); ok {
		_spec.SetField(copytransfer.FieldFromBranchID, field.TypeUUID, value)
		_node.FromBranchID = value
	}
	if value, ok := _c.mutation.ToBranchID(); ok {
		_spec.SetField(copytransfer.FieldToBranchID, field.TypeUUID, value)
		_node.ToBranchID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(copytransfer.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.InitiatedBy(); ok {
		_spec.SetField(copytransfer.FieldInitiatedBy, field.TypeString, value)
		_node.InitiatedBy = value
	}
	if value, ok := _c.mutation.ReceivedBy(); ok {
		_spec.SetField(copytransfer.FieldReceivedBy, field.TypeString, value)
		_node.ReceivedBy = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(copytransfer.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.ReceivedAt(); ok {
		_spec.SetField(copytransfer.FieldReceivedAt, field.TypeTime, value)
		_node.ReceivedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopyTransfer.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopyTransferUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopyTransferCreate) OnConflict(opts ...sql.ConflictOption) *CopyTransferUpsertOne {
	_c.conflict = opts
	return &CopyTransferUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopyTransferCreate) OnConflictColumns(columns ...string) *CopyTransferUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopyTransferUpsertOne{
		create: _c,
	}
}

type (
	// CopyTransferUpsertOne is the builder for "upsert"-ing
	//  one CopyTransfer node.
	CopyTransferUpsertOne struct {
		create *CopyTransferCreate
	}

	// CopyTransferUpsert is the "OnConflict" setter.
	CopyTransferUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CopyTransferUpsert) SetUpdatedAt(v time.Time) *CopyTransferUpsert {
	u.Set(copytransfer.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateUpdatedAt() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldUpdatedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *CopyTransferUpsert) SetTenantID(v uuid.UUID) *CopyTransferUpsert {
	u.Set(copytransfer.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateTenantID() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldTenantID)
	return u
}

// SetCopyID sets the "copy_id" field.
func (u *CopyTransferUpsert) SetCopyID(v uuid.UUID) *CopyTransferUpsert {
	u.Set(copytransfer.FieldCopyID, v)
	return u
}

// UpdateCopyID sets the "copy_id" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateCopyID() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldCopyID)
	return u
}

// SetFromBranchID sets the "from_branch_id" field.
func (u *CopyTransferUpsert) SetFromBranchID(v uuid.UUID) *CopyTransferUpsert {
	u.Set(copytransfer.FieldFromBranchID, v)
	return u
}

// UpdateFromBranchID sets the "from_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateFromBranchID() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldFromBranchID)
	return u
}

// SetToBranchID sets the "to_branch_id" field.
func (u *CopyTransferUpsert) SetToBranchID(v uuid.UUID) *CopyTransferUpsert {
	u.Set(copytransfer.FieldToBranchID, v)
	return u
}

// UpdateToBranchID sets the "to_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateToBranchID() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldToBranchID)
	return u
}

// SetStatus sets the "status" field.
func (u *CopyTransferUpsert) SetStatus(v copytransfer.Status) *CopyTransferUpsert {
	u.Set(copytransfer.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateStatus() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldStatus)
	return u
}

// SetInitiatedBy sets the "initiated_by" field.
func (u *CopyTransferUpsert) SetInitiatedBy(v string) *CopyTransferUpsert {
	u.Set(copytransfer.FieldInitiatedBy, v)
	return u
}

// UpdateInitiatedBy sets the "initiated_by" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateInitiatedBy() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldInitiatedBy)
	return u
}

// ClearInitiatedBy clears the value of the "initiated_by" field.
func (u *CopyTransferUpsert) ClearInitiatedBy() *CopyTransferUpsert {
	u.SetNull(copytransfer.FieldInitiatedBy)
	return u
}

// SetReceivedBy sets the "received_by" field.
func (u *CopyTransferUpsert) SetReceivedBy(v string) *CopyTransferUpsert {
	u.Set(copytransfer.FieldReceivedBy, v)
	return u
}

// UpdateReceivedBy sets the "received_by" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateReceivedBy() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldReceivedBy)
	return u
}

// ClearReceivedBy clears the value of the "received_by" field.
func (u *CopyTransferUpsert) ClearReceivedBy() *CopyTransferUpsert {
	u.SetNull(copytransfer.FieldReceivedBy)
	return u
}

// SetNotes sets the "notes" field.
func (u *CopyTransferUpsert) SetNotes(v string) *CopyTransferUpsert {
	u.Set(copytransfer.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateNotes() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *CopyTransferUpsert) ClearNotes() *CopyTransferUpsert {
	u.SetNull(copytransfer.FieldNotes)
	return u
}

// SetReceivedAt sets the "received_at" field.
func (u *CopyTransferUpsert) SetReceivedAt(v time.Time) *CopyTransferUpsert {
	u.Set(copytransfer.FieldReceivedAt, v)
	return u
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *CopyTransferUpsert) UpdateReceivedAt() *CopyTransferUpsert {
	u.SetExcluded(copytransfer.FieldReceivedAt)
	return u
}

// ClearReceivedAt clears the value of the "received_at" field.
func (u *CopyTransferUpsert) ClearReceivedAt() *CopyTransferUpsert {
	u.SetNull(copytransfer.FieldReceivedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(copytransfer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CopyTransferUpsertOne) UpdateNewValues() *CopyTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(copytransfer.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(copytransfer.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CopyTransferUpsertOne) Ignore() *CopyTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopyTransferUpsertOne) DoNothing() *CopyTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopyTransferCreate.OnConflict
// documentation for more info.
func (u *CopyTransferUpsertOne) Update(set func(*CopyTransferUpsert)) *CopyTransferUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopyTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopyTransferUpsertOne) SetUpdatedAt(v time.Time) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateUpdatedAt() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *CopyTransferUpsertOne) SetTenantID(v uuid.UUID) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateTenantID() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateTenantID()
	})
}

// SetCopyID sets the "copy_id" field.
func (u *CopyTransferUpsertOne) SetCopyID(v uuid.UUID) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetCopyID(v)
	})
}

// UpdateCopyID sets the "copy_id" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateCopyID() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateCopyID()
	})
}

// SetFromBranchID sets the "from_branch_id" field.
func (u *CopyTransferUpsertOne) SetFromBranchID(v uuid.UUID) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetFromBranchID(v)
	})
}

// UpdateFromBranchID sets the "from_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateFromBranchID() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateFromBranchID()
	})
}

// SetToBranchID sets the "to_branch_id" field.
func (u *CopyTransferUpsertOne) SetToBranchID(v uuid.UUID) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetToBranchID(v)
	})
}

// UpdateToBranchID sets the "to_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateToBranchID() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateToBranchID()
	})
}

// SetStatus sets the "status" field.
func (u *CopyTransferUpsertOne) SetStatus(v copytransfer.Status) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateStatus() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateStatus()
	})
}

// SetInitiatedBy sets the "initiated_by" field.
func (u *CopyTransferUpsertOne) SetInitiatedBy(v string) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetInitiatedBy(v)
	})
}

// UpdateInitiatedBy sets the "initiated_by" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateInitiatedBy() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateInitiatedBy()
	})
}

// ClearInitiatedBy clears the value of the "initiated_by" field.
func (u *CopyTransferUpsertOne) ClearInitiatedBy() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearInitiatedBy()
	})
}

// SetReceivedBy sets the "received_by" field.
func (u *CopyTransferUpsertOne) SetReceivedBy(v string) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetReceivedBy(v)
	})
}

// UpdateReceivedBy sets the "received_by" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateReceivedBy() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateReceivedBy()
	})
}

// ClearReceivedBy clears the value of the "received_by" field.
func (u *CopyTransferUpsertOne) ClearReceivedBy() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearReceivedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *CopyTransferUpsertOne) SetNotes(v string) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateNotes() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *CopyTransferUpsertOne) ClearNotes() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearNotes()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *CopyTransferUpsertOne) SetReceivedAt(v time.Time) *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *CopyTransferUpsertOne) UpdateReceivedAt() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateReceivedAt()
	})
}

// ClearReceivedAt clears the value of the "received_at" field.
func (u *CopyTransferUpsertOne) ClearReceivedAt() *CopyTransferUpsertOne {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearReceivedAt()
	})
}

// Exec executes the query.
func (u *CopyTransferUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopyTransferCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopyTransferUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CopyTransferUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CopyTransferUpsertOne.ID is not supported by MySQL driver. Use CopyTransferUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CopyTransferUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CopyTransferCreateBulk is the builder for creating many CopyTransfer entities in bulk.
type CopyTransferCreateBulk struct {
	config
	err      error
	builders []*CopyTransferCreate
	conflict []sql.ConflictOption
}

// Save creates the CopyTransfer entities in the database.
func (_c *CopyTransferCreateBulk) Save(ctx context.Context) ([]*CopyTransfer, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CopyTransfer, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CopyTransferMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CopyTransferCreateBulk) SaveX(ctx context.Context) []*CopyTransfer {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CopyTransferCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CopyTransferCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CopyTransfer.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CopyTransferUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CopyTransferCreateBulk) OnConflict(opts ...sql.ConflictOption) *CopyTransferUpsertBulk {
	_c.conflict = opts
	return &CopyTransferUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CopyTransferCreateBulk) OnConflictColumns(columns ...string) *CopyTransferUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CopyTransferUpsertBulk{
		create: _c,
	}
}

// CopyTransferUpsertBulk is the builder for "upsert"-ing
// a bulk of CopyTransfer nodes.
type CopyTransferUpsertBulk struct {
	create *CopyTransferCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(copytransfer.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CopyTransferUpsertBulk) UpdateNewValues() *CopyTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(copytransfer.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(copytransfer.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CopyTransfer.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CopyTransferUpsertBulk) Ignore() *CopyTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CopyTransferUpsertBulk) DoNothing() *CopyTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CopyTransferCreateBulk.OnConflict
// documentation for more info.
func (u *CopyTransferUpsertBulk) Update(set func(*CopyTransferUpsert)) *CopyTransferUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CopyTransferUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CopyTransferUpsertBulk) SetUpdatedAt(v time.Time) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateUpdatedAt() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *CopyTransferUpsertBulk) SetTenantID(v uuid.UUID) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateTenantID() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateTenantID()
	})
}

// SetCopyID sets the "copy_id" field.
func (u *CopyTransferUpsertBulk) SetCopyID(v uuid.UUID) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetCopyID(v)
	})
}

// UpdateCopyID sets the "copy_id" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateCopyID() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateCopyID()
	})
}

// SetFromBranchID sets the "from_branch_id" field.
func (u *CopyTransferUpsertBulk) SetFromBranchID(v uuid.UUID) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetFromBranchID(v)
	})
}

// UpdateFromBranchID sets the "from_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateFromBranchID() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateFromBranchID()
	})
}

// SetToBranchID sets the "to_branch_id" field.
func (u *CopyTransferUpsertBulk) SetToBranchID(v uuid.UUID) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetToBranchID(v)
	})
}

// UpdateToBranchID sets the "to_branch_id" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateToBranchID() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateToBranchID()
	})
}

// SetStatus sets the "status" field.
func (u *CopyTransferUpsertBulk) SetStatus(v copytransfer.Status) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateStatus() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateStatus()
	})
}

// SetInitiatedBy sets the "initiated_by" field.
func (u *CopyTransferUpsertBulk) SetInitiatedBy(v string) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetInitiatedBy(v)
	})
}

// UpdateInitiatedBy sets the "initiated_by" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateInitiatedBy() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateInitiatedBy()
	})
}

// ClearInitiatedBy clears the value of the "initiated_by" field.
func (u *CopyTransferUpsertBulk) ClearInitiatedBy() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearInitiatedBy()
	})
}

// SetReceivedBy sets the "received_by" field.
func (u *CopyTransferUpsertBulk) SetReceivedBy(v string) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetReceivedBy(v)
	})
}

// UpdateReceivedBy sets the "received_by" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateReceivedBy() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateReceivedBy()
	})
}

// ClearReceivedBy clears the value of the "received_by" field.
func (u *CopyTransferUpsertBulk) ClearReceivedBy() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearReceivedBy()
	})
}

// SetNotes sets the "notes" field.
func (u *CopyTransferUpsertBulk) SetNotes(v string) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateNotes() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *CopyTransferUpsertBulk) ClearNotes() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearNotes()
	})
}

// SetReceivedAt sets the "received_at" field.
func (u *CopyTransferUpsertBulk) SetReceivedAt(v time.Time) *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.SetReceivedAt(v)
	})
}

// UpdateReceivedAt sets the "received_at" field to the value that was provided on create.
func (u *CopyTransferUpsertBulk) UpdateReceivedAt() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.UpdateReceivedAt()
	})
}

// ClearReceivedAt clears the value of the "received_at" field.
func (u *CopyTransferUpsertBulk) ClearReceivedAt() *CopyTransferUpsertBulk {
	return u.Update(func(s *CopyTransferUpsert) {
		s.ClearReceivedAt()
	})
}

// Exec executes the query.
func (u *CopyTransferUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CopyTransferCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CopyTransferCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CopyTransferUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
