// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/library-service/internal/ent/ebookloan"
	"github.com/google/uuid"
)

// EbookLoan is the model entity for the EbookLoan schema.
type EbookLoan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// EbookID holds the value of the "ebook_id" field.
	EbookID uuid.UUID `json:"ebook_id,omitempty"`
	// MemberID holds the value of the "member_id" field.
	MemberID uuid.UUID `json:"member_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode ebookloan.Mode `json:"mode,omitempty"`
	// IssuedAt holds the value of the "issued_at" field.
	IssuedAt time.Time `json:"issued_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ReturnedAt holds the value of the "returned_at" field.
	ReturnedAt *time.Time `json:"returned_at,omitempty"`
	// AccessToken holds the value of the "access_token" field.
	AccessToken string `json:"access_token,omitempty"`
	// LastReadPosition holds the value of the "last_read_position" field.
	LastReadPosition map[string]interface{} `json:"last_read_position,omitempty"`
	selectValues     sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EbookLoan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ebookloan.FieldLastReadPosition:
			values[i] = new([]byte)
		case ebookloan.FieldMode, ebookloan.FieldAccessToken:
			values[i] = new(sql.NullString)
		case ebookloan.FieldCreatedAt, ebookloan.FieldUpdatedAt, ebookloan.FieldIssuedAt, ebookloan.FieldExpiresAt, ebookloan.FieldReturnedAt:
			values[i] = new(sql.NullTime)
		case ebookloan.FieldID, ebookloan.FieldTenantID, ebookloan.FieldEbookID, ebookloan.FieldMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EbookLoan fields.
func (_m *EbookLoan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ebookloan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case ebookloan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ebookloan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ebookloan.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case ebookloan.FieldEbookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field ebook_id", values[i])
			} else if value != nil {
				_m.EbookID = *value
			}
		case ebookloan.FieldMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field member_id", values[i])
			} else if value != nil {
				_m.MemberID = *value
			}
		case ebookloan.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = ebookloan.Mode(value.String)
			}
		case ebookloan.FieldIssuedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field issued_at", values[i])
			} else if value.Valid {
				_m.IssuedAt = value.Time
			}
		case ebookloan.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case ebookloan.FieldReturnedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field returned_at", values[i])
			} else if value.Valid {
				_m.ReturnedAt = new(time.Time)
				*_m.ReturnedAt = value.Time
			}
		case ebookloan.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = value.String
			}
		case ebookloan.FieldLastReadPosition:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field last_read_position", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LastReadPosition); err != nil {
					return fmt.Errorf("unmarshal field last_read_position: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EbookLoan.
// This includes values selected through modifiers, order, etc.
func (_m *EbookLoan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this EbookLoan.
// Note that you need to call EbookLoan.Unwrap() before calling this method if this EbookLoan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EbookLoan) Update() *EbookLoanUpdateOne {
	return NewEbookLoanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EbookLoan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EbookLoan) Unwrap() *EbookLoan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EbookLoan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EbookLoan) String() string {
	var builder strings.Builder
	builder.WriteString("EbookLoan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("ebook_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EbookID))
	builder.WriteString(", ")
	builder.WriteString("member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MemberID))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.Mode))
	builder.WriteString(", ")
	builder.WriteString("issued_at=")
	builder.WriteString(_m.IssuedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ReturnedAt; v != nil {
		builder.WriteString("returned_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("access_token=")
	builder.WriteString(_m.AccessToken)
	builder.WriteString(", ")
	builder.WriteString("last_read_position=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastReadPosition))
	builder.WriteByte(')')
	return builder.String()
}

// EbookLoans is a parsable slice of EbookLoan.
type EbookLoans []*EbookLoan
