// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/libraryrole"
	"github.com/bengobox/library-service/internal/ent/predicate"
)

// LibraryRoleUpdate is the builder for updating LibraryRole entities.
type LibraryRoleUpdate struct {
	config
	hooks    []Hook
	mutation *LibraryRoleMutation
}

// Where appends a list predicates to the LibraryRoleUpdate builder.
func (_u *LibraryRoleUpdate) Where(ps ...predicate.LibraryRole) *LibraryRoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryRoleUpdate) SetUpdatedAt(v time.Time) *LibraryRoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *LibraryRoleUpdate) SetName(v string) *LibraryRoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryRoleUpdate) SetNillableName(v *string) *LibraryRoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LibraryRoleUpdate) SetDescription(v string) *LibraryRoleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LibraryRoleUpdate) SetNillableDescription(v *string) *LibraryRoleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LibraryRoleUpdate) ClearDescription() *LibraryRoleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *LibraryRoleUpdate) SetPermissions(v []string) *LibraryRoleUpdate {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *LibraryRoleUpdate) AppendPermissions(v []string) *LibraryRoleUpdate {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *LibraryRoleUpdate) ClearPermissions() *LibraryRoleUpdate {
	_u.mutation.ClearPermissions()
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *LibraryRoleUpdate) SetIsSystem(v bool) *LibraryRoleUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *LibraryRoleUpdate) SetNillableIsSystem(v *bool) *LibraryRoleUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// Mutation returns the LibraryRoleMutation object of the builder.
func (_u *LibraryRoleUpdate) Mutation() *LibraryRoleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LibraryRoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LibraryRoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryRoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryRoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := libraryrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryRoleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := libraryrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LibraryRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LibraryRoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(libraryrole.Table, libraryrole.Columns, sqlgraph.NewFieldSpec(libraryrole.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(libraryrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(libraryrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(libraryrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(libraryrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(libraryrole.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, libraryrole.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(libraryrole.FieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(libraryrole.FieldIsSystem, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{libraryrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LibraryRoleUpdateOne is the builder for updating a single LibraryRole entity.
type LibraryRoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LibraryRoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LibraryRoleUpdateOne) SetUpdatedAt(v time.Time) *LibraryRoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *LibraryRoleUpdateOne) SetName(v string) *LibraryRoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *LibraryRoleUpdateOne) SetNillableName(v *string) *LibraryRoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *LibraryRoleUpdateOne) SetDescription(v string) *LibraryRoleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *LibraryRoleUpdateOne) SetNillableDescription(v *string) *LibraryRoleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *LibraryRoleUpdateOne) ClearDescription() *LibraryRoleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPermissions sets the "permissions" field.
func (_u *LibraryRoleUpdateOne) SetPermissions(v []string) *LibraryRoleUpdateOne {
	_u.mutation.SetPermissions(v)
	return _u
}

// AppendPermissions appends value to the "permissions" field.
func (_u *LibraryRoleUpdateOne) AppendPermissions(v []string) *LibraryRoleUpdateOne {
	_u.mutation.AppendPermissions(v)
	return _u
}

// ClearPermissions clears the value of the "permissions" field.
func (_u *LibraryRoleUpdateOne) ClearPermissions() *LibraryRoleUpdateOne {
	_u.mutation.ClearPermissions()
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *LibraryRoleUpdateOne) SetIsSystem(v bool) *LibraryRoleUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *LibraryRoleUpdateOne) SetNillableIsSystem(v *bool) *LibraryRoleUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// Mutation returns the LibraryRoleMutation object of the builder.
func (_u *LibraryRoleUpdateOne) Mutation() *LibraryRoleMutation {
	return _u.mutation
}

// Where appends a list predicates to the LibraryRoleUpdate builder.
func (_u *LibraryRoleUpdateOne) Where(ps ...predicate.LibraryRole) *LibraryRoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LibraryRoleUpdateOne) Select(field string, fields ...string) *LibraryRoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LibraryRole entity.
func (_u *LibraryRoleUpdateOne) Save(ctx context.Context) (*LibraryRole, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LibraryRoleUpdateOne) SaveX(ctx context.Context) *LibraryRole {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LibraryRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LibraryRoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LibraryRoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := libraryrole.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LibraryRoleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := libraryrole.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LibraryRole.name": %w`, err)}
		}
	}
	return nil
}

func (_u *LibraryRoleUpdateOne) sqlSave(ctx context.Context) (_node *LibraryRole, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(libraryrole.Table, libraryrole.Columns, sqlgraph.NewFieldSpec(libraryrole.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LibraryRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, libraryrole.FieldID)
		for _, f := range fields {
			if !libraryrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != libraryrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(libraryrole.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(libraryrole.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(libraryrole.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(libraryrole.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Permissions(); ok {
		_spec.SetField(libraryrole.FieldPermissions, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPermissions(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, libraryrole.FieldPermissions, value)
		})
	}
	if _u.mutation.PermissionsCleared() {
		_spec.ClearField(libraryrole.FieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(libraryrole.FieldIsSystem, field.TypeBool, value)
	}
	_node = &LibraryRole{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{libraryrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
