// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/loanpolicy"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LoanPolicyCreate is the builder for creating a LoanPolicy entity.
type LoanPolicyCreate struct {
	config
	mutation *LoanPolicyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoanPolicyCreate) SetCreatedAt(v time.Time) *LoanPolicyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableCreatedAt(v *time.Time) *LoanPolicyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LoanPolicyCreate) SetUpdatedAt(v time.Time) *LoanPolicyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableUpdatedAt(v *time.Time) *LoanPolicyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *LoanPolicyCreate) SetTenantID(v uuid.UUID) *LoanPolicyCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *LoanPolicyCreate) SetName(v string) *LoanPolicyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetLoanPeriodDays sets the "loan_period_days" field.
func (_c *LoanPolicyCreate) SetLoanPeriodDays(v int) *LoanPolicyCreate {
	_c.mutation.SetLoanPeriodDays(v)
	return _c
}

// SetNillableLoanPeriodDays sets the "loan_period_days" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableLoanPeriodDays(v *int) *LoanPolicyCreate {
	if v != nil {
		_c.SetLoanPeriodDays(*v)
	}
	return _c
}

// SetMaxRenewals sets the "max_renewals" field.
func (_c *LoanPolicyCreate) SetMaxRenewals(v int) *LoanPolicyCreate {
	_c.mutation.SetMaxRenewals(v)
	return _c
}

// SetNillableMaxRenewals sets the "max_renewals" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableMaxRenewals(v *int) *LoanPolicyCreate {
	if v != nil {
		_c.SetMaxRenewals(*v)
	}
	return _c
}

// SetHoldable sets the "holdable" field.
func (_c *LoanPolicyCreate) SetHoldable(v bool) *LoanPolicyCreate {
	_c.mutation.SetHoldable(v)
	return _c
}

// SetNillableHoldable sets the "holdable" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableHoldable(v *bool) *LoanPolicyCreate {
	if v != nil {
		_c.SetHoldable(*v)
	}
	return _c
}

// SetFinePerDay sets the "fine_per_day" field.
func (_c *LoanPolicyCreate) SetFinePerDay(v decimal.Decimal) *LoanPolicyCreate {
	_c.mutation.SetFinePerDay(v)
	return _c
}

// SetNillableFinePerDay sets the "fine_per_day" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableFinePerDay(v *decimal.Decimal) *LoanPolicyCreate {
	if v != nil {
		_c.SetFinePerDay(*v)
	}
	return _c
}

// SetGraceDays sets the "grace_days" field.
func (_c *LoanPolicyCreate) SetGraceDays(v int) *LoanPolicyCreate {
	_c.mutation.SetGraceDays(v)
	return _c
}

// SetNillableGraceDays sets the "grace_days" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableGraceDays(v *int) *LoanPolicyCreate {
	if v != nil {
		_c.SetGraceDays(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *LoanPolicyCreate) SetIsDefault(v bool) *LoanPolicyCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableIsDefault(v *bool) *LoanPolicyCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LoanPolicyCreate) SetID(v uuid.UUID) *LoanPolicyCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LoanPolicyCreate) SetNillableID(v *uuid.UUID) *LoanPolicyCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LoanPolicyMutation object of the builder.
func (_c *LoanPolicyCreate) Mutation() *LoanPolicyMutation {
	return _c.mutation
}

// Save creates the LoanPolicy in the database.
func (_c *LoanPolicyCreate) Save(ctx context.Context) (*LoanPolicy, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoanPolicyCreate) SaveX(ctx context.Context) *LoanPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanPolicyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanPolicyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoanPolicyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := loanpolicy.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := loanpolicy.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LoanPeriodDays(); !ok {
		v := loanpolicy.DefaultLoanPeriodDays
		_c.mutation.SetLoanPeriodDays(v)
	}
	if _, ok := _c.mutation.MaxRenewals(); !ok {
		v := loanpolicy.DefaultMaxRenewals
		_c.mutation.SetMaxRenewals(v)
	}
	if _, ok := _c.mutation.Holdable(); !ok {
		v := loanpolicy.DefaultHoldable
		_c.mutation.SetHoldable(v)
	}
	if _, ok := _c.mutation.FinePerDay(); !ok {
		v := loanpolicy.DefaultFinePerDay
		_c.mutation.SetFinePerDay(v)
	}
	if _, ok := _c.mutation.GraceDays(); !ok {
		v := loanpolicy.DefaultGraceDays
		_c.mutation.SetGraceDays(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := loanpolicy.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := loanpolicy.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoanPolicyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LoanPolicy.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LoanPolicy.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "LoanPolicy.tenant_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "LoanPolicy.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := loanpolicy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "LoanPolicy.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoanPeriodDays(); !ok {
		return &ValidationError{Name: "loan_period_days", err: errors.New(`ent: missing required field "LoanPolicy.loan_period_days"`)}
	}
	if _, ok := _c.mutation.MaxRenewals(); !ok {
		return &ValidationError{Name: "max_renewals", err: errors.New(`ent: missing required field "LoanPolicy.max_renewals"`)}
	}
	if _, ok := _c.mutation.Holdable(); !ok {
		return &ValidationError{Name: "holdable", err: errors.New(`ent: missing required field "LoanPolicy.holdable"`)}
	}
	if _, ok := _c.mutation.FinePerDay(); !ok {
		return &ValidationError{Name: "fine_per_day", err: errors.New(`ent: missing required field "LoanPolicy.fine_per_day"`)}
	}
	if _, ok := _c.mutation.GraceDays(); !ok {
		return &ValidationError{Name: "grace_days", err: errors.New(`ent: missing required field "LoanPolicy.grace_days"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "LoanPolicy.is_default"`)}
	}
	return nil
}

func (_c *LoanPolicyCreate) sqlSave(ctx context.Context) (*LoanPolicy, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoanPolicyCreate) createSpec() (*LoanPolicy, *sqlgraph.CreateSpec) {
	var (
		_node = &LoanPolicy{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loanpolicy.Table, sqlgraph.NewFieldSpec(loanpolicy.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loanpolicy.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(loanpolicy.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(loanpolicy.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(loanpolicy.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.LoanPeriodDays(); ok {
		_spec.SetField(loanpolicy.FieldLoanPeriodDays, field.TypeInt, value)
		_node.LoanPeriodDays = value
	}
	if value, ok := _c.mutation.MaxRenewals(); ok {
		_spec.SetField(loanpolicy.FieldMaxRenewals, field.TypeInt, value)
		_node.MaxRenewals = value
	}
	if value, ok := _c.mutation.Holdable(); ok {
		_spec.SetField(loanpolicy.FieldHoldable, field.TypeBool, value)
		_node.Holdable = value
	}
	if value, ok := _c.mutation.FinePerDay(); ok {
		_spec.SetField(loanpolicy.FieldFinePerDay, field.TypeOther, value)
		_node.FinePerDay = value
	}
	if value, ok := _c.mutation.GraceDays(); ok {
		_spec.SetField(loanpolicy.FieldGraceDays, field.TypeInt, value)
		_node.GraceDays = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(loanpolicy.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoanPolicy.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoanPolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoanPolicyCreate) OnConflict(opts ...sql.ConflictOption) *LoanPolicyUpsertOne {
	_c.conflict = opts
	return &LoanPolicyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoanPolicyCreate) OnConflictColumns(columns ...string) *LoanPolicyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoanPolicyUpsertOne{
		create: _c,
	}
}

type (
	// LoanPolicyUpsertOne is the builder for "upsert"-ing
	//  one LoanPolicy node.
	LoanPolicyUpsertOne struct {
		create *LoanPolicyCreate
	}

	// LoanPolicyUpsert is the "OnConflict" setter.
	LoanPolicyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanPolicyUpsert) SetUpdatedAt(v time.Time) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateUpdatedAt() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldUpdatedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LoanPolicyUpsert) SetTenantID(v uuid.UUID) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateTenantID() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldTenantID)
	return u
}

// SetName sets the "name" field.
func (u *LoanPolicyUpsert) SetName(v string) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateName() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldName)
	return u
}

// SetLoanPeriodDays sets the "loan_period_days" field.
func (u *LoanPolicyUpsert) SetLoanPeriodDays(v int) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldLoanPeriodDays, v)
	return u
}

// UpdateLoanPeriodDays sets the "loan_period_days" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateLoanPeriodDays() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldLoanPeriodDays)
	return u
}

// AddLoanPeriodDays adds v to the "loan_period_days" field.
func (u *LoanPolicyUpsert) AddLoanPeriodDays(v int) *LoanPolicyUpsert {
	u.Add(loanpolicy.FieldLoanPeriodDays, v)
	return u
}

// SetMaxRenewals sets the "max_renewals" field.
func (u *LoanPolicyUpsert) SetMaxRenewals(v int) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldMaxRenewals, v)
	return u
}

// UpdateMaxRenewals sets the "max_renewals" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateMaxRenewals() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldMaxRenewals)
	return u
}

// AddMaxRenewals adds v to the "max_renewals" field.
func (u *LoanPolicyUpsert) AddMaxRenewals(v int) *LoanPolicyUpsert {
	u.Add(loanpolicy.FieldMaxRenewals, v)
	return u
}

// SetHoldable sets the "holdable" field.
func (u *LoanPolicyUpsert) SetHoldable(v bool) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldHoldable, v)
	return u
}

// UpdateHoldable sets the "holdable" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateHoldable() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldHoldable)
	return u
}

// SetFinePerDay sets the "fine_per_day" field.
func (u *LoanPolicyUpsert) SetFinePerDay(v decimal.Decimal) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldFinePerDay, v)
	return u
}

// UpdateFinePerDay sets the "fine_per_day" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateFinePerDay() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldFinePerDay)
	return u
}

// SetGraceDays sets the "grace_days" field.
func (u *LoanPolicyUpsert) SetGraceDays(v int) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldGraceDays, v)
	return u
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateGraceDays() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldGraceDays)
	return u
}

// AddGraceDays adds v to the "grace_days" field.
func (u *LoanPolicyUpsert) AddGraceDays(v int) *LoanPolicyUpsert {
	u.Add(loanpolicy.FieldGraceDays, v)
	return u
}

// SetIsDefault sets the "is_default" field.
func (u *LoanPolicyUpsert) SetIsDefault(v bool) *LoanPolicyUpsert {
	u.Set(loanpolicy.FieldIsDefault, v)
	return u
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *LoanPolicyUpsert) UpdateIsDefault() *LoanPolicyUpsert {
	u.SetExcluded(loanpolicy.FieldIsDefault)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(loanpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LoanPolicyUpsertOne) UpdateNewValues() *LoanPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(loanpolicy.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(loanpolicy.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LoanPolicyUpsertOne) Ignore() *LoanPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoanPolicyUpsertOne) DoNothing() *LoanPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoanPolicyCreate.OnConflict
// documentation for more info.
func (u *LoanPolicyUpsertOne) Update(set func(*LoanPolicyUpsert)) *LoanPolicyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoanPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanPolicyUpsertOne) SetUpdatedAt(v time.Time) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateUpdatedAt() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *LoanPolicyUpsertOne) SetTenantID(v uuid.UUID) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateTenantID() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *LoanPolicyUpsertOne) SetName(v string) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateName() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateName()
	})
}

// SetLoanPeriodDays sets the "loan_period_days" field.
func (u *LoanPolicyUpsertOne) SetLoanPeriodDays(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetLoanPeriodDays(v)
	})
}

// AddLoanPeriodDays adds v to the "loan_period_days" field.
func (u *LoanPolicyUpsertOne) AddLoanPeriodDays(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddLoanPeriodDays(v)
	})
}

// UpdateLoanPeriodDays sets the "loan_period_days" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateLoanPeriodDays() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateLoanPeriodDays()
	})
}

// SetMaxRenewals sets the "max_renewals" field.
func (u *LoanPolicyUpsertOne) SetMaxRenewals(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetMaxRenewals(v)
	})
}

// AddMaxRenewals adds v to the "max_renewals" field.
func (u *LoanPolicyUpsertOne) AddMaxRenewals(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddMaxRenewals(v)
	})
}

// UpdateMaxRenewals sets the "max_renewals" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateMaxRenewals() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateMaxRenewals()
	})
}

// SetHoldable sets the "holdable" field.
func (u *LoanPolicyUpsertOne) SetHoldable(v bool) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetHoldable(v)
	})
}

// UpdateHoldable sets the "holdable" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateHoldable() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateHoldable()
	})
}

// SetFinePerDay sets the "fine_per_day" field.
func (u *LoanPolicyUpsertOne) SetFinePerDay(v decimal.Decimal) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetFinePerDay(v)
	})
}

// UpdateFinePerDay sets the "fine_per_day" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateFinePerDay() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateFinePerDay()
	})
}

// SetGraceDays sets the "grace_days" field.
func (u *LoanPolicyUpsertOne) SetGraceDays(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetGraceDays(v)
	})
}

// AddGraceDays adds v to the "grace_days" field.
func (u *LoanPolicyUpsertOne) AddGraceDays(v int) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddGraceDays(v)
	})
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateGraceDays() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateGraceDays()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *LoanPolicyUpsertOne) SetIsDefault(v bool) *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *LoanPolicyUpsertOne) UpdateIsDefault() *LoanPolicyUpsertOne {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateIsDefault()
	})
}

// Exec executes the query.
func (u *LoanPolicyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoanPolicyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoanPolicyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LoanPolicyUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LoanPolicyUpsertOne.ID is not supported by MySQL driver. Use LoanPolicyUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LoanPolicyUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LoanPolicyCreateBulk is the builder for creating many LoanPolicy entities in bulk.
type LoanPolicyCreateBulk struct {
	config
	err      error
	builders []*LoanPolicyCreate
	conflict []sql.ConflictOption
}

// Save creates the LoanPolicy entities in the database.
func (_c *LoanPolicyCreateBulk) Save(ctx context.Context) ([]*LoanPolicy, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoanPolicy, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoanPolicyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoanPolicyCreateBulk) SaveX(ctx context.Context) []*LoanPolicy {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoanPolicyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoanPolicyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LoanPolicy.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LoanPolicyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LoanPolicyCreateBulk) OnConflict(opts ...sql.ConflictOption) *LoanPolicyUpsertBulk {
	_c.conflict = opts
	return &LoanPolicyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LoanPolicyCreateBulk) OnConflictColumns(columns ...string) *LoanPolicyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LoanPolicyUpsertBulk{
		create: _c,
	}
}

// LoanPolicyUpsertBulk is the builder for "upsert"-ing
// a bulk of LoanPolicy nodes.
type LoanPolicyUpsertBulk struct {
	create *LoanPolicyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(loanpolicy.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LoanPolicyUpsertBulk) UpdateNewValues() *LoanPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(loanpolicy.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(loanpolicy.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LoanPolicy.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LoanPolicyUpsertBulk) Ignore() *LoanPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LoanPolicyUpsertBulk) DoNothing() *LoanPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LoanPolicyCreateBulk.OnConflict
// documentation for more info.
func (u *LoanPolicyUpsertBulk) Update(set func(*LoanPolicyUpsert)) *LoanPolicyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LoanPolicyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LoanPolicyUpsertBulk) SetUpdatedAt(v time.Time) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateUpdatedAt() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *LoanPolicyUpsertBulk) SetTenantID(v uuid.UUID) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateTenantID() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateTenantID()
	})
}

// SetName sets the "name" field.
func (u *LoanPolicyUpsertBulk) SetName(v string) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateName() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateName()
	})
}

// SetLoanPeriodDays sets the "loan_period_days" field.
func (u *LoanPolicyUpsertBulk) SetLoanPeriodDays(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetLoanPeriodDays(v)
	})
}

// AddLoanPeriodDays adds v to the "loan_period_days" field.
func (u *LoanPolicyUpsertBulk) AddLoanPeriodDays(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddLoanPeriodDays(v)
	})
}

// UpdateLoanPeriodDays sets the "loan_period_days" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateLoanPeriodDays() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateLoanPeriodDays()
	})
}

// SetMaxRenewals sets the "max_renewals" field.
func (u *LoanPolicyUpsertBulk) SetMaxRenewals(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetMaxRenewals(v)
	})
}

// AddMaxRenewals adds v to the "max_renewals" field.
func (u *LoanPolicyUpsertBulk) AddMaxRenewals(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddMaxRenewals(v)
	})
}

// UpdateMaxRenewals sets the "max_renewals" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateMaxRenewals() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateMaxRenewals()
	})
}

// SetHoldable sets the "holdable" field.
func (u *LoanPolicyUpsertBulk) SetHoldable(v bool) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetHoldable(v)
	})
}

// UpdateHoldable sets the "holdable" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateHoldable() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateHoldable()
	})
}

// SetFinePerDay sets the "fine_per_day" field.
func (u *LoanPolicyUpsertBulk) SetFinePerDay(v decimal.Decimal) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetFinePerDay(v)
	})
}

// UpdateFinePerDay sets the "fine_per_day" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateFinePerDay() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateFinePerDay()
	})
}

// SetGraceDays sets the "grace_days" field.
func (u *LoanPolicyUpsertBulk) SetGraceDays(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetGraceDays(v)
	})
}

// AddGraceDays adds v to the "grace_days" field.
func (u *LoanPolicyUpsertBulk) AddGraceDays(v int) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.AddGraceDays(v)
	})
}

// UpdateGraceDays sets the "grace_days" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateGraceDays() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateGraceDays()
	})
}

// SetIsDefault sets the "is_default" field.
func (u *LoanPolicyUpsertBulk) SetIsDefault(v bool) *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.SetIsDefault(v)
	})
}

// UpdateIsDefault sets the "is_default" field to the value that was provided on create.
func (u *LoanPolicyUpsertBulk) UpdateIsDefault() *LoanPolicyUpsertBulk {
	return u.Update(func(s *LoanPolicyUpsert) {
		s.UpdateIsDefault()
	})
}

// Exec executes the query.
func (u *LoanPolicyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LoanPolicyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LoanPolicyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LoanPolicyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
