// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/library-service/internal/ent/membertier"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// MemberTier is the model entity for the MemberTier schema.
type MemberTier struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MaxConcurrentLoans holds the value of the "max_concurrent_loans" field.
	MaxConcurrentLoans int `json:"max_concurrent_loans,omitempty"`
	// LoanPeriodDays holds the value of the "loan_period_days" field.
	LoanPeriodDays int `json:"loan_period_days,omitempty"`
	// MaxRenewals holds the value of the "max_renewals" field.
	MaxRenewals int `json:"max_renewals,omitempty"`
	// HoldLimit holds the value of the "hold_limit" field.
	HoldLimit int `json:"hold_limit,omitempty"`
	// EbookConcurrentLimit holds the value of the "ebook_concurrent_limit" field.
	EbookConcurrentLimit int `json:"ebook_concurrent_limit,omitempty"`
	// DailyFineRate holds the value of the "daily_fine_rate" field.
	DailyFineRate decimal.Decimal `json:"daily_fine_rate,omitempty"`
	// MaxFineBeforeBlock holds the value of the "max_fine_before_block" field.
	MaxFineBeforeBlock decimal.Decimal `json:"max_fine_before_block,omitempty"`
	// AnnualFee holds the value of the "annual_fee" field.
	AnnualFee decimal.Decimal `json:"annual_fee,omitempty"`
	// IsDefault holds the value of the "is_default" field.
	IsDefault    bool `json:"is_default,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MemberTier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case membertier.FieldDailyFineRate, membertier.FieldMaxFineBeforeBlock, membertier.FieldAnnualFee:
			values[i] = new(decimal.Decimal)
		case membertier.FieldIsDefault:
			values[i] = new(sql.NullBool)
		case membertier.FieldMaxConcurrentLoans, membertier.FieldLoanPeriodDays, membertier.FieldMaxRenewals, membertier.FieldHoldLimit, membertier.FieldEbookConcurrentLimit:
			values[i] = new(sql.NullInt64)
		case membertier.FieldName:
			values[i] = new(sql.NullString)
		case membertier.FieldCreatedAt, membertier.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case membertier.FieldID, membertier.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MemberTier fields.
func (_m *MemberTier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case membertier.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case membertier.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case membertier.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case membertier.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case membertier.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case membertier.FieldMaxConcurrentLoans:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_concurrent_loans", values[i])
			} else if value.Valid {
				_m.MaxConcurrentLoans = int(value.Int64)
			}
		case membertier.FieldLoanPeriodDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field loan_period_days", values[i])
			} else if value.Valid {
				_m.LoanPeriodDays = int(value.Int64)
			}
		case membertier.FieldMaxRenewals:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_renewals", values[i])
			} else if value.Valid {
				_m.MaxRenewals = int(value.Int64)
			}
		case membertier.FieldHoldLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hold_limit", values[i])
			} else if value.Valid {
				_m.HoldLimit = int(value.Int64)
			}
		case membertier.FieldEbookConcurrentLimit:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ebook_concurrent_limit", values[i])
			} else if value.Valid {
				_m.EbookConcurrentLimit = int(value.Int64)
			}
		case membertier.FieldDailyFineRate:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field daily_fine_rate", values[i])
			} else if value != nil {
				_m.DailyFineRate = *value
			}
		case membertier.FieldMaxFineBeforeBlock:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field max_fine_before_block", values[i])
			} else if value != nil {
				_m.MaxFineBeforeBlock = *value
			}
		case membertier.FieldAnnualFee:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field annual_fee", values[i])
			} else if value != nil {
				_m.AnnualFee = *value
			}
		case membertier.FieldIsDefault:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_default", values[i])
			} else if value.Valid {
				_m.IsDefault = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MemberTier.
// This includes values selected through modifiers, order, etc.
func (_m *MemberTier) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MemberTier.
// Note that you need to call MemberTier.Unwrap() before calling this method if this MemberTier
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MemberTier) Update() *MemberTierUpdateOne {
	return NewMemberTierClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MemberTier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MemberTier) Unwrap() *MemberTier {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MemberTier is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MemberTier) String() string {
	var builder strings.Builder
	builder.WriteString("MemberTier(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("max_concurrent_loans=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxConcurrentLoans))
	builder.WriteString(", ")
	builder.WriteString("loan_period_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoanPeriodDays))
	builder.WriteString(", ")
	builder.WriteString("max_renewals=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRenewals))
	builder.WriteString(", ")
	builder.WriteString("hold_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoldLimit))
	builder.WriteString(", ")
	builder.WriteString("ebook_concurrent_limit=")
	builder.WriteString(fmt.Sprintf("%v", _m.EbookConcurrentLimit))
	builder.WriteString(", ")
	builder.WriteString("daily_fine_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.DailyFineRate))
	builder.WriteString(", ")
	builder.WriteString("max_fine_before_block=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxFineBeforeBlock))
	builder.WriteString(", ")
	builder.WriteString("annual_fee=")
	builder.WriteString(fmt.Sprintf("%v", _m.AnnualFee))
	builder.WriteString(", ")
	builder.WriteString("is_default=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDefault))
	builder.WriteByte(')')
	return builder.String()
}

// MemberTiers is a parsable slice of MemberTier.
type MemberTiers []*MemberTier
