// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/purchaseorder"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// PurchaseOrderCreate is the builder for creating a PurchaseOrder entity.
type PurchaseOrderCreate struct {
	config
	mutation *PurchaseOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PurchaseOrderCreate) SetCreatedAt(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableCreatedAt(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PurchaseOrderCreate) SetUpdatedAt(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableUpdatedAt(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *PurchaseOrderCreate) SetTenantID(v uuid.UUID) *PurchaseOrderCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPoNumber sets the "po_number" field.
func (_c *PurchaseOrderCreate) SetPoNumber(v string) *PurchaseOrderCreate {
	_c.mutation.SetPoNumber(v)
	return _c
}

// SetNillablePoNumber sets the "po_number" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillablePoNumber(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetPoNumber(*v)
	}
	return _c
}

// SetVendorID sets the "vendor_id" field.
func (_c *PurchaseOrderCreate) SetVendorID(v uuid.UUID) *PurchaseOrderCreate {
	_c.mutation.SetVendorID(v)
	return _c
}

// SetFundID sets the "fund_id" field.
func (_c *PurchaseOrderCreate) SetFundID(v uuid.UUID) *PurchaseOrderCreate {
	_c.mutation.SetFundID(v)
	return _c
}

// SetNillableFundID sets the "fund_id" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableFundID(v *uuid.UUID) *PurchaseOrderCreate {
	if v != nil {
		_c.SetFundID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PurchaseOrderCreate) SetStatus(v purchaseorder.Status) *PurchaseOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableStatus(v *purchaseorder.Status) *PurchaseOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetOrderDate sets the "order_date" field.
func (_c *PurchaseOrderCreate) SetOrderDate(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetOrderDate(v)
	return _c
}

// SetNillableOrderDate sets the "order_date" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableOrderDate(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetOrderDate(*v)
	}
	return _c
}

// SetExpectedDate sets the "expected_date" field.
func (_c *PurchaseOrderCreate) SetExpectedDate(v time.Time) *PurchaseOrderCreate {
	_c.mutation.SetExpectedDate(v)
	return _c
}

// SetNillableExpectedDate sets the "expected_date" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableExpectedDate(v *time.Time) *PurchaseOrderCreate {
	if v != nil {
		_c.SetExpectedDate(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PurchaseOrderCreate) SetNotes(v string) *PurchaseOrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableNotes(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetSubtotal sets the "subtotal" field.
func (_c *PurchaseOrderCreate) SetSubtotal(v decimal.Decimal) *PurchaseOrderCreate {
	_c.mutation.SetSubtotal(v)
	return _c
}

// SetNillableSubtotal sets the "subtotal" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableSubtotal(v *decimal.Decimal) *PurchaseOrderCreate {
	if v != nil {
		_c.SetSubtotal(*v)
	}
	return _c
}

// SetTax sets the "tax" field.
func (_c *PurchaseOrderCreate) SetTax(v decimal.Decimal) *PurchaseOrderCreate {
	_c.mutation.SetTax(v)
	return _c
}

// SetNillableTax sets the "tax" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableTax(v *decimal.Decimal) *PurchaseOrderCreate {
	if v != nil {
		_c.SetTax(*v)
	}
	return _c
}

// SetTotal sets the "total" field.
func (_c *PurchaseOrderCreate) SetTotal(v decimal.Decimal) *PurchaseOrderCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// SetNillableTotal sets the "total" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableTotal(v *decimal.Decimal) *PurchaseOrderCreate {
	if v != nil {
		_c.SetTotal(*v)
	}
	return _c
}

// SetCurrencyCode sets the "currency_code" field.
func (_c *PurchaseOrderCreate) SetCurrencyCode(v string) *PurchaseOrderCreate {
	_c.mutation.SetCurrencyCode(v)
	return _c
}

// SetNillableCurrencyCode sets the "currency_code" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableCurrencyCode(v *string) *PurchaseOrderCreate {
	if v != nil {
		_c.SetCurrencyCode(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PurchaseOrderCreate) SetID(v uuid.UUID) *PurchaseOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PurchaseOrderCreate) SetNillableID(v *uuid.UUID) *PurchaseOrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the PurchaseOrderMutation object of the builder.
func (_c *PurchaseOrderCreate) Mutation() *PurchaseOrderMutation {
	return _c.mutation
}

// Save creates the PurchaseOrder in the database.
func (_c *PurchaseOrderCreate) Save(ctx context.Context) (*PurchaseOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PurchaseOrderCreate) SaveX(ctx context.Context) *PurchaseOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PurchaseOrderCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := purchaseorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := purchaseorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := purchaseorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		v := purchaseorder.DefaultSubtotal
		_c.mutation.SetSubtotal(v)
	}
	if _, ok := _c.mutation.Tax(); !ok {
		v := purchaseorder.DefaultTax
		_c.mutation.SetTax(v)
	}
	if _, ok := _c.mutation.Total(); !ok {
		v := purchaseorder.DefaultTotal
		_c.mutation.SetTotal(v)
	}
	if _, ok := _c.mutation.CurrencyCode(); !ok {
		v := purchaseorder.DefaultCurrencyCode
		_c.mutation.SetCurrencyCode(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := purchaseorder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PurchaseOrderCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PurchaseOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PurchaseOrder.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PurchaseOrder.tenant_id"`)}
	}
	if _, ok := _c.mutation.VendorID(); !ok {
		return &ValidationError{Name: "vendor_id", err: errors.New(`ent: missing required field "PurchaseOrder.vendor_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PurchaseOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := purchaseorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PurchaseOrder.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subtotal(); !ok {
		return &ValidationError{Name: "subtotal", err: errors.New(`ent: missing required field "PurchaseOrder.subtotal"`)}
	}
	if _, ok := _c.mutation.Tax(); !ok {
		return &ValidationError{Name: "tax", err: errors.New(`ent: missing required field "PurchaseOrder.tax"`)}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "PurchaseOrder.total"`)}
	}
	if _, ok := _c.mutation.CurrencyCode(); !ok {
		return &ValidationError{Name: "currency_code", err: errors.New(`ent: missing required field "PurchaseOrder.currency_code"`)}
	}
	return nil
}

func (_c *PurchaseOrderCreate) sqlSave(ctx context.Context) (*PurchaseOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PurchaseOrderCreate) createSpec() (*PurchaseOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PurchaseOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(purchaseorder.Table, sqlgraph.NewFieldSpec(purchaseorder.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(purchaseorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(purchaseorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(purchaseorder.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.PoNumber(); ok {
		_spec.SetField(purchaseorder.FieldPoNumber, field.TypeString, value)
		_node.PoNumber = value
	}
	if value, ok := _c.mutation.VendorID(); ok {
		_spec.SetField(purchaseorder.FieldVendorID, field.TypeUUID, value)
		_node.VendorID = value
	}
	if value, ok := _c.mutation.FundID(); ok {
		_spec.SetField(purchaseorder.FieldFundID, field.TypeUUID, value)
		_node.FundID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(purchaseorder.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.OrderDate(); ok {
		_spec.SetField(purchaseorder.FieldOrderDate, field.TypeTime, value)
		_node.OrderDate = &value
	}
	if value, ok := _c.mutation.ExpectedDate(); ok {
		_spec.SetField(purchaseorder.FieldExpectedDate, field.TypeTime, value)
		_node.ExpectedDate = &value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(purchaseorder.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Subtotal(); ok {
		_spec.SetField(purchaseorder.FieldSubtotal, field.TypeOther, value)
		_node.Subtotal = value
	}
	if value, ok := _c.mutation.Tax(); ok {
		_spec.SetField(purchaseorder.FieldTax, field.TypeOther, value)
		_node.Tax = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(purchaseorder.FieldTotal, field.TypeOther, value)
		_node.Total = value
	}
	if value, ok := _c.mutation.CurrencyCode(); ok {
		_spec.SetField(purchaseorder.FieldCurrencyCode, field.TypeString, value)
		_node.CurrencyCode = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseOrder.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseOrderCreate) OnConflict(opts ...sql.ConflictOption) *PurchaseOrderUpsertOne {
	_c.conflict = opts
	return &PurchaseOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseOrderCreate) OnConflictColumns(columns ...string) *PurchaseOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseOrderUpsertOne{
		create: _c,
	}
}

type (
	// PurchaseOrderUpsertOne is the builder for "upsert"-ing
	//  one PurchaseOrder node.
	PurchaseOrderUpsertOne struct {
		create *PurchaseOrderCreate
	}

	// PurchaseOrderUpsert is the "OnConflict" setter.
	PurchaseOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsert) SetUpdatedAt(v time.Time) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateUpdatedAt() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldUpdatedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *PurchaseOrderUpsert) SetTenantID(v uuid.UUID) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateTenantID() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldTenantID)
	return u
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsert) SetPoNumber(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldPoNumber, v)
	return u
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdatePoNumber() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldPoNumber)
	return u
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsert) ClearPoNumber() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldPoNumber)
	return u
}

// SetVendorID sets the "vendor_id" field.
func (u *PurchaseOrderUpsert) SetVendorID(v uuid.UUID) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldVendorID, v)
	return u
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateVendorID() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldVendorID)
	return u
}

// SetFundID sets the "fund_id" field.
func (u *PurchaseOrderUpsert) SetFundID(v uuid.UUID) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldFundID, v)
	return u
}

// UpdateFundID sets the "fund_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateFundID() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldFundID)
	return u
}

// ClearFundID clears the value of the "fund_id" field.
func (u *PurchaseOrderUpsert) ClearFundID() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldFundID)
	return u
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsert) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateStatus() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldStatus)
	return u
}

// SetOrderDate sets the "order_date" field.
func (u *PurchaseOrderUpsert) SetOrderDate(v time.Time) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldOrderDate, v)
	return u
}

// UpdateOrderDate sets the "order_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateOrderDate() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldOrderDate)
	return u
}

// ClearOrderDate clears the value of the "order_date" field.
func (u *PurchaseOrderUpsert) ClearOrderDate() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldOrderDate)
	return u
}

// SetExpectedDate sets the "expected_date" field.
func (u *PurchaseOrderUpsert) SetExpectedDate(v time.Time) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldExpectedDate, v)
	return u
}

// UpdateExpectedDate sets the "expected_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateExpectedDate() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldExpectedDate)
	return u
}

// ClearExpectedDate clears the value of the "expected_date" field.
func (u *PurchaseOrderUpsert) ClearExpectedDate() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldExpectedDate)
	return u
}

// SetNotes sets the "notes" field.
func (u *PurchaseOrderUpsert) SetNotes(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateNotes() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseOrderUpsert) ClearNotes() *PurchaseOrderUpsert {
	u.SetNull(purchaseorder.FieldNotes)
	return u
}

// SetSubtotal sets the "subtotal" field.
func (u *PurchaseOrderUpsert) SetSubtotal(v decimal.Decimal) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldSubtotal, v)
	return u
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateSubtotal() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldSubtotal)
	return u
}

// SetTax sets the "tax" field.
func (u *PurchaseOrderUpsert) SetTax(v decimal.Decimal) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldTax, v)
	return u
}

// UpdateTax sets the "tax" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateTax() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldTax)
	return u
}

// SetTotal sets the "total" field.
func (u *PurchaseOrderUpsert) SetTotal(v decimal.Decimal) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldTotal, v)
	return u
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateTotal() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldTotal)
	return u
}

// SetCurrencyCode sets the "currency_code" field.
func (u *PurchaseOrderUpsert) SetCurrencyCode(v string) *PurchaseOrderUpsert {
	u.Set(purchaseorder.FieldCurrencyCode, v)
	return u
}

// UpdateCurrencyCode sets the "currency_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsert) UpdateCurrencyCode() *PurchaseOrderUpsert {
	u.SetExcluded(purchaseorder.FieldCurrencyCode)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(purchaseorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PurchaseOrderUpsertOne) UpdateNewValues() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(purchaseorder.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(purchaseorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PurchaseOrderUpsertOne) Ignore() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseOrderUpsertOne) DoNothing() *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseOrderCreate.OnConflict
// documentation for more info.
func (u *PurchaseOrderUpsertOne) Update(set func(*PurchaseOrderUpsert)) *PurchaseOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsertOne) SetUpdatedAt(v time.Time) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateUpdatedAt() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *PurchaseOrderUpsertOne) SetTenantID(v uuid.UUID) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateTenantID() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTenantID()
	})
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsertOne) SetPoNumber(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetPoNumber(v)
	})
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdatePoNumber() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdatePoNumber()
	})
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsertOne) ClearPoNumber() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearPoNumber()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *PurchaseOrderUpsertOne) SetVendorID(v uuid.UUID) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateVendorID() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateVendorID()
	})
}

// SetFundID sets the "fund_id" field.
func (u *PurchaseOrderUpsertOne) SetFundID(v uuid.UUID) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetFundID(v)
	})
}

// UpdateFundID sets the "fund_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateFundID() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateFundID()
	})
}

// ClearFundID clears the value of the "fund_id" field.
func (u *PurchaseOrderUpsertOne) ClearFundID() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearFundID()
	})
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsertOne) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateStatus() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderDate sets the "order_date" field.
func (u *PurchaseOrderUpsertOne) SetOrderDate(v time.Time) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetOrderDate(v)
	})
}

// UpdateOrderDate sets the "order_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateOrderDate() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateOrderDate()
	})
}

// ClearOrderDate clears the value of the "order_date" field.
func (u *PurchaseOrderUpsertOne) ClearOrderDate() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearOrderDate()
	})
}

// SetExpectedDate sets the "expected_date" field.
func (u *PurchaseOrderUpsertOne) SetExpectedDate(v time.Time) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetExpectedDate(v)
	})
}

// UpdateExpectedDate sets the "expected_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateExpectedDate() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateExpectedDate()
	})
}

// ClearExpectedDate clears the value of the "expected_date" field.
func (u *PurchaseOrderUpsertOne) ClearExpectedDate() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearExpectedDate()
	})
}

// SetNotes sets the "notes" field.
func (u *PurchaseOrderUpsertOne) SetNotes(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateNotes() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseOrderUpsertOne) ClearNotes() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearNotes()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *PurchaseOrderUpsertOne) SetSubtotal(v decimal.Decimal) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateSubtotal() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTax sets the "tax" field.
func (u *PurchaseOrderUpsertOne) SetTax(v decimal.Decimal) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTax(v)
	})
}

// UpdateTax sets the "tax" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateTax() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTax()
	})
}

// SetTotal sets the "total" field.
func (u *PurchaseOrderUpsertOne) SetTotal(v decimal.Decimal) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateTotal() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTotal()
	})
}

// SetCurrencyCode sets the "currency_code" field.
func (u *PurchaseOrderUpsertOne) SetCurrencyCode(v string) *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetCurrencyCode(v)
	})
}

// UpdateCurrencyCode sets the "currency_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsertOne) UpdateCurrencyCode() *PurchaseOrderUpsertOne {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateCurrencyCode()
	})
}

// Exec executes the query.
func (u *PurchaseOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PurchaseOrderUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PurchaseOrderUpsertOne.ID is not supported by MySQL driver. Use PurchaseOrderUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PurchaseOrderUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PurchaseOrderCreateBulk is the builder for creating many PurchaseOrder entities in bulk.
type PurchaseOrderCreateBulk struct {
	config
	err      error
	builders []*PurchaseOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PurchaseOrder entities in the database.
func (_c *PurchaseOrderCreateBulk) Save(ctx context.Context) ([]*PurchaseOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PurchaseOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PurchaseOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PurchaseOrderCreateBulk) SaveX(ctx context.Context) []*PurchaseOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PurchaseOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PurchaseOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PurchaseOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PurchaseOrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PurchaseOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PurchaseOrderUpsertBulk {
	_c.conflict = opts
	return &PurchaseOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PurchaseOrderCreateBulk) OnConflictColumns(columns ...string) *PurchaseOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PurchaseOrderUpsertBulk{
		create: _c,
	}
}

// PurchaseOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PurchaseOrder nodes.
type PurchaseOrderUpsertBulk struct {
	create *PurchaseOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(purchaseorder.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PurchaseOrderUpsertBulk) UpdateNewValues() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(purchaseorder.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(purchaseorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PurchaseOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PurchaseOrderUpsertBulk) Ignore() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PurchaseOrderUpsertBulk) DoNothing() *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PurchaseOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PurchaseOrderUpsertBulk) Update(set func(*PurchaseOrderUpsert)) *PurchaseOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PurchaseOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PurchaseOrderUpsertBulk) SetUpdatedAt(v time.Time) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateUpdatedAt() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *PurchaseOrderUpsertBulk) SetTenantID(v uuid.UUID) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateTenantID() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTenantID()
	})
}

// SetPoNumber sets the "po_number" field.
func (u *PurchaseOrderUpsertBulk) SetPoNumber(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetPoNumber(v)
	})
}

// UpdatePoNumber sets the "po_number" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdatePoNumber() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdatePoNumber()
	})
}

// ClearPoNumber clears the value of the "po_number" field.
func (u *PurchaseOrderUpsertBulk) ClearPoNumber() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearPoNumber()
	})
}

// SetVendorID sets the "vendor_id" field.
func (u *PurchaseOrderUpsertBulk) SetVendorID(v uuid.UUID) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetVendorID(v)
	})
}

// UpdateVendorID sets the "vendor_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateVendorID() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateVendorID()
	})
}

// SetFundID sets the "fund_id" field.
func (u *PurchaseOrderUpsertBulk) SetFundID(v uuid.UUID) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetFundID(v)
	})
}

// UpdateFundID sets the "fund_id" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateFundID() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateFundID()
	})
}

// ClearFundID clears the value of the "fund_id" field.
func (u *PurchaseOrderUpsertBulk) ClearFundID() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearFundID()
	})
}

// SetStatus sets the "status" field.
func (u *PurchaseOrderUpsertBulk) SetStatus(v purchaseorder.Status) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateStatus() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetOrderDate sets the "order_date" field.
func (u *PurchaseOrderUpsertBulk) SetOrderDate(v time.Time) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetOrderDate(v)
	})
}

// UpdateOrderDate sets the "order_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateOrderDate() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateOrderDate()
	})
}

// ClearOrderDate clears the value of the "order_date" field.
func (u *PurchaseOrderUpsertBulk) ClearOrderDate() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearOrderDate()
	})
}

// SetExpectedDate sets the "expected_date" field.
func (u *PurchaseOrderUpsertBulk) SetExpectedDate(v time.Time) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetExpectedDate(v)
	})
}

// UpdateExpectedDate sets the "expected_date" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateExpectedDate() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateExpectedDate()
	})
}

// ClearExpectedDate clears the value of the "expected_date" field.
func (u *PurchaseOrderUpsertBulk) ClearExpectedDate() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearExpectedDate()
	})
}

// SetNotes sets the "notes" field.
func (u *PurchaseOrderUpsertBulk) SetNotes(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateNotes() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PurchaseOrderUpsertBulk) ClearNotes() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.ClearNotes()
	})
}

// SetSubtotal sets the "subtotal" field.
func (u *PurchaseOrderUpsertBulk) SetSubtotal(v decimal.Decimal) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetSubtotal(v)
	})
}

// UpdateSubtotal sets the "subtotal" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateSubtotal() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateSubtotal()
	})
}

// SetTax sets the "tax" field.
func (u *PurchaseOrderUpsertBulk) SetTax(v decimal.Decimal) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTax(v)
	})
}

// UpdateTax sets the "tax" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateTax() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTax()
	})
}

// SetTotal sets the "total" field.
func (u *PurchaseOrderUpsertBulk) SetTotal(v decimal.Decimal) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetTotal(v)
	})
}

// UpdateTotal sets the "total" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateTotal() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateTotal()
	})
}

// SetCurrencyCode sets the "currency_code" field.
func (u *PurchaseOrderUpsertBulk) SetCurrencyCode(v string) *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.SetCurrencyCode(v)
	})
}

// UpdateCurrencyCode sets the "currency_code" field to the value that was provided on create.
func (u *PurchaseOrderUpsertBulk) UpdateCurrencyCode() *PurchaseOrderUpsertBulk {
	return u.Update(func(s *PurchaseOrderUpsert) {
		s.UpdateCurrencyCode()
	})
}

// Exec executes the query.
func (u *PurchaseOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PurchaseOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PurchaseOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PurchaseOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
