// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/bengobox/library-service/internal/ent/auditlog"
	"github.com/bengobox/library-service/internal/ent/author"
	"github.com/bengobox/library-service/internal/ent/bibrecord"
	"github.com/bengobox/library-service/internal/ent/bookcopy"
	"github.com/bengobox/library-service/internal/ent/branch"
	"github.com/bengobox/library-service/internal/ent/collection"
	"github.com/bengobox/library-service/internal/ent/copytransfer"
	"github.com/bengobox/library-service/internal/ent/documentsequence"
	"github.com/bengobox/library-service/internal/ent/ebook"
	"github.com/bengobox/library-service/internal/ent/ebookloan"
	"github.com/bengobox/library-service/internal/ent/ebookpurchase"
	"github.com/bengobox/library-service/internal/ent/fine"
	"github.com/bengobox/library-service/internal/ent/hold"
	"github.com/bengobox/library-service/internal/ent/libraryrole"
	"github.com/bengobox/library-service/internal/ent/libraryuser"
	"github.com/bengobox/library-service/internal/ent/loan"
	"github.com/bengobox/library-service/internal/ent/loanpolicy"
	"github.com/bengobox/library-service/internal/ent/member"
	"github.com/bengobox/library-service/internal/ent/membershipfee"
	"github.com/bengobox/library-service/internal/ent/membertier"
	"github.com/bengobox/library-service/internal/ent/outboxevent"
	"github.com/bengobox/library-service/internal/ent/publisher"
	"github.com/bengobox/library-service/internal/ent/schema"
	"github.com/bengobox/library-service/internal/ent/serviceconfig"
	"github.com/bengobox/library-service/internal/ent/stockcount"
	"github.com/bengobox/library-service/internal/ent/subject"
	"github.com/bengobox/library-service/internal/ent/tenant"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescCreatedAt is the schema descriptor for created_at field.
	auditlogDescCreatedAt := auditlogMixinFields0[1].Descriptor()
	// auditlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditlog.DefaultCreatedAt = auditlogDescCreatedAt.Default.(func() time.Time)
	// auditlogDescUpdatedAt is the schema descriptor for updated_at field.
	auditlogDescUpdatedAt := auditlogMixinFields0[2].Descriptor()
	// auditlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	auditlog.DefaultUpdatedAt = auditlogDescUpdatedAt.Default.(func() time.Time)
	// auditlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	auditlog.UpdateDefaultUpdatedAt = auditlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	// auditlogDescAggregateType is the schema descriptor for aggregate_type field.
	auditlogDescAggregateType := auditlogFields[1].Descriptor()
	// auditlog.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	auditlog.AggregateTypeValidator = auditlogDescAggregateType.Validators[0].(func(string) error)
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[3].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = auditlogDescAction.Validators[0].(func(string) error)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogMixinFields0[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	authorMixin := schema.Author{}.Mixin()
	authorMixinFields0 := authorMixin[0].Fields()
	_ = authorMixinFields0
	authorFields := schema.Author{}.Fields()
	_ = authorFields
	// authorDescCreatedAt is the schema descriptor for created_at field.
	authorDescCreatedAt := authorMixinFields0[1].Descriptor()
	// author.DefaultCreatedAt holds the default value on creation for the created_at field.
	author.DefaultCreatedAt = authorDescCreatedAt.Default.(func() time.Time)
	// authorDescUpdatedAt is the schema descriptor for updated_at field.
	authorDescUpdatedAt := authorMixinFields0[2].Descriptor()
	// author.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	author.DefaultUpdatedAt = authorDescUpdatedAt.Default.(func() time.Time)
	// author.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	author.UpdateDefaultUpdatedAt = authorDescUpdatedAt.UpdateDefault.(func() time.Time)
	// authorDescName is the schema descriptor for name field.
	authorDescName := authorFields[0].Descriptor()
	// author.NameValidator is a validator for the "name" field. It is called by the builders before save.
	author.NameValidator = authorDescName.Validators[0].(func(string) error)
	// authorDescID is the schema descriptor for id field.
	authorDescID := authorMixinFields0[0].Descriptor()
	// author.DefaultID holds the default value on creation for the id field.
	author.DefaultID = authorDescID.Default.(func() uuid.UUID)
	bibrecordMixin := schema.BibRecord{}.Mixin()
	bibrecordMixinFields0 := bibrecordMixin[0].Fields()
	_ = bibrecordMixinFields0
	bibrecordFields := schema.BibRecord{}.Fields()
	_ = bibrecordFields
	// bibrecordDescCreatedAt is the schema descriptor for created_at field.
	bibrecordDescCreatedAt := bibrecordMixinFields0[1].Descriptor()
	// bibrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	bibrecord.DefaultCreatedAt = bibrecordDescCreatedAt.Default.(func() time.Time)
	// bibrecordDescUpdatedAt is the schema descriptor for updated_at field.
	bibrecordDescUpdatedAt := bibrecordMixinFields0[2].Descriptor()
	// bibrecord.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bibrecord.DefaultUpdatedAt = bibrecordDescUpdatedAt.Default.(func() time.Time)
	// bibrecord.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bibrecord.UpdateDefaultUpdatedAt = bibrecordDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bibrecordDescTitle is the schema descriptor for title field.
	bibrecordDescTitle := bibrecordFields[0].Descriptor()
	// bibrecord.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	bibrecord.TitleValidator = bibrecordDescTitle.Validators[0].(func(string) error)
	// bibrecordDescLanguage is the schema descriptor for language field.
	bibrecordDescLanguage := bibrecordFields[7].Descriptor()
	// bibrecord.DefaultLanguage holds the default value on creation for the language field.
	bibrecord.DefaultLanguage = bibrecordDescLanguage.Default.(string)
	// bibrecordDescID is the schema descriptor for id field.
	bibrecordDescID := bibrecordMixinFields0[0].Descriptor()
	// bibrecord.DefaultID holds the default value on creation for the id field.
	bibrecord.DefaultID = bibrecordDescID.Default.(func() uuid.UUID)
	bookcopyMixin := schema.BookCopy{}.Mixin()
	bookcopyMixinFields0 := bookcopyMixin[0].Fields()
	_ = bookcopyMixinFields0
	bookcopyFields := schema.BookCopy{}.Fields()
	_ = bookcopyFields
	// bookcopyDescCreatedAt is the schema descriptor for created_at field.
	bookcopyDescCreatedAt := bookcopyMixinFields0[1].Descriptor()
	// bookcopy.DefaultCreatedAt holds the default value on creation for the created_at field.
	bookcopy.DefaultCreatedAt = bookcopyDescCreatedAt.Default.(func() time.Time)
	// bookcopyDescUpdatedAt is the schema descriptor for updated_at field.
	bookcopyDescUpdatedAt := bookcopyMixinFields0[2].Descriptor()
	// bookcopy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	bookcopy.DefaultUpdatedAt = bookcopyDescUpdatedAt.Default.(func() time.Time)
	// bookcopy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	bookcopy.UpdateDefaultUpdatedAt = bookcopyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// bookcopyDescBarcode is the schema descriptor for barcode field.
	bookcopyDescBarcode := bookcopyFields[2].Descriptor()
	// bookcopy.BarcodeValidator is a validator for the "barcode" field. It is called by the builders before save.
	bookcopy.BarcodeValidator = bookcopyDescBarcode.Validators[0].(func(string) error)
	// bookcopyDescCondition is the schema descriptor for condition field.
	bookcopyDescCondition := bookcopyFields[7].Descriptor()
	// bookcopy.DefaultCondition holds the default value on creation for the condition field.
	bookcopy.DefaultCondition = bookcopyDescCondition.Default.(string)
	// bookcopyDescIsReferenceOnly is the schema descriptor for is_reference_only field.
	bookcopyDescIsReferenceOnly := bookcopyFields[8].Descriptor()
	// bookcopy.DefaultIsReferenceOnly holds the default value on creation for the is_reference_only field.
	bookcopy.DefaultIsReferenceOnly = bookcopyDescIsReferenceOnly.Default.(bool)
	// bookcopyDescID is the schema descriptor for id field.
	bookcopyDescID := bookcopyMixinFields0[0].Descriptor()
	// bookcopy.DefaultID holds the default value on creation for the id field.
	bookcopy.DefaultID = bookcopyDescID.Default.(func() uuid.UUID)
	branchMixin := schema.Branch{}.Mixin()
	branchMixinFields0 := branchMixin[0].Fields()
	_ = branchMixinFields0
	branchFields := schema.Branch{}.Fields()
	_ = branchFields
	// branchDescCreatedAt is the schema descriptor for created_at field.
	branchDescCreatedAt := branchMixinFields0[1].Descriptor()
	// branch.DefaultCreatedAt holds the default value on creation for the created_at field.
	branch.DefaultCreatedAt = branchDescCreatedAt.Default.(func() time.Time)
	// branchDescUpdatedAt is the schema descriptor for updated_at field.
	branchDescUpdatedAt := branchMixinFields0[2].Descriptor()
	// branch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	branch.DefaultUpdatedAt = branchDescUpdatedAt.Default.(func() time.Time)
	// branch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	branch.UpdateDefaultUpdatedAt = branchDescUpdatedAt.UpdateDefault.(func() time.Time)
	// branchDescName is the schema descriptor for name field.
	branchDescName := branchFields[0].Descriptor()
	// branch.NameValidator is a validator for the "name" field. It is called by the builders before save.
	branch.NameValidator = branchDescName.Validators[0].(func(string) error)
	// branchDescCode is the schema descriptor for code field.
	branchDescCode := branchFields[1].Descriptor()
	// branch.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	branch.CodeValidator = branchDescCode.Validators[0].(func(string) error)
	// branchDescIsDefault is the schema descriptor for is_default field.
	branchDescIsDefault := branchFields[7].Descriptor()
	// branch.DefaultIsDefault holds the default value on creation for the is_default field.
	branch.DefaultIsDefault = branchDescIsDefault.Default.(bool)
	// branchDescIsActive is the schema descriptor for is_active field.
	branchDescIsActive := branchFields[8].Descriptor()
	// branch.DefaultIsActive holds the default value on creation for the is_active field.
	branch.DefaultIsActive = branchDescIsActive.Default.(bool)
	// branchDescID is the schema descriptor for id field.
	branchDescID := branchMixinFields0[0].Descriptor()
	// branch.DefaultID holds the default value on creation for the id field.
	branch.DefaultID = branchDescID.Default.(func() uuid.UUID)
	collectionMixin := schema.Collection{}.Mixin()
	collectionMixinFields0 := collectionMixin[0].Fields()
	_ = collectionMixinFields0
	collectionFields := schema.Collection{}.Fields()
	_ = collectionFields
	// collectionDescCreatedAt is the schema descriptor for created_at field.
	collectionDescCreatedAt := collectionMixinFields0[1].Descriptor()
	// collection.DefaultCreatedAt holds the default value on creation for the created_at field.
	collection.DefaultCreatedAt = collectionDescCreatedAt.Default.(func() time.Time)
	// collectionDescUpdatedAt is the schema descriptor for updated_at field.
	collectionDescUpdatedAt := collectionMixinFields0[2].Descriptor()
	// collection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	collection.DefaultUpdatedAt = collectionDescUpdatedAt.Default.(func() time.Time)
	// collection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	collection.UpdateDefaultUpdatedAt = collectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// collectionDescName is the schema descriptor for name field.
	collectionDescName := collectionFields[0].Descriptor()
	// collection.NameValidator is a validator for the "name" field. It is called by the builders before save.
	collection.NameValidator = collectionDescName.Validators[0].(func(string) error)
	// collectionDescIsReferenceOnly is the schema descriptor for is_reference_only field.
	collectionDescIsReferenceOnly := collectionFields[3].Descriptor()
	// collection.DefaultIsReferenceOnly holds the default value on creation for the is_reference_only field.
	collection.DefaultIsReferenceOnly = collectionDescIsReferenceOnly.Default.(bool)
	// collectionDescID is the schema descriptor for id field.
	collectionDescID := collectionMixinFields0[0].Descriptor()
	// collection.DefaultID holds the default value on creation for the id field.
	collection.DefaultID = collectionDescID.Default.(func() uuid.UUID)
	copytransferMixin := schema.CopyTransfer{}.Mixin()
	copytransferMixinFields0 := copytransferMixin[0].Fields()
	_ = copytransferMixinFields0
	copytransferFields := schema.CopyTransfer{}.Fields()
	_ = copytransferFields
	// copytransferDescCreatedAt is the schema descriptor for created_at field.
	copytransferDescCreatedAt := copytransferMixinFields0[1].Descriptor()
	// copytransfer.DefaultCreatedAt holds the default value on creation for the created_at field.
	copytransfer.DefaultCreatedAt = copytransferDescCreatedAt.Default.(func() time.Time)
	// copytransferDescUpdatedAt is the schema descriptor for updated_at field.
	copytransferDescUpdatedAt := copytransferMixinFields0[2].Descriptor()
	// copytransfer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	copytransfer.DefaultUpdatedAt = copytransferDescUpdatedAt.Default.(func() time.Time)
	// copytransfer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	copytransfer.UpdateDefaultUpdatedAt = copytransferDescUpdatedAt.UpdateDefault.(func() time.Time)
	// copytransferDescID is the schema descriptor for id field.
	copytransferDescID := copytransferMixinFields0[0].Descriptor()
	// copytransfer.DefaultID holds the default value on creation for the id field.
	copytransfer.DefaultID = copytransferDescID.Default.(func() uuid.UUID)
	documentsequenceMixin := schema.DocumentSequence{}.Mixin()
	documentsequenceMixinFields0 := documentsequenceMixin[0].Fields()
	_ = documentsequenceMixinFields0
	documentsequenceFields := schema.DocumentSequence{}.Fields()
	_ = documentsequenceFields
	// documentsequenceDescCreatedAt is the schema descriptor for created_at field.
	documentsequenceDescCreatedAt := documentsequenceMixinFields0[1].Descriptor()
	// documentsequence.DefaultCreatedAt holds the default value on creation for the created_at field.
	documentsequence.DefaultCreatedAt = documentsequenceDescCreatedAt.Default.(func() time.Time)
	// documentsequenceDescUpdatedAt is the schema descriptor for updated_at field.
	documentsequenceDescUpdatedAt := documentsequenceMixinFields0[2].Descriptor()
	// documentsequence.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	documentsequence.DefaultUpdatedAt = documentsequenceDescUpdatedAt.Default.(func() time.Time)
	// documentsequence.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	documentsequence.UpdateDefaultUpdatedAt = documentsequenceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// documentsequenceDescKind is the schema descriptor for kind field.
	documentsequenceDescKind := documentsequenceFields[0].Descriptor()
	// documentsequence.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	documentsequence.KindValidator = documentsequenceDescKind.Validators[0].(func(string) error)
	// documentsequenceDescNextValue is the schema descriptor for next_value field.
	documentsequenceDescNextValue := documentsequenceFields[2].Descriptor()
	// documentsequence.DefaultNextValue holds the default value on creation for the next_value field.
	documentsequence.DefaultNextValue = documentsequenceDescNextValue.Default.(int64)
	// documentsequenceDescPadWidth is the schema descriptor for pad_width field.
	documentsequenceDescPadWidth := documentsequenceFields[3].Descriptor()
	// documentsequence.DefaultPadWidth holds the default value on creation for the pad_width field.
	documentsequence.DefaultPadWidth = documentsequenceDescPadWidth.Default.(int)
	// documentsequenceDescID is the schema descriptor for id field.
	documentsequenceDescID := documentsequenceMixinFields0[0].Descriptor()
	// documentsequence.DefaultID holds the default value on creation for the id field.
	documentsequence.DefaultID = documentsequenceDescID.Default.(func() uuid.UUID)
	ebookMixin := schema.Ebook{}.Mixin()
	ebookMixinFields0 := ebookMixin[0].Fields()
	_ = ebookMixinFields0
	ebookFields := schema.Ebook{}.Fields()
	_ = ebookFields
	// ebookDescCreatedAt is the schema descriptor for created_at field.
	ebookDescCreatedAt := ebookMixinFields0[1].Descriptor()
	// ebook.DefaultCreatedAt holds the default value on creation for the created_at field.
	ebook.DefaultCreatedAt = ebookDescCreatedAt.Default.(func() time.Time)
	// ebookDescUpdatedAt is the schema descriptor for updated_at field.
	ebookDescUpdatedAt := ebookMixinFields0[2].Descriptor()
	// ebook.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ebook.DefaultUpdatedAt = ebookDescUpdatedAt.Default.(func() time.Time)
	// ebook.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ebook.UpdateDefaultUpdatedAt = ebookDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ebookDescFileURL is the schema descriptor for file_url field.
	ebookDescFileURL := ebookFields[1].Descriptor()
	// ebook.FileURLValidator is a validator for the "file_url" field. It is called by the builders before save.
	ebook.FileURLValidator = ebookDescFileURL.Validators[0].(func(string) error)
	// ebookDescMaxConcurrentLoans is the schema descriptor for max_concurrent_loans field.
	ebookDescMaxConcurrentLoans := ebookFields[5].Descriptor()
	// ebook.DefaultMaxConcurrentLoans holds the default value on creation for the max_concurrent_loans field.
	ebook.DefaultMaxConcurrentLoans = ebookDescMaxConcurrentLoans.Default.(int)
	// ebookDescLoanDurationDays is the schema descriptor for loan_duration_days field.
	ebookDescLoanDurationDays := ebookFields[6].Descriptor()
	// ebook.DefaultLoanDurationDays holds the default value on creation for the loan_duration_days field.
	ebook.DefaultLoanDurationDays = ebookDescLoanDurationDays.Default.(int)
	// ebookDescIsPurchasable is the schema descriptor for is_purchasable field.
	ebookDescIsPurchasable := ebookFields[7].Descriptor()
	// ebook.DefaultIsPurchasable holds the default value on creation for the is_purchasable field.
	ebook.DefaultIsPurchasable = ebookDescIsPurchasable.Default.(bool)
	// ebookDescPrice is the schema descriptor for price field.
	ebookDescPrice := ebookFields[8].Descriptor()
	// ebook.DefaultPrice holds the default value on creation for the price field.
	ebook.DefaultPrice = ebookDescPrice.Default.(decimal.Decimal)
	// ebookDescID is the schema descriptor for id field.
	ebookDescID := ebookMixinFields0[0].Descriptor()
	// ebook.DefaultID holds the default value on creation for the id field.
	ebook.DefaultID = ebookDescID.Default.(func() uuid.UUID)
	ebookloanMixin := schema.EbookLoan{}.Mixin()
	ebookloanMixinFields0 := ebookloanMixin[0].Fields()
	_ = ebookloanMixinFields0
	ebookloanFields := schema.EbookLoan{}.Fields()
	_ = ebookloanFields
	// ebookloanDescCreatedAt is the schema descriptor for created_at field.
	ebookloanDescCreatedAt := ebookloanMixinFields0[1].Descriptor()
	// ebookloan.DefaultCreatedAt holds the default value on creation for the created_at field.
	ebookloan.DefaultCreatedAt = ebookloanDescCreatedAt.Default.(func() time.Time)
	// ebookloanDescUpdatedAt is the schema descriptor for updated_at field.
	ebookloanDescUpdatedAt := ebookloanMixinFields0[2].Descriptor()
	// ebookloan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ebookloan.DefaultUpdatedAt = ebookloanDescUpdatedAt.Default.(func() time.Time)
	// ebookloan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ebookloan.UpdateDefaultUpdatedAt = ebookloanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ebookloanDescID is the schema descriptor for id field.
	ebookloanDescID := ebookloanMixinFields0[0].Descriptor()
	// ebookloan.DefaultID holds the default value on creation for the id field.
	ebookloan.DefaultID = ebookloanDescID.Default.(func() uuid.UUID)
	ebookpurchaseMixin := schema.EbookPurchase{}.Mixin()
	ebookpurchaseMixinFields0 := ebookpurchaseMixin[0].Fields()
	_ = ebookpurchaseMixinFields0
	ebookpurchaseFields := schema.EbookPurchase{}.Fields()
	_ = ebookpurchaseFields
	// ebookpurchaseDescCreatedAt is the schema descriptor for created_at field.
	ebookpurchaseDescCreatedAt := ebookpurchaseMixinFields0[1].Descriptor()
	// ebookpurchase.DefaultCreatedAt holds the default value on creation for the created_at field.
	ebookpurchase.DefaultCreatedAt = ebookpurchaseDescCreatedAt.Default.(func() time.Time)
	// ebookpurchaseDescUpdatedAt is the schema descriptor for updated_at field.
	ebookpurchaseDescUpdatedAt := ebookpurchaseMixinFields0[2].Descriptor()
	// ebookpurchase.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ebookpurchase.DefaultUpdatedAt = ebookpurchaseDescUpdatedAt.Default.(func() time.Time)
	// ebookpurchase.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ebookpurchase.UpdateDefaultUpdatedAt = ebookpurchaseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ebookpurchaseDescAmount is the schema descriptor for amount field.
	ebookpurchaseDescAmount := ebookpurchaseFields[3].Descriptor()
	// ebookpurchase.DefaultAmount holds the default value on creation for the amount field.
	ebookpurchase.DefaultAmount = ebookpurchaseDescAmount.Default.(decimal.Decimal)
	// ebookpurchaseDescDownloadCount is the schema descriptor for download_count field.
	ebookpurchaseDescDownloadCount := ebookpurchaseFields[6].Descriptor()
	// ebookpurchase.DefaultDownloadCount holds the default value on creation for the download_count field.
	ebookpurchase.DefaultDownloadCount = ebookpurchaseDescDownloadCount.Default.(int)
	// ebookpurchaseDescID is the schema descriptor for id field.
	ebookpurchaseDescID := ebookpurchaseMixinFields0[0].Descriptor()
	// ebookpurchase.DefaultID holds the default value on creation for the id field.
	ebookpurchase.DefaultID = ebookpurchaseDescID.Default.(func() uuid.UUID)
	fineMixin := schema.Fine{}.Mixin()
	fineMixinFields0 := fineMixin[0].Fields()
	_ = fineMixinFields0
	fineFields := schema.Fine{}.Fields()
	_ = fineFields
	// fineDescCreatedAt is the schema descriptor for created_at field.
	fineDescCreatedAt := fineMixinFields0[1].Descriptor()
	// fine.DefaultCreatedAt holds the default value on creation for the created_at field.
	fine.DefaultCreatedAt = fineDescCreatedAt.Default.(func() time.Time)
	// fineDescUpdatedAt is the schema descriptor for updated_at field.
	fineDescUpdatedAt := fineMixinFields0[2].Descriptor()
	// fine.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	fine.DefaultUpdatedAt = fineDescUpdatedAt.Default.(func() time.Time)
	// fine.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	fine.UpdateDefaultUpdatedAt = fineDescUpdatedAt.UpdateDefault.(func() time.Time)
	// fineDescAmount is the schema descriptor for amount field.
	fineDescAmount := fineFields[4].Descriptor()
	// fine.DefaultAmount holds the default value on creation for the amount field.
	fine.DefaultAmount = fineDescAmount.Default.(decimal.Decimal)
	// fineDescAmountPaid is the schema descriptor for amount_paid field.
	fineDescAmountPaid := fineFields[5].Descriptor()
	// fine.DefaultAmountPaid holds the default value on creation for the amount_paid field.
	fine.DefaultAmountPaid = fineDescAmountPaid.Default.(decimal.Decimal)
	// fineDescID is the schema descriptor for id field.
	fineDescID := fineMixinFields0[0].Descriptor()
	// fine.DefaultID holds the default value on creation for the id field.
	fine.DefaultID = fineDescID.Default.(func() uuid.UUID)
	holdMixin := schema.Hold{}.Mixin()
	holdMixinFields0 := holdMixin[0].Fields()
	_ = holdMixinFields0
	holdFields := schema.Hold{}.Fields()
	_ = holdFields
	// holdDescCreatedAt is the schema descriptor for created_at field.
	holdDescCreatedAt := holdMixinFields0[1].Descriptor()
	// hold.DefaultCreatedAt holds the default value on creation for the created_at field.
	hold.DefaultCreatedAt = holdDescCreatedAt.Default.(func() time.Time)
	// holdDescUpdatedAt is the schema descriptor for updated_at field.
	holdDescUpdatedAt := holdMixinFields0[2].Descriptor()
	// hold.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	hold.DefaultUpdatedAt = holdDescUpdatedAt.Default.(func() time.Time)
	// hold.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	hold.UpdateDefaultUpdatedAt = holdDescUpdatedAt.UpdateDefault.(func() time.Time)
	// holdDescQueuePosition is the schema descriptor for queue_position field.
	holdDescQueuePosition := holdFields[4].Descriptor()
	// hold.DefaultQueuePosition holds the default value on creation for the queue_position field.
	hold.DefaultQueuePosition = holdDescQueuePosition.Default.(int)
	// holdDescID is the schema descriptor for id field.
	holdDescID := holdMixinFields0[0].Descriptor()
	// hold.DefaultID holds the default value on creation for the id field.
	hold.DefaultID = holdDescID.Default.(func() uuid.UUID)
	libraryroleMixin := schema.LibraryRole{}.Mixin()
	libraryroleMixinFields0 := libraryroleMixin[0].Fields()
	_ = libraryroleMixinFields0
	libraryroleFields := schema.LibraryRole{}.Fields()
	_ = libraryroleFields
	// libraryroleDescCreatedAt is the schema descriptor for created_at field.
	libraryroleDescCreatedAt := libraryroleMixinFields0[1].Descriptor()
	// libraryrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	libraryrole.DefaultCreatedAt = libraryroleDescCreatedAt.Default.(func() time.Time)
	// libraryroleDescUpdatedAt is the schema descriptor for updated_at field.
	libraryroleDescUpdatedAt := libraryroleMixinFields0[2].Descriptor()
	// libraryrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	libraryrole.DefaultUpdatedAt = libraryroleDescUpdatedAt.Default.(func() time.Time)
	// libraryrole.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	libraryrole.UpdateDefaultUpdatedAt = libraryroleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// libraryroleDescName is the schema descriptor for name field.
	libraryroleDescName := libraryroleFields[0].Descriptor()
	// libraryrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	libraryrole.NameValidator = libraryroleDescName.Validators[0].(func(string) error)
	// libraryroleDescIsSystem is the schema descriptor for is_system field.
	libraryroleDescIsSystem := libraryroleFields[3].Descriptor()
	// libraryrole.DefaultIsSystem holds the default value on creation for the is_system field.
	libraryrole.DefaultIsSystem = libraryroleDescIsSystem.Default.(bool)
	// libraryroleDescID is the schema descriptor for id field.
	libraryroleDescID := libraryroleMixinFields0[0].Descriptor()
	// libraryrole.DefaultID holds the default value on creation for the id field.
	libraryrole.DefaultID = libraryroleDescID.Default.(func() uuid.UUID)
	libraryuserMixin := schema.LibraryUser{}.Mixin()
	libraryuserMixinFields0 := libraryuserMixin[0].Fields()
	_ = libraryuserMixinFields0
	libraryuserFields := schema.LibraryUser{}.Fields()
	_ = libraryuserFields
	// libraryuserDescCreatedAt is the schema descriptor for created_at field.
	libraryuserDescCreatedAt := libraryuserMixinFields0[1].Descriptor()
	// libraryuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	libraryuser.DefaultCreatedAt = libraryuserDescCreatedAt.Default.(func() time.Time)
	// libraryuserDescUpdatedAt is the schema descriptor for updated_at field.
	libraryuserDescUpdatedAt := libraryuserMixinFields0[2].Descriptor()
	// libraryuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	libraryuser.DefaultUpdatedAt = libraryuserDescUpdatedAt.Default.(func() time.Time)
	// libraryuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	libraryuser.UpdateDefaultUpdatedAt = libraryuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	// libraryuserDescUserID is the schema descriptor for user_id field.
	libraryuserDescUserID := libraryuserFields[0].Descriptor()
	// libraryuser.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	libraryuser.UserIDValidator = libraryuserDescUserID.Validators[0].(func(string) error)
	// libraryuserDescIsActive is the schema descriptor for is_active field.
	libraryuserDescIsActive := libraryuserFields[5].Descriptor()
	// libraryuser.DefaultIsActive holds the default value on creation for the is_active field.
	libraryuser.DefaultIsActive = libraryuserDescIsActive.Default.(bool)
	// libraryuserDescPinFailedAttempts is the schema descriptor for pin_failed_attempts field.
	libraryuserDescPinFailedAttempts := libraryuserFields[8].Descriptor()
	// libraryuser.DefaultPinFailedAttempts holds the default value on creation for the pin_failed_attempts field.
	libraryuser.DefaultPinFailedAttempts = libraryuserDescPinFailedAttempts.Default.(int)
	// libraryuserDescID is the schema descriptor for id field.
	libraryuserDescID := libraryuserMixinFields0[0].Descriptor()
	// libraryuser.DefaultID holds the default value on creation for the id field.
	libraryuser.DefaultID = libraryuserDescID.Default.(func() uuid.UUID)
	loanMixin := schema.Loan{}.Mixin()
	loanMixinFields0 := loanMixin[0].Fields()
	_ = loanMixinFields0
	loanFields := schema.Loan{}.Fields()
	_ = loanFields
	// loanDescCreatedAt is the schema descriptor for created_at field.
	loanDescCreatedAt := loanMixinFields0[1].Descriptor()
	// loan.DefaultCreatedAt holds the default value on creation for the created_at field.
	loan.DefaultCreatedAt = loanDescCreatedAt.Default.(func() time.Time)
	// loanDescUpdatedAt is the schema descriptor for updated_at field.
	loanDescUpdatedAt := loanMixinFields0[2].Descriptor()
	// loan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	loan.DefaultUpdatedAt = loanDescUpdatedAt.Default.(func() time.Time)
	// loan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	loan.UpdateDefaultUpdatedAt = loanDescUpdatedAt.UpdateDefault.(func() time.Time)
	// loanDescRenewalsCount is the schema descriptor for renewals_count field.
	loanDescRenewalsCount := loanFields[8].Descriptor()
	// loan.DefaultRenewalsCount holds the default value on creation for the renewals_count field.
	loan.DefaultRenewalsCount = loanDescRenewalsCount.Default.(int)
	// loanDescInHouse is the schema descriptor for in_house field.
	loanDescInHouse := loanFields[10].Descriptor()
	// loan.DefaultInHouse holds the default value on creation for the in_house field.
	loan.DefaultInHouse = loanDescInHouse.Default.(bool)
	// loanDescID is the schema descriptor for id field.
	loanDescID := loanMixinFields0[0].Descriptor()
	// loan.DefaultID holds the default value on creation for the id field.
	loan.DefaultID = loanDescID.Default.(func() uuid.UUID)
	loanpolicyMixin := schema.LoanPolicy{}.Mixin()
	loanpolicyMixinFields0 := loanpolicyMixin[0].Fields()
	_ = loanpolicyMixinFields0
	loanpolicyFields := schema.LoanPolicy{}.Fields()
	_ = loanpolicyFields
	// loanpolicyDescCreatedAt is the schema descriptor for created_at field.
	loanpolicyDescCreatedAt := loanpolicyMixinFields0[1].Descriptor()
	// loanpolicy.DefaultCreatedAt holds the default value on creation for the created_at field.
	loanpolicy.DefaultCreatedAt = loanpolicyDescCreatedAt.Default.(func() time.Time)
	// loanpolicyDescUpdatedAt is the schema descriptor for updated_at field.
	loanpolicyDescUpdatedAt := loanpolicyMixinFields0[2].Descriptor()
	// loanpolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	loanpolicy.DefaultUpdatedAt = loanpolicyDescUpdatedAt.Default.(func() time.Time)
	// loanpolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	loanpolicy.UpdateDefaultUpdatedAt = loanpolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	// loanpolicyDescName is the schema descriptor for name field.
	loanpolicyDescName := loanpolicyFields[0].Descriptor()
	// loanpolicy.NameValidator is a validator for the "name" field. It is called by the builders before save.
	loanpolicy.NameValidator = loanpolicyDescName.Validators[0].(func(string) error)
	// loanpolicyDescLoanPeriodDays is the schema descriptor for loan_period_days field.
	loanpolicyDescLoanPeriodDays := loanpolicyFields[1].Descriptor()
	// loanpolicy.DefaultLoanPeriodDays holds the default value on creation for the loan_period_days field.
	loanpolicy.DefaultLoanPeriodDays = loanpolicyDescLoanPeriodDays.Default.(int)
	// loanpolicyDescMaxRenewals is the schema descriptor for max_renewals field.
	loanpolicyDescMaxRenewals := loanpolicyFields[2].Descriptor()
	// loanpolicy.DefaultMaxRenewals holds the default value on creation for the max_renewals field.
	loanpolicy.DefaultMaxRenewals = loanpolicyDescMaxRenewals.Default.(int)
	// loanpolicyDescHoldable is the schema descriptor for holdable field.
	loanpolicyDescHoldable := loanpolicyFields[3].Descriptor()
	// loanpolicy.DefaultHoldable holds the default value on creation for the holdable field.
	loanpolicy.DefaultHoldable = loanpolicyDescHoldable.Default.(bool)
	// loanpolicyDescFinePerDay is the schema descriptor for fine_per_day field.
	loanpolicyDescFinePerDay := loanpolicyFields[4].Descriptor()
	// loanpolicy.DefaultFinePerDay holds the default value on creation for the fine_per_day field.
	loanpolicy.DefaultFinePerDay = loanpolicyDescFinePerDay.Default.(decimal.Decimal)
	// loanpolicyDescGraceDays is the schema descriptor for grace_days field.
	loanpolicyDescGraceDays := loanpolicyFields[5].Descriptor()
	// loanpolicy.DefaultGraceDays holds the default value on creation for the grace_days field.
	loanpolicy.DefaultGraceDays = loanpolicyDescGraceDays.Default.(int)
	// loanpolicyDescIsDefault is the schema descriptor for is_default field.
	loanpolicyDescIsDefault := loanpolicyFields[6].Descriptor()
	// loanpolicy.DefaultIsDefault holds the default value on creation for the is_default field.
	loanpolicy.DefaultIsDefault = loanpolicyDescIsDefault.Default.(bool)
	// loanpolicyDescID is the schema descriptor for id field.
	loanpolicyDescID := loanpolicyMixinFields0[0].Descriptor()
	// loanpolicy.DefaultID holds the default value on creation for the id field.
	loanpolicy.DefaultID = loanpolicyDescID.Default.(func() uuid.UUID)
	memberMixin := schema.Member{}.Mixin()
	memberMixinFields0 := memberMixin[0].Fields()
	_ = memberMixinFields0
	memberFields := schema.Member{}.Fields()
	_ = memberFields
	// memberDescCreatedAt is the schema descriptor for created_at field.
	memberDescCreatedAt := memberMixinFields0[1].Descriptor()
	// member.DefaultCreatedAt holds the default value on creation for the created_at field.
	member.DefaultCreatedAt = memberDescCreatedAt.Default.(func() time.Time)
	// memberDescUpdatedAt is the schema descriptor for updated_at field.
	memberDescUpdatedAt := memberMixinFields0[2].Descriptor()
	// member.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	member.DefaultUpdatedAt = memberDescUpdatedAt.Default.(func() time.Time)
	// member.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	member.UpdateDefaultUpdatedAt = memberDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memberDescMembershipNo is the schema descriptor for membership_no field.
	memberDescMembershipNo := memberFields[0].Descriptor()
	// member.MembershipNoValidator is a validator for the "membership_no" field. It is called by the builders before save.
	member.MembershipNoValidator = memberDescMembershipNo.Validators[0].(func(string) error)
	// memberDescIsWalkIn is the schema descriptor for is_walk_in field.
	memberDescIsWalkIn := memberFields[9].Descriptor()
	// member.DefaultIsWalkIn holds the default value on creation for the is_walk_in field.
	member.DefaultIsWalkIn = memberDescIsWalkIn.Default.(bool)
	// memberDescID is the schema descriptor for id field.
	memberDescID := memberMixinFields0[0].Descriptor()
	// member.DefaultID holds the default value on creation for the id field.
	member.DefaultID = memberDescID.Default.(func() uuid.UUID)
	membertierMixin := schema.MemberTier{}.Mixin()
	membertierMixinFields0 := membertierMixin[0].Fields()
	_ = membertierMixinFields0
	membertierFields := schema.MemberTier{}.Fields()
	_ = membertierFields
	// membertierDescCreatedAt is the schema descriptor for created_at field.
	membertierDescCreatedAt := membertierMixinFields0[1].Descriptor()
	// membertier.DefaultCreatedAt holds the default value on creation for the created_at field.
	membertier.DefaultCreatedAt = membertierDescCreatedAt.Default.(func() time.Time)
	// membertierDescUpdatedAt is the schema descriptor for updated_at field.
	membertierDescUpdatedAt := membertierMixinFields0[2].Descriptor()
	// membertier.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membertier.DefaultUpdatedAt = membertierDescUpdatedAt.Default.(func() time.Time)
	// membertier.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membertier.UpdateDefaultUpdatedAt = membertierDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membertierDescName is the schema descriptor for name field.
	membertierDescName := membertierFields[0].Descriptor()
	// membertier.NameValidator is a validator for the "name" field. It is called by the builders before save.
	membertier.NameValidator = membertierDescName.Validators[0].(func(string) error)
	// membertierDescMaxConcurrentLoans is the schema descriptor for max_concurrent_loans field.
	membertierDescMaxConcurrentLoans := membertierFields[1].Descriptor()
	// membertier.DefaultMaxConcurrentLoans holds the default value on creation for the max_concurrent_loans field.
	membertier.DefaultMaxConcurrentLoans = membertierDescMaxConcurrentLoans.Default.(int)
	// membertierDescLoanPeriodDays is the schema descriptor for loan_period_days field.
	membertierDescLoanPeriodDays := membertierFields[2].Descriptor()
	// membertier.DefaultLoanPeriodDays holds the default value on creation for the loan_period_days field.
	membertier.DefaultLoanPeriodDays = membertierDescLoanPeriodDays.Default.(int)
	// membertierDescMaxRenewals is the schema descriptor for max_renewals field.
	membertierDescMaxRenewals := membertierFields[3].Descriptor()
	// membertier.DefaultMaxRenewals holds the default value on creation for the max_renewals field.
	membertier.DefaultMaxRenewals = membertierDescMaxRenewals.Default.(int)
	// membertierDescHoldLimit is the schema descriptor for hold_limit field.
	membertierDescHoldLimit := membertierFields[4].Descriptor()
	// membertier.DefaultHoldLimit holds the default value on creation for the hold_limit field.
	membertier.DefaultHoldLimit = membertierDescHoldLimit.Default.(int)
	// membertierDescEbookConcurrentLimit is the schema descriptor for ebook_concurrent_limit field.
	membertierDescEbookConcurrentLimit := membertierFields[5].Descriptor()
	// membertier.DefaultEbookConcurrentLimit holds the default value on creation for the ebook_concurrent_limit field.
	membertier.DefaultEbookConcurrentLimit = membertierDescEbookConcurrentLimit.Default.(int)
	// membertierDescDailyFineRate is the schema descriptor for daily_fine_rate field.
	membertierDescDailyFineRate := membertierFields[6].Descriptor()
	// membertier.DefaultDailyFineRate holds the default value on creation for the daily_fine_rate field.
	membertier.DefaultDailyFineRate = membertierDescDailyFineRate.Default.(decimal.Decimal)
	// membertierDescMaxFineBeforeBlock is the schema descriptor for max_fine_before_block field.
	membertierDescMaxFineBeforeBlock := membertierFields[7].Descriptor()
	// membertier.DefaultMaxFineBeforeBlock holds the default value on creation for the max_fine_before_block field.
	membertier.DefaultMaxFineBeforeBlock = membertierDescMaxFineBeforeBlock.Default.(decimal.Decimal)
	// membertierDescAnnualFee is the schema descriptor for annual_fee field.
	membertierDescAnnualFee := membertierFields[8].Descriptor()
	// membertier.DefaultAnnualFee holds the default value on creation for the annual_fee field.
	membertier.DefaultAnnualFee = membertierDescAnnualFee.Default.(decimal.Decimal)
	// membertierDescIsDefault is the schema descriptor for is_default field.
	membertierDescIsDefault := membertierFields[9].Descriptor()
	// membertier.DefaultIsDefault holds the default value on creation for the is_default field.
	membertier.DefaultIsDefault = membertierDescIsDefault.Default.(bool)
	// membertierDescID is the schema descriptor for id field.
	membertierDescID := membertierMixinFields0[0].Descriptor()
	// membertier.DefaultID holds the default value on creation for the id field.
	membertier.DefaultID = membertierDescID.Default.(func() uuid.UUID)
	membershipfeeMixin := schema.MembershipFee{}.Mixin()
	membershipfeeMixinFields0 := membershipfeeMixin[0].Fields()
	_ = membershipfeeMixinFields0
	membershipfeeFields := schema.MembershipFee{}.Fields()
	_ = membershipfeeFields
	// membershipfeeDescCreatedAt is the schema descriptor for created_at field.
	membershipfeeDescCreatedAt := membershipfeeMixinFields0[1].Descriptor()
	// membershipfee.DefaultCreatedAt holds the default value on creation for the created_at field.
	membershipfee.DefaultCreatedAt = membershipfeeDescCreatedAt.Default.(func() time.Time)
	// membershipfeeDescUpdatedAt is the schema descriptor for updated_at field.
	membershipfeeDescUpdatedAt := membershipfeeMixinFields0[2].Descriptor()
	// membershipfee.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	membershipfee.DefaultUpdatedAt = membershipfeeDescUpdatedAt.Default.(func() time.Time)
	// membershipfee.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	membershipfee.UpdateDefaultUpdatedAt = membershipfeeDescUpdatedAt.UpdateDefault.(func() time.Time)
	// membershipfeeDescAmount is the schema descriptor for amount field.
	membershipfeeDescAmount := membershipfeeFields[3].Descriptor()
	// membershipfee.DefaultAmount holds the default value on creation for the amount field.
	membershipfee.DefaultAmount = membershipfeeDescAmount.Default.(decimal.Decimal)
	// membershipfeeDescID is the schema descriptor for id field.
	membershipfeeDescID := membershipfeeMixinFields0[0].Descriptor()
	// membershipfee.DefaultID holds the default value on creation for the id field.
	membershipfee.DefaultID = membershipfeeDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = outboxeventDescAggregateType.Validators[0].(func(string) error)
	// outboxeventDescAggregateID is the schema descriptor for aggregate_id field.
	outboxeventDescAggregateID := outboxeventFields[3].Descriptor()
	// outboxevent.AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	outboxevent.AggregateIDValidator = outboxeventDescAggregateID.Validators[0].(func(string) error)
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[4].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = outboxeventDescEventType.Validators[0].(func(string) error)
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[6].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(string)
	// outboxeventDescAttempts is the schema descriptor for attempts field.
	outboxeventDescAttempts := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultAttempts holds the default value on creation for the attempts field.
	outboxevent.DefaultAttempts = outboxeventDescAttempts.Default.(int)
	// outboxeventDescCreatedAt is the schema descriptor for created_at field.
	outboxeventDescCreatedAt := outboxeventFields[11].Descriptor()
	// outboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	outboxevent.DefaultCreatedAt = outboxeventDescCreatedAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	publisherMixin := schema.Publisher{}.Mixin()
	publisherMixinFields0 := publisherMixin[0].Fields()
	_ = publisherMixinFields0
	publisherFields := schema.Publisher{}.Fields()
	_ = publisherFields
	// publisherDescCreatedAt is the schema descriptor for created_at field.
	publisherDescCreatedAt := publisherMixinFields0[1].Descriptor()
	// publisher.DefaultCreatedAt holds the default value on creation for the created_at field.
	publisher.DefaultCreatedAt = publisherDescCreatedAt.Default.(func() time.Time)
	// publisherDescUpdatedAt is the schema descriptor for updated_at field.
	publisherDescUpdatedAt := publisherMixinFields0[2].Descriptor()
	// publisher.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	publisher.DefaultUpdatedAt = publisherDescUpdatedAt.Default.(func() time.Time)
	// publisher.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	publisher.UpdateDefaultUpdatedAt = publisherDescUpdatedAt.UpdateDefault.(func() time.Time)
	// publisherDescName is the schema descriptor for name field.
	publisherDescName := publisherFields[0].Descriptor()
	// publisher.NameValidator is a validator for the "name" field. It is called by the builders before save.
	publisher.NameValidator = publisherDescName.Validators[0].(func(string) error)
	// publisherDescID is the schema descriptor for id field.
	publisherDescID := publisherMixinFields0[0].Descriptor()
	// publisher.DefaultID holds the default value on creation for the id field.
	publisher.DefaultID = publisherDescID.Default.(func() uuid.UUID)
	serviceconfigFields := schema.ServiceConfig{}.Fields()
	_ = serviceconfigFields
	// serviceconfigDescConfigKey is the schema descriptor for config_key field.
	serviceconfigDescConfigKey := serviceconfigFields[2].Descriptor()
	// serviceconfig.ConfigKeyValidator is a validator for the "config_key" field. It is called by the builders before save.
	serviceconfig.ConfigKeyValidator = serviceconfigDescConfigKey.Validators[0].(func(string) error)
	// serviceconfigDescConfigValue is the schema descriptor for config_value field.
	serviceconfigDescConfigValue := serviceconfigFields[3].Descriptor()
	// serviceconfig.ConfigValueValidator is a validator for the "config_value" field. It is called by the builders before save.
	serviceconfig.ConfigValueValidator = serviceconfigDescConfigValue.Validators[0].(func(string) error)
	// serviceconfigDescConfigType is the schema descriptor for config_type field.
	serviceconfigDescConfigType := serviceconfigFields[4].Descriptor()
	// serviceconfig.DefaultConfigType holds the default value on creation for the config_type field.
	serviceconfig.DefaultConfigType = serviceconfigDescConfigType.Default.(string)
	// serviceconfigDescIsSecret is the schema descriptor for is_secret field.
	serviceconfigDescIsSecret := serviceconfigFields[6].Descriptor()
	// serviceconfig.DefaultIsSecret holds the default value on creation for the is_secret field.
	serviceconfig.DefaultIsSecret = serviceconfigDescIsSecret.Default.(bool)
	// serviceconfigDescCreatedAt is the schema descriptor for created_at field.
	serviceconfigDescCreatedAt := serviceconfigFields[7].Descriptor()
	// serviceconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	serviceconfig.DefaultCreatedAt = serviceconfigDescCreatedAt.Default.(func() time.Time)
	// serviceconfigDescUpdatedAt is the schema descriptor for updated_at field.
	serviceconfigDescUpdatedAt := serviceconfigFields[8].Descriptor()
	// serviceconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	serviceconfig.DefaultUpdatedAt = serviceconfigDescUpdatedAt.Default.(func() time.Time)
	// serviceconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	serviceconfig.UpdateDefaultUpdatedAt = serviceconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
	// serviceconfigDescID is the schema descriptor for id field.
	serviceconfigDescID := serviceconfigFields[0].Descriptor()
	// serviceconfig.DefaultID holds the default value on creation for the id field.
	serviceconfig.DefaultID = serviceconfigDescID.Default.(func() uuid.UUID)
	stockcountMixin := schema.StockCount{}.Mixin()
	stockcountMixinFields0 := stockcountMixin[0].Fields()
	_ = stockcountMixinFields0
	stockcountFields := schema.StockCount{}.Fields()
	_ = stockcountFields
	// stockcountDescCreatedAt is the schema descriptor for created_at field.
	stockcountDescCreatedAt := stockcountMixinFields0[1].Descriptor()
	// stockcount.DefaultCreatedAt holds the default value on creation for the created_at field.
	stockcount.DefaultCreatedAt = stockcountDescCreatedAt.Default.(func() time.Time)
	// stockcountDescUpdatedAt is the schema descriptor for updated_at field.
	stockcountDescUpdatedAt := stockcountMixinFields0[2].Descriptor()
	// stockcount.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	stockcount.DefaultUpdatedAt = stockcountDescUpdatedAt.Default.(func() time.Time)
	// stockcount.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	stockcount.UpdateDefaultUpdatedAt = stockcountDescUpdatedAt.UpdateDefault.(func() time.Time)
	// stockcountDescExpectedCount is the schema descriptor for expected_count field.
	stockcountDescExpectedCount := stockcountFields[4].Descriptor()
	// stockcount.DefaultExpectedCount holds the default value on creation for the expected_count field.
	stockcount.DefaultExpectedCount = stockcountDescExpectedCount.Default.(int)
	// stockcountDescScannedCount is the schema descriptor for scanned_count field.
	stockcountDescScannedCount := stockcountFields[5].Descriptor()
	// stockcount.DefaultScannedCount holds the default value on creation for the scanned_count field.
	stockcount.DefaultScannedCount = stockcountDescScannedCount.Default.(int)
	// stockcountDescMissingCount is the schema descriptor for missing_count field.
	stockcountDescMissingCount := stockcountFields[6].Descriptor()
	// stockcount.DefaultMissingCount holds the default value on creation for the missing_count field.
	stockcount.DefaultMissingCount = stockcountDescMissingCount.Default.(int)
	// stockcountDescID is the schema descriptor for id field.
	stockcountDescID := stockcountMixinFields0[0].Descriptor()
	// stockcount.DefaultID holds the default value on creation for the id field.
	stockcount.DefaultID = stockcountDescID.Default.(func() uuid.UUID)
	subjectMixin := schema.Subject{}.Mixin()
	subjectMixinFields0 := subjectMixin[0].Fields()
	_ = subjectMixinFields0
	subjectFields := schema.Subject{}.Fields()
	_ = subjectFields
	// subjectDescCreatedAt is the schema descriptor for created_at field.
	subjectDescCreatedAt := subjectMixinFields0[1].Descriptor()
	// subject.DefaultCreatedAt holds the default value on creation for the created_at field.
	subject.DefaultCreatedAt = subjectDescCreatedAt.Default.(func() time.Time)
	// subjectDescUpdatedAt is the schema descriptor for updated_at field.
	subjectDescUpdatedAt := subjectMixinFields0[2].Descriptor()
	// subject.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subject.DefaultUpdatedAt = subjectDescUpdatedAt.Default.(func() time.Time)
	// subject.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subject.UpdateDefaultUpdatedAt = subjectDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subjectDescName is the schema descriptor for name field.
	subjectDescName := subjectFields[0].Descriptor()
	// subject.NameValidator is a validator for the "name" field. It is called by the builders before save.
	subject.NameValidator = subjectDescName.Validators[0].(func(string) error)
	// subjectDescID is the schema descriptor for id field.
	subjectDescID := subjectMixinFields0[0].Descriptor()
	// subject.DefaultID holds the default value on creation for the id field.
	subject.DefaultID = subjectDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescSlug is the schema descriptor for slug field.
	tenantDescSlug := tenantFields[1].Descriptor()
	// tenant.SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	tenant.SlugValidator = tenantDescSlug.Validators[0].(func(string) error)
	// tenantDescIsActive is the schema descriptor for is_active field.
	tenantDescIsActive := tenantFields[4].Descriptor()
	// tenant.DefaultIsActive holds the default value on creation for the is_active field.
	tenant.DefaultIsActive = tenantDescIsActive.Default.(bool)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[5].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescUpdatedAt is the schema descriptor for updated_at field.
	tenantDescUpdatedAt := tenantFields[6].Descriptor()
	// tenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenant.DefaultUpdatedAt = tenantDescUpdatedAt.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	tenant.UpdateDefaultUpdatedAt = tenantDescUpdatedAt.UpdateDefault.(func() time.Time)
}
