// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/library-service/internal/ent/stockcount"
	"github.com/google/uuid"
)

// StockCountCreate is the builder for creating a StockCount entity.
type StockCountCreate struct {
	config
	mutation *StockCountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *StockCountCreate) SetCreatedAt(v time.Time) *StockCountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableCreatedAt(v *time.Time) *StockCountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StockCountCreate) SetUpdatedAt(v time.Time) *StockCountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableUpdatedAt(v *time.Time) *StockCountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *StockCountCreate) SetTenantID(v uuid.UUID) *StockCountCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetBranchID sets the "branch_id" field.
func (_c *StockCountCreate) SetBranchID(v uuid.UUID) *StockCountCreate {
	_c.mutation.SetBranchID(v)
	return _c
}

// SetReference sets the "reference" field.
func (_c *StockCountCreate) SetReference(v string) *StockCountCreate {
	_c.mutation.SetReference(v)
	return _c
}

// SetNillableReference sets the "reference" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableReference(v *string) *StockCountCreate {
	if v != nil {
		_c.SetReference(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StockCountCreate) SetStatus(v stockcount.Status) *StockCountCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableStatus(v *stockcount.Status) *StockCountCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetScannedCopyIds sets the "scanned_copy_ids" field.
func (_c *StockCountCreate) SetScannedCopyIds(v []string) *StockCountCreate {
	_c.mutation.SetScannedCopyIds(v)
	return _c
}

// SetExpectedCount sets the "expected_count" field.
func (_c *StockCountCreate) SetExpectedCount(v int) *StockCountCreate {
	_c.mutation.SetExpectedCount(v)
	return _c
}

// SetNillableExpectedCount sets the "expected_count" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableExpectedCount(v *int) *StockCountCreate {
	if v != nil {
		_c.SetExpectedCount(*v)
	}
	return _c
}

// SetScannedCount sets the "scanned_count" field.
func (_c *StockCountCreate) SetScannedCount(v int) *StockCountCreate {
	_c.mutation.SetScannedCount(v)
	return _c
}

// SetNillableScannedCount sets the "scanned_count" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableScannedCount(v *int) *StockCountCreate {
	if v != nil {
		_c.SetScannedCount(*v)
	}
	return _c
}

// SetMissingCount sets the "missing_count" field.
func (_c *StockCountCreate) SetMissingCount(v int) *StockCountCreate {
	_c.mutation.SetMissingCount(v)
	return _c
}

// SetNillableMissingCount sets the "missing_count" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableMissingCount(v *int) *StockCountCreate {
	if v != nil {
		_c.SetMissingCount(*v)
	}
	return _c
}

// SetCountedBy sets the "counted_by" field.
func (_c *StockCountCreate) SetCountedBy(v string) *StockCountCreate {
	_c.mutation.SetCountedBy(v)
	return _c
}

// SetNillableCountedBy sets the "counted_by" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableCountedBy(v *string) *StockCountCreate {
	if v != nil {
		_c.SetCountedBy(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *StockCountCreate) SetCompletedAt(v time.Time) *StockCountCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableCompletedAt(v *time.Time) *StockCountCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StockCountCreate) SetID(v uuid.UUID) *StockCountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *StockCountCreate) SetNillableID(v *uuid.UUID) *StockCountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the StockCountMutation object of the builder.
func (_c *StockCountCreate) Mutation() *StockCountMutation {
	return _c.mutation
}

// Save creates the StockCount in the database.
func (_c *StockCountCreate) Save(ctx context.Context) (*StockCount, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StockCountCreate) SaveX(ctx context.Context) *StockCount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StockCountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StockCountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StockCountCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := stockcount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := stockcount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := stockcount.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ExpectedCount(); !ok {
		v := stockcount.DefaultExpectedCount
		_c.mutation.SetExpectedCount(v)
	}
	if _, ok := _c.mutation.ScannedCount(); !ok {
		v := stockcount.DefaultScannedCount
		_c.mutation.SetScannedCount(v)
	}
	if _, ok := _c.mutation.MissingCount(); !ok {
		v := stockcount.DefaultMissingCount
		_c.mutation.SetMissingCount(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := stockcount.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StockCountCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StockCount.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StockCount.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "StockCount.tenant_id"`)}
	}
	if _, ok := _c.mutation.BranchID(); !ok {
		return &ValidationError{Name: "branch_id", err: errors.New(`ent: missing required field "StockCount.branch_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StockCount.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := stockcount.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StockCount.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpectedCount(); !ok {
		return &ValidationError{Name: "expected_count", err: errors.New(`ent: missing required field "StockCount.expected_count"`)}
	}
	if _, ok := _c.mutation.ScannedCount(); !ok {
		return &ValidationError{Name: "scanned_count", err: errors.New(`ent: missing required field "StockCount.scanned_count"`)}
	}
	if _, ok := _c.mutation.MissingCount(); !ok {
		return &ValidationError{Name: "missing_count", err: errors.New(`ent: missing required field "StockCount.missing_count"`)}
	}
	return nil
}

func (_c *StockCountCreate) sqlSave(ctx context.Context) (*StockCount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StockCountCreate) createSpec() (*StockCount, *sqlgraph.CreateSpec) {
	var (
		_node = &StockCount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stockcount.Table, sqlgraph.NewFieldSpec(stockcount.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(stockcount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(stockcount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(stockcount.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.BranchID(); ok {
		_spec.SetField(stockcount.FieldBranchID, field.TypeUUID, value)
		_node.BranchID = value
	}
	if value, ok := _c.mutation.Reference(); ok {
		_spec.SetField(stockcount.FieldReference, field.TypeString, value)
		_node.Reference = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(stockcount.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ScannedCopyIds(); ok {
		_spec.SetField(stockcount.FieldScannedCopyIds, field.TypeJSON, value)
		_node.ScannedCopyIds = value
	}
	if value, ok := _c.mutation.ExpectedCount(); ok {
		_spec.SetField(stockcount.FieldExpectedCount, field.TypeInt, value)
		_node.ExpectedCount = value
	}
	if value, ok := _c.mutation.ScannedCount(); ok {
		_spec.SetField(stockcount.FieldScannedCount, field.TypeInt, value)
		_node.ScannedCount = value
	}
	if value, ok := _c.mutation.MissingCount(); ok {
		_spec.SetField(stockcount.FieldMissingCount, field.TypeInt, value)
		_node.MissingCount = value
	}
	if value, ok := _c.mutation.CountedBy(); ok {
		_spec.SetField(stockcount.FieldCountedBy, field.TypeString, value)
		_node.CountedBy = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(stockcount.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockCount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockCountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *StockCountCreate) OnConflict(opts ...sql.ConflictOption) *StockCountUpsertOne {
	_c.conflict = opts
	return &StockCountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockCount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StockCountCreate) OnConflictColumns(columns ...string) *StockCountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StockCountUpsertOne{
		create: _c,
	}
}

type (
	// StockCountUpsertOne is the builder for "upsert"-ing
	//  one StockCount node.
	StockCountUpsertOne struct {
		create *StockCountCreate
	}

	// StockCountUpsert is the "OnConflict" setter.
	StockCountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *StockCountUpsert) SetUpdatedAt(v time.Time) *StockCountUpsert {
	u.Set(stockcount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateUpdatedAt() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldUpdatedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *StockCountUpsert) SetTenantID(v uuid.UUID) *StockCountUpsert {
	u.Set(stockcount.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateTenantID() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldTenantID)
	return u
}

// SetBranchID sets the "branch_id" field.
func (u *StockCountUpsert) SetBranchID(v uuid.UUID) *StockCountUpsert {
	u.Set(stockcount.FieldBranchID, v)
	return u
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateBranchID() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldBranchID)
	return u
}

// SetReference sets the "reference" field.
func (u *StockCountUpsert) SetReference(v string) *StockCountUpsert {
	u.Set(stockcount.FieldReference, v)
	return u
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateReference() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldReference)
	return u
}

// ClearReference clears the value of the "reference" field.
func (u *StockCountUpsert) ClearReference() *StockCountUpsert {
	u.SetNull(stockcount.FieldReference)
	return u
}

// SetStatus sets the "status" field.
func (u *StockCountUpsert) SetStatus(v stockcount.Status) *StockCountUpsert {
	u.Set(stockcount.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateStatus() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldStatus)
	return u
}

// SetScannedCopyIds sets the "scanned_copy_ids" field.
func (u *StockCountUpsert) SetScannedCopyIds(v []string) *StockCountUpsert {
	u.Set(stockcount.FieldScannedCopyIds, v)
	return u
}

// UpdateScannedCopyIds sets the "scanned_copy_ids" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateScannedCopyIds() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldScannedCopyIds)
	return u
}

// ClearScannedCopyIds clears the value of the "scanned_copy_ids" field.
func (u *StockCountUpsert) ClearScannedCopyIds() *StockCountUpsert {
	u.SetNull(stockcount.FieldScannedCopyIds)
	return u
}

// SetExpectedCount sets the "expected_count" field.
func (u *StockCountUpsert) SetExpectedCount(v int) *StockCountUpsert {
	u.Set(stockcount.FieldExpectedCount, v)
	return u
}

// UpdateExpectedCount sets the "expected_count" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateExpectedCount() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldExpectedCount)
	return u
}

// AddExpectedCount adds v to the "expected_count" field.
func (u *StockCountUpsert) AddExpectedCount(v int) *StockCountUpsert {
	u.Add(stockcount.FieldExpectedCount, v)
	return u
}

// SetScannedCount sets the "scanned_count" field.
func (u *StockCountUpsert) SetScannedCount(v int) *StockCountUpsert {
	u.Set(stockcount.FieldScannedCount, v)
	return u
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateScannedCount() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldScannedCount)
	return u
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *StockCountUpsert) AddScannedCount(v int) *StockCountUpsert {
	u.Add(stockcount.FieldScannedCount, v)
	return u
}

// SetMissingCount sets the "missing_count" field.
func (u *StockCountUpsert) SetMissingCount(v int) *StockCountUpsert {
	u.Set(stockcount.FieldMissingCount, v)
	return u
}

// UpdateMissingCount sets the "missing_count" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateMissingCount() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldMissingCount)
	return u
}

// AddMissingCount adds v to the "missing_count" field.
func (u *StockCountUpsert) AddMissingCount(v int) *StockCountUpsert {
	u.Add(stockcount.FieldMissingCount, v)
	return u
}

// SetCountedBy sets the "counted_by" field.
func (u *StockCountUpsert) SetCountedBy(v string) *StockCountUpsert {
	u.Set(stockcount.FieldCountedBy, v)
	return u
}

// UpdateCountedBy sets the "counted_by" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateCountedBy() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldCountedBy)
	return u
}

// ClearCountedBy clears the value of the "counted_by" field.
func (u *StockCountUpsert) ClearCountedBy() *StockCountUpsert {
	u.SetNull(stockcount.FieldCountedBy)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *StockCountUpsert) SetCompletedAt(v time.Time) *StockCountUpsert {
	u.Set(stockcount.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *StockCountUpsert) UpdateCompletedAt() *StockCountUpsert {
	u.SetExcluded(stockcount.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *StockCountUpsert) ClearCompletedAt() *StockCountUpsert {
	u.SetNull(stockcount.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StockCount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockcount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockCountUpsertOne) UpdateNewValues() *StockCountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(stockcount.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(stockcount.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockCount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StockCountUpsertOne) Ignore() *StockCountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockCountUpsertOne) DoNothing() *StockCountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockCountCreate.OnConflict
// documentation for more info.
func (u *StockCountUpsertOne) Update(set func(*StockCountUpsert)) *StockCountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockCountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StockCountUpsertOne) SetUpdatedAt(v time.Time) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateUpdatedAt() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *StockCountUpsertOne) SetTenantID(v uuid.UUID) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateTenantID() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateTenantID()
	})
}

// SetBranchID sets the "branch_id" field.
func (u *StockCountUpsertOne) SetBranchID(v uuid.UUID) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetBranchID(v)
	})
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateBranchID() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateBranchID()
	})
}

// SetReference sets the "reference" field.
func (u *StockCountUpsertOne) SetReference(v string) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetReference(v)
	})
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateReference() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateReference()
	})
}

// ClearReference clears the value of the "reference" field.
func (u *StockCountUpsertOne) ClearReference() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearReference()
	})
}

// SetStatus sets the "status" field.
func (u *StockCountUpsertOne) SetStatus(v stockcount.Status) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateStatus() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateStatus()
	})
}

// SetScannedCopyIds sets the "scanned_copy_ids" field.
func (u *StockCountUpsertOne) SetScannedCopyIds(v []string) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetScannedCopyIds(v)
	})
}

// UpdateScannedCopyIds sets the "scanned_copy_ids" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateScannedCopyIds() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateScannedCopyIds()
	})
}

// ClearScannedCopyIds clears the value of the "scanned_copy_ids" field.
func (u *StockCountUpsertOne) ClearScannedCopyIds() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearScannedCopyIds()
	})
}

// SetExpectedCount sets the "expected_count" field.
func (u *StockCountUpsertOne) SetExpectedCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetExpectedCount(v)
	})
}

// AddExpectedCount adds v to the "expected_count" field.
func (u *StockCountUpsertOne) AddExpectedCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.AddExpectedCount(v)
	})
}

// UpdateExpectedCount sets the "expected_count" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateExpectedCount() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateExpectedCount()
	})
}

// SetScannedCount sets the "scanned_count" field.
func (u *StockCountUpsertOne) SetScannedCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetScannedCount(v)
	})
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *StockCountUpsertOne) AddScannedCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.AddScannedCount(v)
	})
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateScannedCount() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateScannedCount()
	})
}

// SetMissingCount sets the "missing_count" field.
func (u *StockCountUpsertOne) SetMissingCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetMissingCount(v)
	})
}

// AddMissingCount adds v to the "missing_count" field.
func (u *StockCountUpsertOne) AddMissingCount(v int) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.AddMissingCount(v)
	})
}

// UpdateMissingCount sets the "missing_count" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateMissingCount() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateMissingCount()
	})
}

// SetCountedBy sets the "counted_by" field.
func (u *StockCountUpsertOne) SetCountedBy(v string) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetCountedBy(v)
	})
}

// UpdateCountedBy sets the "counted_by" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateCountedBy() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateCountedBy()
	})
}

// ClearCountedBy clears the value of the "counted_by" field.
func (u *StockCountUpsertOne) ClearCountedBy() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearCountedBy()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *StockCountUpsertOne) SetCompletedAt(v time.Time) *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *StockCountUpsertOne) UpdateCompletedAt() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *StockCountUpsertOne) ClearCompletedAt() *StockCountUpsertOne {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *StockCountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockCountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockCountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StockCountUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: StockCountUpsertOne.ID is not supported by MySQL driver. Use StockCountUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StockCountUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StockCountCreateBulk is the builder for creating many StockCount entities in bulk.
type StockCountCreateBulk struct {
	config
	err      error
	builders []*StockCountCreate
	conflict []sql.ConflictOption
}

// Save creates the StockCount entities in the database.
func (_c *StockCountCreateBulk) Save(ctx context.Context) ([]*StockCount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StockCount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StockCountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StockCountCreateBulk) SaveX(ctx context.Context) []*StockCount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StockCountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StockCountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StockCount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StockCountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *StockCountCreateBulk) OnConflict(opts ...sql.ConflictOption) *StockCountUpsertBulk {
	_c.conflict = opts
	return &StockCountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StockCount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StockCountCreateBulk) OnConflictColumns(columns ...string) *StockCountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StockCountUpsertBulk{
		create: _c,
	}
}

// StockCountUpsertBulk is the builder for "upsert"-ing
// a bulk of StockCount nodes.
type StockCountUpsertBulk struct {
	create *StockCountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StockCount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stockcount.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StockCountUpsertBulk) UpdateNewValues() *StockCountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(stockcount.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(stockcount.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StockCount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StockCountUpsertBulk) Ignore() *StockCountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StockCountUpsertBulk) DoNothing() *StockCountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StockCountCreateBulk.OnConflict
// documentation for more info.
func (u *StockCountUpsertBulk) Update(set func(*StockCountUpsert)) *StockCountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StockCountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StockCountUpsertBulk) SetUpdatedAt(v time.Time) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateUpdatedAt() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *StockCountUpsertBulk) SetTenantID(v uuid.UUID) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateTenantID() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateTenantID()
	})
}

// SetBranchID sets the "branch_id" field.
func (u *StockCountUpsertBulk) SetBranchID(v uuid.UUID) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetBranchID(v)
	})
}

// UpdateBranchID sets the "branch_id" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateBranchID() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateBranchID()
	})
}

// SetReference sets the "reference" field.
func (u *StockCountUpsertBulk) SetReference(v string) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetReference(v)
	})
}

// UpdateReference sets the "reference" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateReference() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateReference()
	})
}

// ClearReference clears the value of the "reference" field.
func (u *StockCountUpsertBulk) ClearReference() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearReference()
	})
}

// SetStatus sets the "status" field.
func (u *StockCountUpsertBulk) SetStatus(v stockcount.Status) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateStatus() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateStatus()
	})
}

// SetScannedCopyIds sets the "scanned_copy_ids" field.
func (u *StockCountUpsertBulk) SetScannedCopyIds(v []string) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetScannedCopyIds(v)
	})
}

// UpdateScannedCopyIds sets the "scanned_copy_ids" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateScannedCopyIds() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateScannedCopyIds()
	})
}

// ClearScannedCopyIds clears the value of the "scanned_copy_ids" field.
func (u *StockCountUpsertBulk) ClearScannedCopyIds() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearScannedCopyIds()
	})
}

// SetExpectedCount sets the "expected_count" field.
func (u *StockCountUpsertBulk) SetExpectedCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetExpectedCount(v)
	})
}

// AddExpectedCount adds v to the "expected_count" field.
func (u *StockCountUpsertBulk) AddExpectedCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.AddExpectedCount(v)
	})
}

// UpdateExpectedCount sets the "expected_count" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateExpectedCount() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateExpectedCount()
	})
}

// SetScannedCount sets the "scanned_count" field.
func (u *StockCountUpsertBulk) SetScannedCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetScannedCount(v)
	})
}

// AddScannedCount adds v to the "scanned_count" field.
func (u *StockCountUpsertBulk) AddScannedCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.AddScannedCount(v)
	})
}

// UpdateScannedCount sets the "scanned_count" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateScannedCount() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateScannedCount()
	})
}

// SetMissingCount sets the "missing_count" field.
func (u *StockCountUpsertBulk) SetMissingCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetMissingCount(v)
	})
}

// AddMissingCount adds v to the "missing_count" field.
func (u *StockCountUpsertBulk) AddMissingCount(v int) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.AddMissingCount(v)
	})
}

// UpdateMissingCount sets the "missing_count" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateMissingCount() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateMissingCount()
	})
}

// SetCountedBy sets the "counted_by" field.
func (u *StockCountUpsertBulk) SetCountedBy(v string) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetCountedBy(v)
	})
}

// UpdateCountedBy sets the "counted_by" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateCountedBy() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateCountedBy()
	})
}

// ClearCountedBy clears the value of the "counted_by" field.
func (u *StockCountUpsertBulk) ClearCountedBy() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearCountedBy()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *StockCountUpsertBulk) SetCompletedAt(v time.Time) *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *StockCountUpsertBulk) UpdateCompletedAt() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *StockCountUpsertBulk) ClearCompletedAt() *StockCountUpsertBulk {
	return u.Update(func(s *StockCountUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *StockCountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StockCountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StockCountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StockCountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
