// Code generated by ent, DO NOT EDIT.

package documentsequence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/library-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldTenantID, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldKind, v))
}

// Prefix applies equality check predicate on the "prefix" field. It's identical to PrefixEQ.
func Prefix(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldPrefix, v))
}

// NextValue applies equality check predicate on the "next_value" field. It's identical to NextValueEQ.
func NextValue(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldNextValue, v))
}

// PadWidth applies equality check predicate on the "pad_width" field. It's identical to PadWidthEQ.
func PadWidth(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldPadWidth, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldTenantID, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldContainsFold(FieldKind, v))
}

// PrefixEQ applies the EQ predicate on the "prefix" field.
func PrefixEQ(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldPrefix, v))
}

// PrefixNEQ applies the NEQ predicate on the "prefix" field.
func PrefixNEQ(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldPrefix, v))
}

// PrefixIn applies the In predicate on the "prefix" field.
func PrefixIn(vs ...string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldPrefix, vs...))
}

// PrefixNotIn applies the NotIn predicate on the "prefix" field.
func PrefixNotIn(vs ...string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldPrefix, vs...))
}

// PrefixGT applies the GT predicate on the "prefix" field.
func PrefixGT(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldPrefix, v))
}

// PrefixGTE applies the GTE predicate on the "prefix" field.
func PrefixGTE(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldPrefix, v))
}

// PrefixLT applies the LT predicate on the "prefix" field.
func PrefixLT(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldPrefix, v))
}

// PrefixLTE applies the LTE predicate on the "prefix" field.
func PrefixLTE(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldPrefix, v))
}

// PrefixContains applies the Contains predicate on the "prefix" field.
func PrefixContains(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldContains(FieldPrefix, v))
}

// PrefixHasPrefix applies the HasPrefix predicate on the "prefix" field.
func PrefixHasPrefix(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldHasPrefix(FieldPrefix, v))
}

// PrefixHasSuffix applies the HasSuffix predicate on the "prefix" field.
func PrefixHasSuffix(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldHasSuffix(FieldPrefix, v))
}

// PrefixIsNil applies the IsNil predicate on the "prefix" field.
func PrefixIsNil() predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIsNull(FieldPrefix))
}

// PrefixNotNil applies the NotNil predicate on the "prefix" field.
func PrefixNotNil() predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotNull(FieldPrefix))
}

// PrefixEqualFold applies the EqualFold predicate on the "prefix" field.
func PrefixEqualFold(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEqualFold(FieldPrefix, v))
}

// PrefixContainsFold applies the ContainsFold predicate on the "prefix" field.
func PrefixContainsFold(v string) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldContainsFold(FieldPrefix, v))
}

// NextValueEQ applies the EQ predicate on the "next_value" field.
func NextValueEQ(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldNextValue, v))
}

// NextValueNEQ applies the NEQ predicate on the "next_value" field.
func NextValueNEQ(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldNextValue, v))
}

// NextValueIn applies the In predicate on the "next_value" field.
func NextValueIn(vs ...int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldNextValue, vs...))
}

// NextValueNotIn applies the NotIn predicate on the "next_value" field.
func NextValueNotIn(vs ...int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldNextValue, vs...))
}

// NextValueGT applies the GT predicate on the "next_value" field.
func NextValueGT(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldNextValue, v))
}

// NextValueGTE applies the GTE predicate on the "next_value" field.
func NextValueGTE(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldNextValue, v))
}

// NextValueLT applies the LT predicate on the "next_value" field.
func NextValueLT(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldNextValue, v))
}

// NextValueLTE applies the LTE predicate on the "next_value" field.
func NextValueLTE(v int64) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldNextValue, v))
}

// PadWidthEQ applies the EQ predicate on the "pad_width" field.
func PadWidthEQ(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldEQ(FieldPadWidth, v))
}

// PadWidthNEQ applies the NEQ predicate on the "pad_width" field.
func PadWidthNEQ(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNEQ(FieldPadWidth, v))
}

// PadWidthIn applies the In predicate on the "pad_width" field.
func PadWidthIn(vs ...int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldIn(FieldPadWidth, vs...))
}

// PadWidthNotIn applies the NotIn predicate on the "pad_width" field.
func PadWidthNotIn(vs ...int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldNotIn(FieldPadWidth, vs...))
}

// PadWidthGT applies the GT predicate on the "pad_width" field.
func PadWidthGT(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGT(FieldPadWidth, v))
}

// PadWidthGTE applies the GTE predicate on the "pad_width" field.
func PadWidthGTE(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldGTE(FieldPadWidth, v))
}

// PadWidthLT applies the LT predicate on the "pad_width" field.
func PadWidthLT(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLT(FieldPadWidth, v))
}

// PadWidthLTE applies the LTE predicate on the "pad_width" field.
func PadWidthLTE(v int) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.FieldLTE(FieldPadWidth, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DocumentSequence) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DocumentSequence) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DocumentSequence) predicate.DocumentSequence {
	return predicate.DocumentSequence(sql.NotPredicates(p))
}
